# scripts/feeds.py

FEEDS = [
    {"id": "news", "name": "【2ch】コピペ情報局", "url": "http://news.2chblog.jp/index.rdf"},
    {"id": "nwknews", "name": "哲学ニュースnwk", "url": "http://blog.livedoor.jp/nwknews/index.rdf"},
    {"id": "jyoushiki43", "name": "常識的に考えた", "url": "http://blog.livedoor.jp/jyoushiki43/index.rdf"},
    {"id": "dqnplus", "name": "痛いニュース(ﾉ∀`)", "url": "http://blog.livedoor.jp/dqnplus/index.rdf"},
    {"id": "exawarosu", "name": "エクサワロス | ニュースまとめサイト", "url": "http://exawarosu.net/index.rdf"},
    {"id": "yu_ps13", "name": "ゆめ痛 -NEWS ALERT-", "url": "http://blog.livedoor.jp/yu_ps13/index.rdf"},
    {"id": "misopan_news", "name": "みそパンNEWS", "url": "http://blog.livedoor.jp/misopan_news/index.rdf"},
    {"id": "news30over", "name": "ニュース30over", "url": "http://www.news30over.com/index.rdf"},
    {"id": "funs", "name": "ガハろぐNewsヽ(･ω･)/ｽﾞｺｰ", "url": "http://blog.livedoor.jp/funs/index.rdf"},
    {"id": "worldrankingup", "name": "世界ランク速報", "url": "http://worldrankingup.blog41.fc2.com/?xml"},
    {"id": "scienceplus2ch", "name": "(*ﾟ∀ﾟ)ゞカガクニュース隊", "url": "http://www.scienceplus2ch.com/index.rdf"},
    {"id": "milfled", "name": "何でもありんす", "url": "http://milfled.seesaa.net/index.rdf"},
    {"id": "hamusoku", "name": "ハムスター速報", "url": "http://hamusoku.com/index.rdf"},
    {"id": "goldennews", "name": "ゴールデンタイムズ", "url": "http://blog.livedoor.jp/goldennews/index.rdf"},
    {"id": "michaelsan", "name": "もみあげチャ～シュ～", "url": "http://michaelsan.livedoor.biz/index.rdf"},
    {"id": "alfalfalfa", "name": "アルファルファモザイク", "url": "http://alfalfalfa.com/index.rdf"},
    {"id": "lifehack2ch", "name": "ライフハックちゃんねる弐式", "url": "http://lifehack2ch.livedoor.biz/index.rdf"},
    {"id": "esuteru", "name": "はちま起稿", "url": "http://blog.esuteru.com/index.rdf"},
    {"id": "rbkyn844", "name": "暇つぶしニュース", "url": "http://blog.livedoor.jp/rbkyn844/index.rdf"},
    {"id": "kowasugiru", "name": "ザ・ミステリー体験", "url": "http://kowasugiru.blog.jp/index.rdf"},
    {"id": "ainbekker_news2", "name": "まとめニュースちゃんねるぷらす", "url": "http://blog.livedoor.jp/ainbekker-news2/index.rdf"},
    {"id": "watch2chan", "name": "watch＠２ちゃんねる", "url": "http://www.watch2chan.com/index.rdf"},
    {"id": "jyouhouya3", "name": "情報屋さん。", "url": "http://jyouhouya3.net/feed"},
    {"id": "netmorie", "name": "もりえってぃー", "url": "http://netmorie.com/feed"},
    {"id": "newsoku", "name": "NEWSOKU BLOG", "url": "https://newsoku.blog/feed"},
    {"id": "jiken24", "name": "事件ファイル24時", "url": "http://jiken24.com/index.rdf"},
    {"id": "jishin_yogen", "name": "大地震・前兆・予言.com", "url": "https://jishin-yogen.com/?xml"},
    {"id": "2chnewsblog", "name": "２ちゃんねるニュース超速まとめ＋", "url": "http://2chnewsblog.blog.jp/index.rdf"},
    {"id": "jisaka", "name": "汎用型自作PCまとめ", "url": "http://www.jisaka.com/index.rdf"},
    {"id": "warotanien", "name": "わろたにえん速報", "url": "https://warotanien.net/feed"},
    {"id": "gunbird", "name": "銃とバッジは置いていけ", "url": "http://blog.livedoor.jp/gunbird/index.rdf"},
    {"id": "earsoku", "name": "イヤホン速報", "url": "http://earsoku.com/feed"},
    {"id": "na2ka4", "name": "あのころの", "url": "http://na2ka4.blog.fc2.com/?xml"},
    {"id": "airlinehonpo", "name": "エアライン本舗", "url": "http://airlinehonpo.blog.fc2.com/?xml"},
    {"id": "qmanews", "name": "くまニュース", "url": "http://blog.livedoor.jp/qmanews/index.rdf"},
    {"id": "bluejay01_review", "name": "PCパーツまとめ", "url": "http://blog.livedoor.jp/bluejay01-review/index.rdf"},
    {"id": "pocketcamp", "name": "TweetPocket", "url": "http://blog.livedoor.jp/pocketcamp/index.rdf"},
    {"id": "itsoku", "name": "IT速報", "url": "http://blog.livedoor.jp/itsoku/index.rdf"},
    {"id": "rejapan", "name": "Revival Japan 日本復活を叫ぶ", "url": "http://rejapan.blog.jp/index.rdf"},
    {"id": "habanero_ch", "name": "ハバネロちゃんねる", "url": "http://habanero-ch.com/index.rdf"},
    {"id": "xn__t8j4cxcta", "name": "おなやみ通信", "url": "http://xn--t8j4cxcta.com/feed/"},
    {"id": "himatubusokuho", "name": "暇つぶ速報", "url": "http://himatubusokuho.blog.jp/index.rdf"},
    {"id": "puzzleoj3", "name": "たっぷり速報α", "url": "https://puzzleoj3.com/feed"},
    {"id": "news_toranomaki", "name": "とらのまき", "url": "https://www.news-toranomaki.net/?feed=rss2"},
    {"id": "pirori2ch", "name": "ぴろり速報", "url": "http://pirori2ch.com/feed"},
    {"id": "moerunihon", "name": "もえるにほん彡(^)(^)", "url": "http://moerunihon.blog.jp/index.rdf"},
    {"id": "himacyan", "name": "2chまとめ放題", "url": "http://blog.livedoor.jp/himacyan/index.rdf"},
    {"id": "allnews24", "name": "まいにちにゅーす", "url": "https://allnews24.site/feed"},
    {"id": "honsoku", "name": "ほんわか速報", "url": "http://honsoku.com/index.rdf"},
    {"id": "toychan", "name": "トーイチャンネット", "url": "http://toychan.blog.jp/index.rdf"},
    {"id": "zapzapjp", "name": "ZAPZAP!", "url": "https://zapzapjp.com/index.rdf"},
    {"id": "20xxnyu_su", "name": "20ＸＸニュース", "url": "http://20xxnyu-su.blog.jp/index.rdf"},
    {"id": "geolog_book", "name": "ジオろぐ", "url": "http://geolog-book.com/index.rdf"},
    {"id": "pcnewsflash", "name": "ウドログ", "url": "https://pcnewsflash.net/feed/"},
    {"id": "logusoku", "name": "1億人のまとめブログ", "url": "https://logusoku.blog.jp/index.rdf"},
    {"id": "netsokuhou", "name": "ネット速報まとめ超", "url": "https://netsokuhou.seesaa.net/index20.rdf"},
    {"id": "jijinews", "name": "時事ネタニュース速報", "url": "http://jijinews.online/index.rdf"},
    {"id": "metyayaba", "name": "めちゃヤバ速報", "url": "https://metyayaba.com/?feed=rss2"},
    {"id": "nogizakajyoho46", "name": "ネタンゴ！", "url": "https://nogizakajyoho46.com/index.rdf"},
    {"id": "matomemento", "name": "爆速まとめめんと", "url": "https://matomemento.com/feed/rdf/"},
    {"id": "fxya", "name": "政経ch", "url": "http://fxya.blog129.fc2.com/?xml"},
    {"id": "gotagotashita", "name": "ゴタゴタシタニュース", "url": "http://blog.livedoor.jp/gotagotashita/index.rdf"},
    {"id": "kuromacyo", "name": "黒マッチョニュース", "url": "http://kuromacyo.livedoor.biz/index.rdf"},
    {"id": "mogeonna", "name": "いろんな人ガイル", "url": "http://mogeonna.blog.fc2.com/?xml"},
    {"id": "military38", "name": "大艦巨砲主義！", "url": "http://military38.com/index.rdf"},
    {"id": "honmotakeshi", "name": "正義の見方", "url": "https://www.honmotakeshi.com/feed"},
    {"id": "corez18c24_mili777", "name": "軍事・ミリタリー速報☆彡", "url": "http://blog.livedoor.jp/corez18c24-mili777/index.rdf"},
    {"id": "mona_news", "name": "モナニュース", "url": "http://mona-news.com/index.rdf"},
    {"id": "mix2ch", "name": "ミックスニュース速報", "url": "http://mix2ch.blog.fc2.com/?xml"},
    {"id": "seikeidouga", "name": "政経ワロスまとめニュース♪", "url": "http://seikeidouga.blog.jp/index.rdf"},
    {"id": "crx7601", "name": "おーるじゃんる", "url": "http://crx7601.com/index.rdf"},
    {"id": "you1news", "name": "U-1 NEWS", "url": "https://you1news.com/feed"},
    {"id": "news_us", "name": "News U.S.", "url": "https://news-us.org/feed"},
    {"id": "fx2ch", "name": "FX2ちゃんねる|投資系2chまとめ", "url": "http://www.fx2ch.net/feed"},
    {"id": "kasegeru", "name": "稼げるまとめ速報", "url": "http://kasegeru.blog.jp/index.rdf"},
    {"id": "toushichannel", "name": "投資ちゃんねる", "url": "http://toushichannel.net/index.rdf"},
    {"id": "money_life", "name": "マネーライフ2ch|クレジット関連・お金関係", "url": "http://money-life.doorblog.jp/index.rdf"},
    {"id": "ideal2ch", "name": "理想ちゃんねる", "url": "http://ideal2ch.livedoor.biz/index.rdf"},
    {"id": "gadget2ch", "name": "ガジェット2ch", "url": "http://www.gadget2ch.com/index.rdf"},
    {"id": "incident_wo", "name": "日本第一！ニュース録", "url": "https://incident-wo.com/feed/"},
    {"id": "beikokukabu_etf_matome", "name": "米国株ETFまとめ速報", "url": "http://beikokukabu-etf-matome.com/index.rdf"},
    {"id": "j_seiji", "name": "なんJ政治ネタまとめ", "url": "http://j-seiji.blog.jp/index.rdf"},
    {"id": "cashlesssoku", "name": "キャッシュレス速報", "url": "https://cashlesssoku.net/feed/"},
    {"id": "abechan_matome", "name": "まとめ安倍速報", "url": "http://blog.livedoor.jp/abechan_matome/index.rdf"},
    {"id": "jpsoku", "name": "じゃぱそく！", "url": "http://jpsoku.blog.jp/index.rdf"},
    {"id": "crypto_worldwide", "name": "クリプト・ワールドワイド", "url": "https://crypto-worldwide.xyz/feed/"},
    {"id": "gachich", "name": "ガッチリ！ちゃんねる", "url": "https://gachich.net/?xml"},
    {"id": "okanetotoshi", "name": "お金と投資.com", "url": "https://okanetotoshi.com/feed"},
    {"id": "beikokukabu_2ch_matome", "name": "米国株速報", "url": "https://beikokukabu-2ch-matome.com/feed/"},
    {"id": "kumokumowatawata", "name": "コイン速報 | 仮想通貨ニュース・暗号資産相場情報・5chまとめ", "url": "http://blog.livedoor.jp/kumokumowatawata/index.rdf"},
    {"id": "erakokyu", "name": "えら呼吸速報", "url": "http://erakokyu.net/feed"},
    {"id": "o2military", "name": "軍事・ミリタリーログ", "url": "http://o2military.blog.jp/index.rdf"},
    {"id": "invest_news_source", "name": "投資ネタ集めておいたのだ！", "url": "https://invest-news-source.com/?feed=rss2"},
    {"id": "keizai4567", "name": "投資.com", "url": "https://keizai4567.blog.jp/index.rdf"},
    {"id": "netouyonews", "name": "ネトウヨにゅーす。", "url": "http://netouyonews.net/index.rdf"},
    {"id": "warakan2ch", "name": "笑　韓　ブログ", "url": "http://blog.livedoor.jp/warakan2ch/index.rdf"},
    {"id": "hosyusokuhou", "name": "保守速報", "url": "http://hosyusokuhou.jp/index.rdf"},
    {"id": "kimsoku", "name": "キムチ速報", "url": "http://kimsoku.com/index.rdf"},
    {"id": "gensen2ch", "name": "厳選！韓国情報", "url": "http://gensen2ch.com/index.rdf"},
    {"id": "hannichigukoku", "name": "反日愚国　恨寓瘻", "url": "http://hannichigukoku.info/?xml"},
    {"id": "moeruasia", "name": "もえるあじあ(･∀･)", "url": "https://www.moeruasia.net/index.rdf"},
    {"id": "neta_ru", "name": "ねたーる", "url": "http://neta-ru.com/feed"},
    {"id": "asianews2ch", "name": "あじあニュースちゃんねる", "url": "http://asianews2ch.jp/index.rdf"},
    {"id": "mizuhonokuni2ch", "name": "MIZUHO no KUNI ≪2ch≫特亜ニュース", "url": "http://mizuhonokuni2ch.com/feed"},
    {"id": "totalwar", "name": "/)；｀ω´)＜国家総動員報", "url": "http://totalwar.doorblog.jp/index.rdf"},
    {"id": "kokunanmonomousu", "name": "国難にあってもの申す！！", "url": "http://www.kokunanmonomousu.com/index.rdf"},
    {"id": "rakukan", "name": "楽韓Web", "url": "http://rakukan.net/index.rdf"},
    {"id": "china_aggressor_nation", "name": "中国 ~100年遅れの帝国主義~ まとめ", "url": "http://china-aggressor-nation.blog.jp/index.rdf"},
    {"id": "monomi_news", "name": "物見ニュース", "url": "http://monomi-news.blog.jp/index.rdf"},
    {"id": "chantome_2ch", "name": "ちゃんとめ！", "url": "http://chantome-2ch.doorblog.jp/index.rdf"},
    {"id": "sontaku", "name": "ます速ch", "url": "https://sontaku.info/feed"},
    {"id": "katasumisokuhou", "name": "かたすみ速報", "url": "http://katasumisokuhou.blog.jp/index.rdf"},
    {"id": "datsuaron", "name": "脱亜論", "url": "http://datsuaron.blog.jp/index.rdf"},
    {"id": "nida_aru", "name": "ニダアル速報＋", "url": "http://nida-aru.com/index.rdf"},
    {"id": "mazesoku", "name": "まぜるな!キケン!!速報", "url": "http://mazesoku.blog.jp/index.rdf"},
    {"id": "kaikaihanno", "name": "カイカイ反応通信", "url": "http://blog.livedoor.jp/kaikaihanno/index.rdf"},
    {"id": "kaigainohannoublog", "name": "【海外の反応】　パンドラの憂鬱", "url": "http://kaigainohannoublog.blog55.fc2.com/?xml"},
    {"id": "otonarisoku", "name": "海外の反応　お隣速報", "url": "https://www.otonarisoku.com/feed"},
    {"id": "dng65", "name": "どんぐりこ - 海外の反応", "url": "http://dng65.com/?xml"},
    {"id": "gekiyaku", "name": "劇訳表示。", "url": "http://www.gekiyaku.com/index.rdf"},
    {"id": "xxxkikimimixxx", "name": "­海外反応　キキミミ", "url": "http://xxxkikimimixxx.blog.fc2.com/?xml"},
    {"id": "drazuli", "name": "暇は無味無臭の劇薬", "url": "http://blog.livedoor.jp/drazuli/index.rdf"},
    {"id": "sow", "name": "すらるど - 海外の反応", "url": "http://sow.blog.jp/index.rdf"},
    {"id": "taiwannohannou", "name": "台湾の反応ブログ", "url": "http://www.taiwannohannou.com/index.rdf"},
    {"id": "asiareaction", "name": "（　｀ハ´）中国の反応ブログ", "url": "http://asiareaction.blog.fc2.com/?xml"},
    {"id": "dimikai", "name": "海外の反応 ディミヌート", "url": "https://www.dimikai.com/?xml"},
    {"id": "all_nationz", "name": "海外の万国反応記＠海外の反応", "url": "http://www.all-nationz.com/index.rdf"},
    {"id": "galapagosjapan", "name": "ガラパゴスジャパン - 海外の反応", "url": "http://galapagosjapan.blog.fc2.com/?xml"},
    {"id": "tchal", "name": "チャルバンを翻訳してみた【海外の反応】", "url": "http://tchal.net/index.rdf"},
    {"id": "japohan", "name": "じゃぽにか反応帳", "url": "http://www.japohan.net/feed"},
    {"id": "foreignnews", "name": "海外の反応 | 海外報道翻訳所", "url": "http://foreignnews.biz/archives/cat_382414.xml"},
    {"id": "tamenal", "name": "【海外の反応】タメナル", "url": "http://tamenal.com/feed"},
    {"id": "yurukuyaru", "name": "ユルクヤル、外国人から見た世界", "url": "http://yurukuyaru.com/index.rdf"},
    {"id": "chinareaction", "name": "中国四千年の反応！ 海外の反応ブログ", "url": "http://chinareaction.com/?xml"},
    {"id": "kaigainohannou", "name": "海外の反応 | 翻訳部", "url": "http://kaigainohannou.info/feed/"},
    {"id": "karapaia", "name": "カラパイア - 海外の反応", "url": "http://karapaia.com/xml/kaigai.xml"},
    {"id": "kaigaino", "name": "世界の反応", "url": "https://kaigaino.net/feed"},
    {"id": "no_one_no", "name": "QQQ(海外の反応)", "url": "http://no-one-no.net/index.rdf"},
    {"id": "kaigai_otaku_1", "name": "韓国の反応 | 海外のリアクション", "url": "http://kaigai-otaku.jp/category/korea/feed"},
    {"id": "kaigainoomaera", "name": "海外のお前ら　海外の反応", "url": "https://kaigainoomaera.com/?xml"},
    {"id": "kaigaisoku", "name": "翻訳ちゃんねる | 海外の反応まとめブログ", "url": "http://blog.livedoor.jp/kaigaisoku/index.rdf"},
    {"id": "thainokoe", "name": "タイの反応 タイコエ", "url": "https://thainokoe.com/feed/"},
    {"id": "blogspot_1", "name": "かいこれ！ 海外の反応 コレクション", "url": "https://kaikore.blogspot.com/feeds/posts/default?alt=rss"},
    {"id": "polandball", "name": "ポーランドボール 翻訳", "url": "http://polandball.blog.fc2.com/?xml"},
    {"id": "overseasresponse", "name": "海外の反応ジャーナル", "url": "https://overseasresponse.com/feed"},
    {"id": "zzcj", "name": "海外反応！　I LOVE JAPAN　", "url": "http://blog.livedoor.jp/zzcj/index.rdf"},
    {"id": "lakatan", "name": "ラカタン", "url": "http://lakatan.net/feed"},
    {"id": "labaq", "name": "らばQ - 海外の反応", "url": "http://labaq.com/archives/cat_50037985.xml"},
    {"id": "stumbleon", "name": "こんなニュースにでくわした", "url": "http://stumbleon.blog.fc2.com/?xml"},
    {"id": "baychannel", "name": "今日も荷物が届かない。@海外の反応", "url": "http://baychannel.blog.fc2.com/?xml"},
    {"id": "yaku_plus", "name": "海外の反応  |  ヤクプラス", "url": "http://yaku-plus.com/archives/category/%E6%B5%B7%E5%A4%96%E3%81%AE%E5%8F%8D%E5%BF%9C/feed"},
    {"id": "kattobi_japan", "name": "【動画翻訳】かっとびジャパン - 海外の反応", "url": "http://www.kattobi-japan.com/index.rdf"},
    {"id": "kaigai_nippon", "name": "海外の反応 ニッポンの翻訳", "url": "http://kaigai-nippon.com/?feed=rss2"},
    {"id": "amped_up", "name": "【海外の反応】アンプタップ", "url": "http://amped-up.net/feed"},
    {"id": "matomehannou", "name": "お隣通信　", "url": "http://matomehannou.com/?feed=rss2"},
    {"id": "kashikou", "name": "「日中文化交流」と書いてオタ活動と読む", "url": "http://blog.livedoor.jp/kashikou/index.rdf"},
    {"id": "moriforest", "name": "翻訳の森　海外の反応", "url": "http://moriforest.com/feed"},
    {"id": "kaigaireactionsite", "name": "世界反応web", "url": "http://kaigaireactionsite.net/feed"},
    {"id": "twfunnymovie", "name": "新世代台湾人の反応", "url": "https://twfunnymovie.com/?xml"},
    {"id": "mykeibamemory", "name": "海外の小反応", "url": "http://mykeibamemory.blog.fc2.com/?xml"},
    {"id": "chinesestyle", "name": "中国人の戯言～大中華思想～", "url": "http://chinesestyle.seesaa.net/index.rdf"},
    {"id": "closetotokyo", "name": "フォゲラバリ（海外の反応）", "url": "http://closetotokyo.blog.fc2.com/?xml"},
    {"id": "sekaiminzoku", "name": "世界の憂鬱 海外・韓国の反応", "url": "http://blog.livedoor.jp/sekaiminzoku/index.rdf"},
    {"id": "iwado", "name": "イワド新報", "url": "https://iwado.work/feed"},
    {"id": "blogspot_2", "name": "コーヒーと翻訳", "url": "https://coffeehonyaku.blogspot.com/feeds/posts/default?alt=rss&amp;orderby=published"},
    {"id": "kankokunohannou", "name": "かんこく！　韓国の反応翻訳ブログ", "url": "https://kankokunohannou.org/?xml"},
    {"id": "kaigaiwelcome", "name": "海外さんいらっしゃい　海外の反応", "url": "https://kaigaiwelcome.com/?xml"},
    {"id": "sarasoku", "name": "世界の反応　さら速", "url": "http://sarasoku.net/feed/"},
    {"id": "k_han", "name": "ボイスオブコリア韓国の反応翻訳まとめ", "url": "https://k-han.com/?xml"},
    {"id": "kaigaino_syogeki", "name": "海外の笑劇", "url": "http://kaigaino-syogeki.blog.jp/index.rdf"},
    {"id": "kaigaihannnoumatome", "name": "YouTube海外の反応まとめ", "url": "http://kaigaihannnoumatome.ldblog.jp/index.rdf"},
    {"id": "pankori", "name": "パンコリ", "url": "https://pankori.net/feed/"},
    {"id": "muryou_tanoshimu", "name": "韓国の反応  |  海外トークログ", "url": "https://muryou-tanoshimu.com/category/kankoku/feed/"},
    {"id": "koreaction", "name": "KoreAction", "url": "https://koreaction.net/feed/"},
    {"id": "grandfleet", "name": "航空万能論GF", "url": "https://grandfleet.info/feed/"},
    {"id": "toku_log", "name": "海外の反応 | 海外トークログ", "url": "https://toku-log.com/feed/?cat=-5"},
    {"id": "kaigai_otaku_2", "name": "海外の反応 | 海外のリアクション", "url": "http://kaigai-otaku.jp/category/world/feed"},
    {"id": "japan_and_korea", "name": "日本と韓国は敵か？味方か？", "url": "http://blog.livedoor.jp/japan_and_korea/index.rdf"},
    {"id": "continent_news", "name": "大陸日報", "url": "http://continent-news.blog.jp/atom.xml"},
    {"id": "nikkokubu", "name": "日中国民連絡部", "url": "https://nikkokubu.com/?feed=rss2"},
    {"id": "betweenjpandkr", "name": "ニチカン!", "url": "https://betweenjpandkr.blog/feed"},
    {"id": "marutoo", "name": "まるっと翻訳", "url": "https://marutoo.com/feed"},
    {"id": "claudeworld", "name": "海外の反応 クロード", "url": "https://claudeworld.net/feed/"},
    {"id": "reddit_matome", "name": "Ask Reddit まとめ", "url": "https://reddit-matome.com/feed"},
    {"id": "sekai_zukan", "name": "世界反応図鑑", "url": "https://sekai-zukan.blog/feed/"},
    {"id": "red4_kaigaimatome", "name": "Red4 海外の反応まとめ", "url": "https://red4-kaigaimatome.com/feed/"},
    {"id": "sekahan0623", "name": "せかはん（世界の反応）", "url": "https://sekahan0623.com/feed"},
    {"id": "kanasoku", "name": "カナ速", "url": "http://kanasoku.info/index.rdf"},
    {"id": "darkm", "name": "はれぞう", "url": "http://blog.livedoor.jp/darkm/index.rdf"},
    {"id": "geinoukame", "name": "芸能かめはめ波", "url": "http://geinoukame.blog.fc2.com/?xml"},
    {"id": "gossip1", "name": "GOSSIP速報", "url": "http://gossip1.net/index.rdf"},
    {"id": "uwasainfo", "name": "芸能人の気になる噂", "url": "http://blog.livedoor.jp/uwasainfo/index.rdf"},
    {"id": "jyajyani", "name": "ジャにジャに速報 - ジャニーズまとめ", "url": "http://jyajyani.doorblog.jp/index.rdf"},
    {"id": "geininsokuhou_1", "name": "お笑いまとめ　芸人速報", "url": "http://geininsokuhou.blog.jp/index.rdf"},
    {"id": "sky_wing2010_geinou", "name": "芸能人ニュース速報", "url": "http://blog.livedoor.jp/sky_wing2010-geinou/index.rdf"},
    {"id": "koredakedeok", "name": "芸能ネタはこれだけでおｋ", "url": "http://koredakedeok.blog.jp/index.rdf"},
    {"id": "kininaru_geinou_m", "name": "気になる芸能まとめ", "url": "http://kininaru-geinou-m.blog.jp/index.rdf"},
    {"id": "dameposokuho", "name": "ダメポ速報", "url": "http://dameposokuho.com/index.rdf"},
    {"id": "mashlife", "name": "mashlife通信", "url": "http://mashlife.doorblog.jp/index.rdf"},
    {"id": "geinouplus", "name": "芸能NEWS＋｜エンタメ情報まとめ！", "url": "http://geinouplus.com/index.rdf"},
    {"id": "knowledgesokuhou", "name": "ナレッジ速報", "url": "http://knowledgesokuhou.com/index.rdf"},
    {"id": "movient", "name": "映画.net", "url": "http://www.movient.net/index.rdf"},
    {"id": "a_la_carte", "name": "ちまたのアラカルト", "url": "http://a-la-carte.blog.jp/index.rdf"},
    {"id": "showbizjapan", "name": "SHOWBIZ JAPAN", "url": "http://showbizjapan.blog.fc2.com/?xml"},
    {"id": "mhsoken", "name": "ミーハー総研（ミーハー総合研究所）", "url": "http://mhsoken.blog.jp/index.rdf"},
    {"id": "news_bomb", "name": "News Bomb｜ニュースまとめサイト", "url": "http://news-bomb.com/feed"},
    {"id": "oto_ch", "name": "音ちゃんねる", "url": "https://oto-ch.net/feed"},
    {"id": "geinoutopics_plus", "name": "芸能トピ＋＋", "url": "http://geinoutopics-plus.blog.jp/index.rdf"},
    {"id": "cinesoku", "name": "シネマ速報", "url": "http://cinesoku.net/feed"},
    {"id": "loudrockers", "name": "ラウドロッカーズ", "url": "http://loudrockers.com/feed"},
    {"id": "bokumato", "name": "僕のまとめ", "url": "https://bokumato.site/feed/"},
    {"id": "youtube_sokuhou", "name": "YouTube速報", "url": "http://blog.livedoor.jp/youtube_sokuhou/index.rdf"},
    {"id": "medakamatome", "name": "まとめだかニュース速報＠", "url": "http://medakamatome.tokyo/index.rdf"},
    {"id": "geininsokuhou_2", "name": "お笑いまとめ　芸人速報", "url": "https://geininsokuhou.com/feed"},
    {"id": "geinou_7days", "name": "芸能7days", "url": "http://geinou-7days.net/feed"},
    {"id": "sh_arekore", "name": "昭和平成懐かしラウンジ", "url": "https://sh-arekore.com/index.rdf"},
    {"id": "otonoke_ottodokechannel", "name": "おとのけ おとっどけ.ch", "url": "https://otonoke-ottodokechannel.blog.jp/index.rdf"},
    {"id": "nogiviola", "name": "NOGIVIOLA＠乃木坂46まとめ", "url": "http://nogiviola.livedoor.biz/index.rdf"},
    {"id": "chikakb", "name": "地下帝国-AKB48まとめ", "url": "http://chikakb.ldblog.jp/index.rdf"},
    {"id": "keyakizaka46plus", "name": "欅坂46news+", "url": "http://keyakizaka46plus.com/feed"},
    {"id": "keyakizaka1", "name": "欅坂46速報", "url": "http://keyakizaka1.blog.jp/index.rdf"},
    {"id": "akb48mt", "name": "AKB48情報まとめたった", "url": "http://www.akb48mt.com/index.rdf"},
    {"id": "ske48matoeme", "name": "SKE48まとめはエメラルド（まとえめ）", "url": "http://www.ske48matoeme.com/index.rdf"},
    {"id": "nmb48_mtm", "name": "NMB48まとめスピリッツ", "url": "http://nmb48-mtm.com/index.rdf"},
    {"id": "hiraganakeyaki", "name": "日向坂46まとめ速報", "url": "http://hiraganakeyaki.blog.jp/index.rdf"},
    {"id": "nogizaka46link", "name": "乃木坂46まとめ 乃木りんく", "url": "http://nogizaka46link.blog.jp/index.rdf"},
    {"id": "nogitweet", "name": "乃木坂46まとめんばー", "url": "http://nogitweet.com/feed"},
    {"id": "akb48rompen", "name": "ROMれ！ペンギン(AKB48まとめ)", "url": "http://www.akb48rompen.com/index.rdf"},
    {"id": "hktmatomemon", "name": "HKTまとめもん【HKT48のまとめ】", "url": "http://blog.livedoor.jp/hktmatomemon/index.rdf"},
    {"id": "akb48taimuzu", "name": "AKB48タイムズ（AKB48まとめ）", "url": "http://akb48taimuzu.livedoor.biz/index.rdf"},
    {"id": "nogizaka46matomenoma", "name": "乃木坂46まとめの「ま」", "url": "http://nogizaka46matomenoma.blog.jp/index.rdf"},
    {"id": "hinatasoku", "name": "日向速報 -日向坂46まとめ-", "url": "http://hinatasoku.blog.jp/index.rdf"},
    {"id": "nmb48matome", "name": "NMB48まとめといたで", "url": "http://nmb48matome.net/feed"},
    {"id": "keyakizaka46matomerabo", "name": "欅坂46まとめラボ", "url": "http://www.keyakizaka46matomerabo.com/index.rdf"},
    {"id": "toriizaka46", "name": "欅坂46まとめきんぐだむ", "url": "http://toriizaka46.jp/feed"},
    {"id": "akb48rhyh", "name": "AKB48地下速報", "url": "http://blog.livedoor.jp/akb48rhyh/index.rdf"},
    {"id": "xxxblog", "name": "ももクロ侍", "url": "http://momoclozamurai.xxxblog.jp/index.rdf"},
    {"id": "hinatazaka46menome", "name": "日向坂46まとめタイムズ", "url": "http://hinatazaka46menome.ldblog.jp/index.rdf"},
    {"id": "sakamichi48", "name": "乃木通☆世界最速！乃木坂46欅坂46日向坂46速報まとめ", "url": "http://sakamichi48.blog.jp/index.rdf"},
    {"id": "hellopronews", "name": "ハロプロニュース", "url": "http://hellopronews.blog.jp/index.rdf"},
    {"id": "keyakizaka46ch", "name": "櫻坂46まとめちゃんねる", "url": "https://keyakizaka46ch.jp/feed"},
    {"id": "hinatazaka46ch", "name": "日向坂46まとめちゃんねる", "url": "http://hinatazaka46ch.jp/feed"},
    {"id": "officeblog", "name": "乃木坂46まとめたいよ", "url": "http://nogizaka46.officeblog.jp/index.rdf"},
    {"id": "akbfriend", "name": "AKBフレンド", "url": "http://akbfriend.blog.jp/index.rdf"},
    {"id": "nogizaka_46bunno1", "name": "乃木坂46まとめ 1/46", "url": "http://nogizaka-46bunno1.blog.jp/index.rdf"},
    {"id": "keyakihinatamatome", "name": "欅日向まとめコム", "url": "https://keyakihinatamatome.com/feed"},
    {"id": "akbmatome18300", "name": "18300ｍ～AKB48まとめブログ～", "url": "http://akbmatome18300.ldblog.jp/index.rdf"},
    {"id": "sakamichijyoho46", "name": "坂道G情報通", "url": "http://sakamichijyoho46.blog.jp/index.rdf"},
    {"id": "c_ute", "name": "℃-ute派なんday", "url": "http://c-ute.doorblog.jp/index.rdf"},
    {"id": "keyakizaka46matomemory", "name": "欅坂46まとめもり～", "url": "http://keyakizaka46matomemory.net/index.rdf"},
    {"id": "46matome", "name": "日向坂46まとめもり～", "url": "http://46matome.net/index.rdf"},
    {"id": "nijiproject", "name": "NiziUまとめキングダム", "url": "http://nijiproject.livedoor.biz/index.rdf"},
    {"id": "nogiradi", "name": "乃木坂46まとめ ラジオの時間", "url": "http://nogiradi.com/index.rdf"},
    {"id": "ske48matome", "name": "SKE48まとめろぐっ！", "url": "http://ske48matome.net/index.rdf"},
    {"id": "akb48team8", "name": "チーム8まとめりか(AKB48Team8まとめ)", "url": "http://akb48team8.net/feed/"},
    {"id": "stu4846", "name": "STU48まとめニュース（瀬戸内48）", "url": "http://stu4846.livedoor.biz/index.rdf"},
    {"id": "46room", "name": "乃木坂46まとめもり～", "url": "https://46room.blog.jp/index.rdf"},
    {"id": "ske48matomemo", "name": "SKE48まとめもらんだむ", "url": "http://ske48matomemo.doorblog.jp/index.rdf"},
    {"id": "morning77", "name": "ハロプロ×LIFE", "url": "http://blog.livedoor.jp/morning77/index.rdf"},
    {"id": "giogio48", "name": "GIOGIOの奇妙な速報‐AKB48・チーム8まとめたの", "url": "http://www.giogio48.com/index.rdf"},
    {"id": "nmbfan", "name": "NMB時々AKBとか", "url": "http://nmbfan.seesaa.net/index20.rdf"},
    {"id": "haruka1027", "name": "ハロプロってながいぜぃ・・・Blog", "url": "http://haruka1027.blog.jp/index.rdf"},
    {"id": "helloprot", "name": "ハロプロまとめトーク", "url": "http://helloprot.ldblog.jp/index.rdf"},
    {"id": "setouchi48g", "name": "船上の瀬戸内48Gまとめブログ☆STU48", "url": "http://setouchi48g.ldblog.jp/index.rdf"},
    {"id": "paruru", "name": "ぱるる情報局", "url": "http://paruru.2chblog.jp/index.rdf"},
    {"id": "nogizaka46_matome", "name": "超・乃木坂まとめ誕生！ - 乃木坂46まとめ", "url": "https://nogizaka46-matome.jp/index.rdf"},
    {"id": "hello_johokyoku", "name": "ハロプロちゃん情報局", "url": "https://hello-johokyoku.com/index.rdf"},
    {"id": "hellopronotane", "name": "ハロプロの種", "url": "https://hellopronotane.doorblog.jp/index.rdf"},
    {"id": "gootore", "name": "僕青ちゃんねる", "url": "https://gootore.xyz/?feed=rss2"},
    {"id": "hpupdate", "name": "ハロアップデート", "url": "https://hpupdate.info/?feed=rss2"},
    {"id": "nogizakalife", "name": "乃木坂LIFE -坂道・48高速まとめ-", "url": "https://nogizakalife.tokyo/?feed=rss2"},
    {"id": "halospo", "name": "ハロスポ＠ハロプロまとめ", "url": "https://halospo.com/feed/"},
    {"id": "visual_matome", "name": "V系まとめ速報", "url": "http://visual-matome.com/index.rdf"},
    {"id": "blogo", "name": "大物Youtubeｒ速報", "url": "http://oomonoyoutubersokuhou.blogo.jp/index.rdf"},
    {"id": "babymetalmatome", "name": "BABYmatoMETAL", "url": "http://babymetalmatome.com/index.rdf"},
    {"id": "vtuber_matome", "name": "Vtuberまとめてみました", "url": "http://vtuber-matome.com/feed"},
    {"id": "babymetal_darake", "name": "べビメタだらけの・・・", "url": "https://www.babymetal-darake.com/feed"},
    {"id": "babymetalize", "name": "BABYMETALIZE", "url": "http://babymetalize.com/feed"},
    {"id": "revuestarlightre", "name": "日刊バーチャル", "url": "http://revuestarlightre.com/index.rdf"},
    {"id": "bbmt46", "name": "BABYMETALまとめもりー", "url": "http://blog.livedoor.jp/bbmt46/index.rdf"},
    {"id": "moti_soku", "name": "気になるVtuber速報", "url": "https://moti-soku.com/feed/"},
    {"id": "babymetal_matome", "name": "BABYMETALまとめニュース", "url": "http://babymetal-matome.blog.jp/index.rdf"},
    {"id": "babymetaltimes", "name": "BABYMETAL TIMES", "url": "http://www.babymetaltimes.com/index.rdf"},
    {"id": "holosoku", "name": "ホロ速", "url": "https://holosoku.com/feed/"},
    {"id": "bitubu", "name": "ぶいちゅー部！@ホロライブまとめ", "url": "https://bitubu.blog.jp/index.rdf"},
    {"id": "vtubernews", "name": "VTuberNews", "url": "http://vtubernews.jp/index.rdf"},
    {"id": "vtubertete", "name": "てぇてぇかんそく：Vtuber にじさんじ ホロライブまとめ", "url": "https://vtubertete.com/feed/"},
    {"id": "vtubersokuhou", "name": "ぶいちゅーばー速報", "url": "http://vtubersokuhou.com/feed"},
    {"id": "vrtuber_news", "name": "Vtuber速報@バーチャルYouTuberまとめ", "url": "http://vrtuber-news.com/index.rdf"},
    {"id": "vtuber_matomeruyon", "name": "Vtuberまとめるよ～ん", "url": "http://vtuber-matomeruyon.blog.jp/index.rdf"},
    {"id": "mangasokuhou", "name": "にじホロVtuberまとめ速報", "url": "https://www.mangasokuhou.com/?feed=rss2"},
    {"id": "holoch", "name": "ホロちゃんねる", "url": "http://blog.livedoor.jp/holoch/index.rdf"},
    {"id": "moon0502", "name": "VTuberまとめ情報", "url": "http://moon0502.blog.jp/index.rdf"},
    {"id": "2ch_life", "name": "隠し味は2chソース(^ω^)", "url": "https://2ch-life.com/?xml"},
    {"id": "news4vip", "name": "【2ch】ニュー速クオリティ", "url": "http://news4vip.livedoor.biz/index.rdf"},
    {"id": "matometanews", "name": "まとめたニュース", "url": "http://matometanews.com/index.rdf"},
    {"id": "himasoku", "name": "暇人＼(^o^)／速報", "url": "http://himasoku.com/index.rdf"},
    {"id": "ryusoku", "name": "流速VIP", "url": "http://ryusoku.com/index.rdf"},
    {"id": "news23vip", "name": "VIPPERな俺", "url": "http://blog.livedoor.jp/news23vip/index.rdf"},
    {"id": "burusoku_vip", "name": "ぶる速-VIP", "url": "http://burusoku-vip.com/index.rdf"},
    {"id": "workingnews", "name": "働くモノニュース : 人生VIP職人ブログwww", "url": "http://workingnews.blog117.fc2.com/?xml"},
    {"id": "chaos2ch", "name": "カオスちゃんねる", "url": "http://chaos2ch.com/index.rdf"},
    {"id": "waranote", "name": "ワラノート", "url": "http://waranote.livedoor.biz/index.rdf"},
    {"id": "joujakuvip2ch", "name": "情弱VIP2ちゃんねる", "url": "http://blog.livedoor.jp/joujakuvip2ch/index.rdf"},
    {"id": "robosoku", "name": "ろぼ速VIP", "url": "http://blog.livedoor.jp/robosoku/index.rdf"},
    {"id": "2chcopipe", "name": "2chコピペ保存道場", "url": "http://2chcopipe.com/index.rdf"},
    {"id": "akb48matomemory", "name": "NEWSまとめもりー｜2chまとめブログ", "url": "http://www.akb48matomemory.com/index.rdf"},
    {"id": "world_fusigi", "name": "不思議.net", "url": "http://world-fusigi.net/index.rdf"},
    {"id": "vippers", "name": "VIPPER速報", "url": "http://vippers.jp/index.rdf"},
    {"id": "rabitsokuhou", "name": "ラビット速報", "url": "http://rabitsokuhou.2chblog.jp/index.rdf"},
    {"id": "inazumanews2", "name": "稲妻速報", "url": "http://inazumanews2.com/index.rdf"},
    {"id": "aramame", "name": "あらまめ2ch", "url": "http://aramame.net/feed"},
    {"id": "takenokosokuhou", "name": "気になるたけのこ速報VIP", "url": "http://takenokosokuhou.com/index.rdf"},
    {"id": "2ch_matomenews", "name": "まにゅそく 2chまとめニュース速報VIP", "url": "http://2ch-matomenews.com/feed"},
    {"id": "1000mg", "name": "1000mg", "url": "http://1000mg.jp/feed"},
    {"id": "negisoku", "name": "ネギ速", "url": "http://www.negisoku.com/index.rdf"},
    {"id": "2logch", "name": "２ろぐちゃんねる", "url": "https://2logch.com/feed"},
    {"id": "netamesi", "name": "ネタめし.com", "url": "http://www.netamesi.com/index.rdf"},
    {"id": "ronsoku", "name": "ロン速", "url": "http://ronsoku.com/index.rdf"},
    {"id": "matometre", "name": "まとめーとる", "url": "http://matometre.net/index.rdf"},
    {"id": "majimanjisokuhou", "name": "マジ卍速報", "url": "http://majimanjisokuhou.com/index.rdf"},
    {"id": "mudainodocument", "name": "無題のドキュメント", "url": "http://www.mudainodocument.com/index.rdf"},
    {"id": "fesoku", "name": "ふぇー速", "url": "http://fesoku.net/index.rdf"},
    {"id": "okutta", "name": "億ったー", "url": "http://www.okutta.net/index.rdf"},
    {"id": "nyaasokuvip", "name": "にゃあ速報VIP", "url": "http://nyaasokuvip.net/feed"},
    {"id": "shitsumon_aru", "name": "質問ある？まとめ速報", "url": "http://shitsumon-aru.net/index.rdf"},
    {"id": "kyousoku", "name": "今日速2ch", "url": "http://kyousoku.net/index.rdf"},
    {"id": "maji_w", "name": "マジワロ速報", "url": "http://maji-w.blog.jp/index.rdf"},
    {"id": "sonicch", "name": "ソニック速報", "url": "http://sonicch.com/index.rdf"},
    {"id": "girlsvip_matome", "name": "ガールズVIPまとめ", "url": "http://girlsvip-matome.com/index.rdf"},
    {"id": "magical_news", "name": "まじかる☆にゅーす", "url": "http://magical-news.blog.jp/index.rdf"},
    {"id": "parusoku", "name": "ぱる速報", "url": "http://parusoku.com/index.rdf"},
    {"id": "oumaga_times", "name": "おうまがタイムズ", "url": "http://www.oumaga-times.com/index.rdf"},
    {"id": "ginnga", "name": "銀河系まとめブログ", "url": "http://ginnga.blog.jp/index.rdf"},
    {"id": "dechisoku", "name": "でっちでち速報", "url": "http://dechisoku.com/index.rdf"},
    {"id": "ikeike2ch", "name": "イケイケ速報", "url": "http://ikeike2ch.jp/index.rdf"},
    {"id": "paripinews", "name": "パリピにゅーす", "url": "http://paripinews.net/index.rdf"},
    {"id": "moe_vip", "name": "燃えよVIPPER", "url": "http://www.moe-vip.com/index.rdf"},
    {"id": "sokuho_1", "name": "ぱわわ速報", "url": "http://pawawa.sokuho.org/index20.rdf"},
    {"id": "beasoku", "name": "ベア速", "url": "http://beasoku.com/index20.rdf"},
    {"id": "mildch", "name": "マイルドちゃんねる", "url": "http://mildch.com/index.rdf"},
    {"id": "sasuga801_koukokugyoukai", "name": "アドちゃんねる", "url": "http://blog.livedoor.jp/sasuga801-koukokugyoukai/index.rdf"},
    {"id": "bigbangchannel", "name": "ビッグバンちゃんねる", "url": "http://bigbangchannel.net/index.rdf"},
    {"id": "himayomi", "name": "暇読み", "url": "https://himayomi.com/feed"},
    {"id": "xdomain", "name": "ヘビィなD通信", "url": "http://asg1501.wp.xdomain.jp/feed"},
    {"id": "kiteretubaka", "name": "アホの気まぐれ速報", "url": "https://kiteretubaka.com/feed/"},
    {"id": "twihako", "name": "ツイハコ", "url": "https://twihako.com/feed"},
    {"id": "sfgidf", "name": "ピンキリ速報 - レスバもまとめる5chブログ -", "url": "http://sfgidf.blog.jp/index.rdf"},
    {"id": "uhawwwsoku", "name": "うはｗｗｗ速｜まとめブログ", "url": "http://uhawwwsoku.net/index.rdf"},
    {"id": "hnbnfun", "name": "ほのぼのしない動物速報 (Ф∀Ф)", "url": "http://hnbnfun.blog.jp/index.rdf"},
    {"id": "shikaku105", "name": "2chNEWSまとめ", "url": "http://shikaku105.blog.jp/index.rdf"},
    {"id": "brow2ing", "name": "ブラブラブラウジング", "url": "http://brow2ing.com/index.rdf"},
    {"id": "love_history", "name": "群雄割拠", "url": "http://www.love-history.jp/index.rdf"},
    {"id": "2monkeys", "name": "2chまとめ・読み物・長編・名作/2MONKEYS.JP", "url": "http://www.2monkeys.jp/index.rdf"},
    {"id": "everydayissunday", "name": "ずっと日曜日のターン", "url": "http://everydayissunday.livedoor.blog/index.rdf"},
    {"id": "studynews", "name": "Study速報", "url": "https://studynews.jp/feed/"},
    {"id": "matomeru1", "name": "まとめる", "url": "http://matomeru1.livedoor.blog/index.rdf"},
    {"id": "jiwachan", "name": "じわるチャンネル-雑談まとめブログ-", "url": "http://jiwachan.net/index.rdf"},
    {"id": "twintailsokuhou", "name": "ついんてーる速報", "url": "http://twintailsokuhou.blog.jp/index.rdf"},
    {"id": "gazoua2meru", "name": "画像あつめーる", "url": "http://gazoua2meru.livedoor.blog/index.rdf"},
    {"id": "yuitannel", "name": "ゆいたんねる", "url": "https://yuitannel.blog.jp/index.rdf"},
    {"id": "shitsumonaru", "name": "為になる？質問ある？まとめ", "url": "http://shitsumonaru.com/feed"},
    {"id": "neochisokuhou", "name": "寝落ち速報", "url": "https://neochisokuhou.net/feed/"},
    {"id": "gironsokuhoo", "name": "議論速報", "url": "https://gironsokuhoo.livedoor.blog/index.rdf"},
    {"id": "channelz", "name": "ちゃんねるZ", "url": "http://channelz.blog.fc2.com/?xml"},
    {"id": "lamsect", "name": "ジュピ速", "url": "http://lamsect.blog112.fc2.com/?xml"},
    {"id": "kinisoku", "name": "キニ速", "url": "http://blog.livedoor.jp/kinisoku/index.rdf"},
    {"id": "shikaku2ch", "name": "資格ちゃんねる", "url": "http://shikaku2ch.doorblog.jp/index.rdf"},
    {"id": "blomaga_1", "name": "ニコニコ２ちゃんねる", "url": "http://vip.blomaga.jp/index.rdf"},
    {"id": "kiru2ch", "name": "２ちゃんを斬る！", "url": "http://kiru2ch.com/index.rdf"},
    {"id": "blomaga_2", "name": "かれっじライフハッキング", "url": "http://college2ch.blomaga.jp/index.rdf"},
    {"id": "matome_tarou", "name": "まとめ太郎！", "url": "http://matome-tarou.ldblog.jp/index.rdf"},
    {"id": "bmaysu", "name": "ってなんじぇですかー", "url": "http://blog.livedoor.jp/bmaysu/index.rdf"},
    {"id": "totalmatomedia", "name": "まとめでぃあ", "url": "http://totalmatomedia.blog.fc2.com/?xml"},
    {"id": "apasoku", "name": "あぱれる速報", "url": "http://apasoku.doorblog.jp/index.rdf"},
    {"id": "bb", "name": "なんJ 野球をまとめてみたよ", "url": "http://bb.doorblog.jp/index.rdf"},
    {"id": "niccorin", "name": "ニッコリン", "url": "http://niccorin.com/index.rdf"},
    {"id": "nanj_short", "name": "みじかめっ！なんJ", "url": "http://blog.livedoor.jp/nanj_short/index.rdf"},
    {"id": "pokemon_goh", "name": "NEWSぽけまとめーる", "url": "http://pokemon-goh.doorblog.jp/index.rdf"},
    {"id": "squallchannel", "name": "スコールちゃんねる｜２ちゃんまとめブログ", "url": "http://squallchannel.doorblog.jp/index.rdf"},
    {"id": "inutomo11", "name": "なんJクエスト", "url": "http://inutomo11.com/index.rdf"},
    {"id": "yabatanichannel", "name": "やばたにチャンネル", "url": "http://yabatanichannel.net/index.rdf"},
    {"id": "heekogirl", "name": "2ちゃんねるまとめ 名前はまだない", "url": "http://heekogirl.blog.fc2.com/?xml"},
    {"id": "nanjmgun", "name": "なんＪマシンガン", "url": "http://nanjmgun.livedoor.blog/index.rdf"},
    {"id": "nanj_world", "name": "なんJワールド", "url": "http://nanj-world.blog.jp/index.rdf"},
    {"id": "nanjwalker", "name": "なんJウォーカー！", "url": "http://nanjwalker.blog.jp/index.rdf"},
    {"id": "kankeinai", "name": "なんJやきう関係ない部@おんJ", "url": "http://kankeinai.blog.jp/index.rdf"},
    {"id": "kokoyakyumatomesokuho", "name": "なんJ　高校野球まとめ速報", "url": "http://kokoyakyumatomesokuho.blog.jp/index.rdf"},
    {"id": "nanj_push", "name": "なんJ PUSH!!", "url": "https://nanj-push.blog.jp/index.rdf"},
    {"id": "nanj_dream", "name": "なんJ Dream", "url": "http://blog.livedoor.jp/nanj_dream/index.rdf"},
    {"id": "g_ogasawara", "name": "NaNじぇい", "url": "http://blog.livedoor.jp/g_ogasawara/index.rdf"},
    {"id": "mylife", "name": "Jのログ＠おんJまとめブログ", "url": "http://mylife.2chblog.jp/index.rdf"},
    {"id": "konoyubitomare", "name": "コノユビ", "url": "http://konoyubitomare.jp/index.rdf"},
    {"id": "almighty_nanj", "name": "ごちゃまぜオールマイティ", "url": "http://almighty-nanj.ldblog.jp/index.rdf"},
    {"id": "amatsubushi", "name": "あまつぶし", "url": "http://blog.livedoor.jp/amatsubushi/index.rdf"},
    {"id": "nanj_hero", "name": "なんJ HERO", "url": "http://nanj-hero.com/index.rdf"},
    {"id": "matmebae", "name": "まとめ映ぇぇ", "url": "http://matmebae.net/index20.rdf"},
    {"id": "nanjcollection", "name": "なんJコレクション", "url": "http://nanjcollection.blog.jp/index.rdf"},
    {"id": "tiktok_p", "name": "まとめＴｏｋ", "url": "http://tiktok-p.blog.jp/index.rdf"},
    {"id": "nandemo_uketori", "name": "なんでも受信遅報@なんJ・おんJまとめ", "url": "http://www.nandemo-uketori.com/index.rdf"},
    {"id": "question56", "name": "Question. -クエッション-", "url": "http://question56.blog.jp/index.rdf"},
    {"id": "sapparipiman", "name": "さっぱりピーマン", "url": "http://sapparipiman.com/index.rdf"},
    {"id": "dragonballmatomech", "name": "ドラゴン速報", "url": "http://dragonballmatomech.blog.jp/index.rdf"},
    {"id": "tapittalk", "name": "くろす速報", "url": "https://tapittalk.com/feed/"},
    {"id": "ganbarinote", "name": "がんばりノート", "url": "http://ganbarinote.net/index.rdf"},
    {"id": "zatuzatu", "name": "雑なまとめ", "url": "https://zatuzatu.com/feed"},
    {"id": "kima_mato", "name": "きままと", "url": "http://kima-mato.blog.jp/index.rdf"},
    {"id": "maruhorror", "name": "まるたろうの怖い心霊ブログ", "url": "http://www.maruhorror.com/index.rdf"},
    {"id": "a711", "name": "CRただいま速報", "url": "http://a711.work/index.rdf"},
    {"id": "waimatome", "name": "ワイ、まとめ速報", "url": "http://waimatome.blog.jp/index.rdf"},
    {"id": "2ch", "name": "2ちゃんcc", "url": "http://2ch.cc/index.rdf"},
    {"id": "netizen_voice", "name": "ネラーボイス", "url": "http://netizen-voice.blog.jp/index.rdf"},
    {"id": "daunti", "name": "おフトンからまとめ", "url": "http://blog.livedoor.jp/daunti/index.rdf"},
    {"id": "vipperlog", "name": "VIPPERlog", "url": "http://vipperlog.com/index.rdf"},
    {"id": "btnk48", "name": "シュヴァイネフライシュまとめ@おんＪ", "url": "https://btnk48.blog.jp/index.rdf"},
    {"id": "toshi114514", "name": "野獣先輩が選ぶ！？神ＳＳ&amp;日本応援まとめ：なんJおんJ", "url": "http://blog.livedoor.jp/toshi114514/index.rdf"},
    {"id": "trombonechannel", "name": "ボントロちゃんねる", "url": "https://trombonechannel.net/feed"},
    {"id": "shirokurosokuhou", "name": "シロクロ速報", "url": "https://shirokurosokuhou.blog.jp/index.rdf"},
    {"id": "senzaiyoron", "name": "潜在世論", "url": "https://senzaiyoron.blog.jp/index.rdf"},
    {"id": "kosodatech", "name": "子育てちゃんねる", "url": "http://kosodatech.blog133.fc2.com/?xml"},
    {"id": "kekkongo", "name": "結婚・恋愛ニュースぷらす", "url": "http://blog.livedoor.jp/kekkongo/index.rdf"},
    {"id": "mousouteki", "name": "続・妄想的日常", "url": "http://mousouteki.blog53.fc2.com/?xml"},
    {"id": "honwaka2ch", "name": "ほんわかMkⅡ", "url": "http://honwaka2ch.livedoor.biz/index.rdf"},
    {"id": "sk2ch", "name": "すかっとしていきませんか | sk2ch", "url": "http://sk2ch.net/feed"},
    {"id": "overjoyed", "name": "オーバージョイド！　　2chまとめサイト", "url": "http://overjoyed.info/feed"},
    {"id": "kisslog2", "name": "キスログ", "url": "http://kisslog2.com/index.rdf"},
    {"id": "love120331", "name": "はーとログ", "url": "http://blog.livedoor.jp/love120331/index.rdf"},
    {"id": "kidan_m", "name": "気団まとめ-噫無情-｜嫁・浮気・メシマズ", "url": "http://kidan-m.com/index.rdf"},
    {"id": "kidandan", "name": "気団談", "url": "http://blog.livedoor.jp/kidandan/index.rdf"},
    {"id": "hattatu_matome", "name": "凹凸ちゃんねる　発達障害・生きにくい人のまとめ", "url": "http://hattatu-matome.ldblog.jp/index.rdf"},
    {"id": "otoko_honne", "name": "オトコの本音｜生活2chまとめブログ", "url": "http://www.otoko-honne.com/index.rdf"},
    {"id": "nihonjinnanmin", "name": "日本人＿難民。～2ｃｈ読み物まとめ～", "url": "http://nihonjinnanmin.com/index.rdf"},
    {"id": "ouchinews", "name": "おうち速報", "url": "http://ouchinews.doorblog.jp/index.rdf"},
    {"id": "romeomail", "name": "ロミオメールまとめやめました(・∀・)", "url": "http://romeomail.doorblog.jp/index.rdf"},
    {"id": "heartlife_matome", "name": "はーとらいふ -出会い・子育て・生活系まとめ-", "url": "http://heartlife-matome.com/index.rdf"},
    {"id": "girlsreport", "name": "がーるずレポート - ガールズちゃんねるまとめブログ", "url": "http://girlsreport.net/index.rdf"},
    {"id": "danseisama", "name": "男性様｜気団・生活2chまとめブログ", "url": "https://danseisama.com/index.rdf"},
    {"id": "kidanlog", "name": "気団ログ", "url": "http://kidanlog.com/feed"},
    {"id": "kininatta2chmatome", "name": "気になった生活スレまとめ", "url": "http://kininatta2chmatome.doorblog.jp/index.rdf"},
    {"id": "recosoku", "name": "恋愛速報｜2chまとめサイト", "url": "http://www.recosoku.com/index.rdf"},
    {"id": "purinisdrink", "name": "プリンはのみものです。｜にちゃん生活まとめ", "url": "http://purinisdrink.net/index.rdf"},
    {"id": "sukattojapan", "name": "スカッとじゃぱん", "url": "http://sukattojapan.com/index.rdf"},
    {"id": "kuzu_soku", "name": "クズ速報‐ニート・金銭トラブル・人間関係‐【ダメ人間まとめ】", "url": "http://kuzu-soku.com/index.rdf"},
    {"id": "chitama", "name": "ちたま速報", "url": "http://chitama.blog.jp/index.rdf"},
    {"id": "whoistrueenemy", "name": "すまいる(^-^)ぶろぐ", "url": "http://blog.livedoor.jp/whoistrueenemy/index.rdf"},
    {"id": "kazokuchannel", "name": "かぞくちゃんねる", "url": "http://kazokuchannel.doorblog.jp/index.rdf"},
    {"id": "2_carat", "name": "2カラット", "url": "http://2-carat.net/index.rdf"},
    {"id": "chiwasoku_1", "name": "ちわわ速報｜修羅場・鬼女・２ちゃん生活まとめ", "url": "http://chiwasoku.com/index.rdf"},
    {"id": "minnano_syuraba", "name": "みんなの修羅場な体験談｜5ch浮気・不倫・修羅場・黒い過去まとめ", "url": "http://minnano-syuraba.ldblog.jp/index.rdf"},
    {"id": "romeodensetsu", "name": "ロミオ伝説｜にちゃんまとめ", "url": "http://romeodensetsu.com/index.rdf"},
    {"id": "shuraba_dendo", "name": "修羅場まとめの殿堂～離婚・復讐・不倫・浮気まとめ～", "url": "http://shuraba-dendo.com/index.rdf"},
    {"id": "xresolutionx", "name": "修羅場ライフ速報", "url": "http://xresolutionx.livedoor.blog/index.rdf"},
    {"id": "moteruwm", "name": "マッチングアプリ2ch・5chまとめブログ", "url": "http://moteruwm.blog.jp/index.rdf"},
    {"id": "ikinuki2ch", "name": "いきぬき2ちゃんねる", "url": "http://ikinuki2ch.blog.jp/index.rdf"},
    {"id": "bluebluesunset", "name": "ねこのあまやどり　", "url": "http://bluebluesunset.blog.fc2.com/?xml"},
    {"id": "kitimonogatari", "name": "世にもキチな物語", "url": "http://kitimonogatari.com/index.rdf"},
    {"id": "ikuzitter", "name": "いくじったー", "url": "http://blog.livedoor.jp/ikuzitter/index.rdf"},
    {"id": "shiawasewalk", "name": "幸せが歩いてきた！", "url": "http://shiawasewalk.doorblog.jp/index.rdf"},
    {"id": "xn__2ch_4k4bd7h9hsba8og2551jd75g", "name": "まとめ革命", "url": "http://xn--2ch-4k4bd7h9hsba8og2551jd75g.jp/?feed=rss2"},
    {"id": "paranomal", "name": "修羅の華-家庭・生活まとめ", "url": "http://paranomal.blog.jp/index.rdf"},
    {"id": "financial_c", "name": "守銭奴日報", "url": "https://financial-c.net/feed"},
    {"id": "konkatsuchan", "name": "婚活ちゃんねる", "url": "http://konkatsuchan.doorblog.jp/index.rdf"},
    {"id": "kachimukayama", "name": "カチムカ山", "url": "http://kachimukayama.com/?feed=rss2"},
    {"id": "syurabarabanba", "name": "修羅場★らばんば", "url": "http://syurabarabanba.blog.jp/index.rdf"},
    {"id": "kaji2jimu", "name": "かじとじむ", "url": "https://kaji2jimu.work/index.rdf"},
    {"id": "gooddays_wedding", "name": "女と男の幸せがいっぱい", "url": "http://gooddays-wedding.com/feed/"},
    {"id": "xn__h9jtah1gvb5bc", "name": "にんちゃんねる", "url": "http://www.xn--h9jtah1gvb5bc.com/index.rdf"},
    {"id": "kekkon_souken", "name": "結婚総研", "url": "http://kekkon-souken.com/index.rdf"},
    {"id": "fuin_ki_dan", "name": "ふいん気団", "url": "http://fuin-ki-dan.blog.jp/index.rdf"},
    {"id": "shukichisokuhou", "name": "しゅーキチ速報", "url": "http://shukichisokuhou.blog/index.rdf"},
    {"id": "shurarara_monogatari", "name": "しゅららら物語", "url": "https://shurarara-monogatari.com/feed/"},
    {"id": "ikumamasokuhou", "name": "育ママ速報", "url": "http://ikumamasokuhou.com/index.rdf"},
    {"id": "himatub_livedoor", "name": "暇つぶしのまとめ", "url": "http://himatub-livedoor.blog.jp/index.rdf"},
    {"id": "garumato", "name": "ガールズちゃんねるまとめ「ガルまと」", "url": "https://www.garumato.com/feed"},
    {"id": "oishiimatome", "name": "おいしいまとめ", "url": "https://oishiimatome.com/?xml"},
    {"id": "love_matome", "name": "アノ人の恋愛系まとめ芸能情報局", "url": "https://love-matome.com/index.rdf"},
    {"id": "oniyomech", "name": "鬼嫁ちゃんねる", "url": "http://oniyomech.livedoor.biz/index.rdf"},
    {"id": "onihimechan", "name": "おにひめちゃんの監視部屋-鬼女、キチママ、修羅場、生活まとめ-", "url": "http://onihimechan.com/index.rdf"},
    {"id": "watarukiti", "name": "渡る世間はキチばかり - 鬼女・修羅場・キチママ・義家族まとめ-", "url": "http://watarukiti.com/index.rdf"},
    {"id": "uwakich", "name": "浮気ちゃんねる", "url": "http://uwakich.com/index.rdf"},
    {"id": "kitimama_matome", "name": "キチガイママまとめ保管庫", "url": "http://www.kitimama-matome.net/index.rdf"},
    {"id": "kijomatomelog", "name": "鬼女まとめログ｜生活2chまとめブログ", "url": "http://www.kijomatomelog.com/index.rdf"},
    {"id": "kijyomatome", "name": "鬼女まとめ速報 -修羅場・キチママ・生活まとめ-", "url": "http://kijyomatome.com/index.rdf"},
    {"id": "revenge", "name": "本当にやった復讐　まとめ", "url": "http://revenge.doorblog.jp/index.rdf"},
    {"id": "sutekinakijo", "name": "素敵な鬼女様", "url": "http://sutekinakijo.com/index.rdf"},
    {"id": "shuraba_matome", "name": "修羅場まとめ速報", "url": "http://shuraba-matome.com/index.rdf"},
    {"id": "oniyomediary", "name": "鬼嫁日記〜2ch生活まとめ〜", "url": "http://oniyomediary.com/index.rdf"},
    {"id": "okusama_kijyo", "name": "奥様は鬼女-DQN返しまとめ-", "url": "http://okusama-kijyo.com/index.rdf"},
    {"id": "kijosoku", "name": "鬼女速", "url": "http://kijosoku.com/index.rdf"},
    {"id": "kijolifehack", "name": "オンナの本音｜2ch生活まとめ-鬼女ライフハック", "url": "http://www.kijolifehack.com/index.rdf"},
    {"id": "jyoseisama", "name": "女性様｜鬼女・生活2chまとめブログ", "url": "https://jyoseisama.com/index.rdf"},
    {"id": "mojomojo_licarca", "name": "喪女リカ喪女ルカ┃鬼女・生活系まとめサイト", "url": "http://mojomojo-licarca.com/index.rdf"},
    {"id": "kijosokuho", "name": "鬼女速報 ― キチママ・修羅場まとめ ―", "url": "http://kijosokuho.com/index.rdf"},
    {"id": "kijonikki", "name": "鬼女日記 -鬼女・修羅場・キチママ系まとめ-", "url": "http://kijonikki.net/index.rdf"},
    {"id": "kijyotown", "name": "鬼女タウン", "url": "http://kijyotown.net/index.rdf"},
    {"id": "kijoden", "name": "鬼女まとめ伝説｜生活2chまとめブログ", "url": "http://kijoden.com/index.rdf"},
    {"id": "kijoume", "name": "鬼女梅‐育児・ママ友・義実家・生活まとめ‐", "url": "http://kijoume.net/index.rdf"},
    {"id": "kijorabu", "name": "鬼女乱舞-キチママ・鬼女・修羅場系まとめ-", "url": "http://kijorabu.com/index.rdf"},
    {"id": "kijyomatome_ch", "name": "鬼女まとめちゃんねる｜生活2chまとめブログ", "url": "http://kijyomatome-ch.com/index.rdf"},
    {"id": "kijyokatu", "name": "鬼女の生活｜2ch修羅場まとめブログ", "url": "http://kijyokatu.com/index.rdf"},
    {"id": "kijyomita", "name": "鬼女はみた -修羅場・恋愛・育児系まとめサイト-", "url": "http://kijyomita.com/index.rdf"},
    {"id": "kizyonouwaki", "name": "鬼女の浮気速報｜ 2ch鬼女・キチママ・修羅場まとめ", "url": "http://kizyonouwaki.com/index.rdf"},
    {"id": "kijyotsubu", "name": "鬼女のつぶやき〜2ch鬼女・キチママ・生活まとめ〜", "url": "http://kijyotsubu.net/index.rdf"},
    {"id": "kijonotakuhaibin", "name": "鬼女の宅配便 - 修羅場・浮気からほのぼの系まで[まとめサイト]", "url": "http://kijonotakuhaibin.com/index.rdf"},
    {"id": "kijyokaigi", "name": "鬼女の井戸端会議-鬼女、キチママ、修羅場、生活まとめ-", "url": "http://kijyokaigi.com/index.rdf"},
    {"id": "2chmatome", "name": "長編にちゃんまとめ　修羅場・浮気", "url": "http://2chmatome.net/index.rdf"},
    {"id": "uwakitaiken", "name": "衝撃体験！アンビリバボー｜浮気・修羅場・スカッとまとめ", "url": "http://uwakitaiken.com/index.rdf"},
    {"id": "polite_kijyo", "name": "拝啓、鬼女様", "url": "http://polite-kijyo.net/index.rdf"},
    {"id": "ikarishintou", "name": "怒り新党～仕返し・復讐・修羅場まとめ～", "url": "http://ikarishintou.com/index.rdf"},
    {"id": "kitizawa", "name": "基地沢直樹-復讐・修羅場・DQN返し【2chスカッとする話まとめ】", "url": "http://kitizawa.com/index.rdf"},
    {"id": "uwasakijo", "name": "噂の鬼女様", "url": "http://uwasakijo.net/index.rdf"},
    {"id": "shurabanote", "name": "修羅場ノート-2ch修羅場・復讐まとめ-", "url": "http://shurabanote.com/index.rdf"},
    {"id": "shurabana", "name": "修羅場な話まとめ", "url": "http://shurabana.com/index.rdf"},
    {"id": "syurabahazard", "name": "修羅場ハザード -復讐・DQN返し・衝撃系まとめ-", "url": "http://syurabahazard.com/index.rdf"},
    {"id": "shurabach", "name": "修羅場ちゃんねる", "url": "http://shurabach.org/index.rdf"},
    {"id": "densetsunokijo", "name": "伝説の鬼女 ～修羅場・キチママ・生活まとめ～", "url": "http://densetsunokijo.net/index.rdf"},
    {"id": "syuramama", "name": "修羅ママ速報", "url": "http://syuramama.com/index.rdf"},
    {"id": "matometemitatta", "name": "一回は一回です。。｜ 2ch修羅場・復讐まとめ", "url": "http://www.matometemitatta.com/index.rdf"},
    {"id": "labradorsokuho", "name": "ラブラドール速報～生活・修羅場・鬼女まとめ～", "url": "http://labradorsokuho.net/index.rdf"},
    {"id": "celery_marine", "name": "セロリのマリネ", "url": "http://celery-marine.net/feed"},
    {"id": "sukashuraba", "name": "スカッとする修羅場まとめ", "url": "http://sukashuraba.net/index.rdf"},
    {"id": "dorosoku", "name": "ドロドロ速報-鬼女・不倫・浮気・修羅場系まとめ", "url": "http://dorosoku.com/index.rdf"},
    {"id": "girls2chmatome", "name": "ガールズにちゃんまとめ～生活・鬼女～", "url": "http://girls2chmatome.net/index.rdf"},
    {"id": "kichimama_1", "name": "キチママまとめちゃんねる", "url": "http://kichimama.net/index.rdf"},
    {"id": "pomepuu", "name": "ぽめぷー速報 ～修羅場・キチママ・生活まとめ～", "url": "http://pomepuu.net/index.rdf"},
    {"id": "nyankosokuho", "name": "にゃんこ速報～修羅場・キチママ・生活まとめ～", "url": "http://nyankosokuho.com/index.rdf"},
    {"id": "kimagure_kijyo", "name": "きまぐれ鬼女-鬼女・不倫・浮気・修羅場系まとめ", "url": "http://kimagure-kijyo.com/index.rdf"},
    {"id": "eegg", "name": "easterEgg", "url": "http://eegg.fun/index.rdf"},
    {"id": "kichimama_life", "name": "キチママらいふ－浮気・不倫・修羅場－", "url": "http://kichimama-life.com/index.rdf"},
    {"id": "kichimama_2", "name": "キチママ警報 -キチママ・生活系まとめ-", "url": "http://kichimama.com/index.rdf"},
    {"id": "kijyosama", "name": "鬼女様.com", "url": "http://kijyosama.com/feed"},
    {"id": "syurabake", "name": "修羅場家の日常", "url": "http://syurabake.com/index.rdf"},
    {"id": "kijyonoyaiba", "name": "鬼女の刃", "url": "http://blog.livedoor.jp/kijyonoyaiba/index.rdf"},
    {"id": "chiwasoku_2", "name": "痴話速報", "url": "http://chiwasoku.ldblog.jp/index.rdf"},
    {"id": "life_traveling", "name": "ライフトラベリング", "url": "http://life-traveling.com/?xml"},
    {"id": "syurasan", "name": "しゅらさん｜キチママ・修羅場の生活まとめ", "url": "https://www.syurasan.com/?xml"},
    {"id": "diet2channel", "name": "ダイエット速報＠2ちゃんねる", "url": "http://blog.livedoor.jp/diet2channel/index.rdf"},
    {"id": "tozanchannel", "name": "登山ちゃんねる", "url": "http://tozanchannel.blog.jp/index.rdf"},
    {"id": "oryouri", "name": "お料理速報", "url": "http://oryouri.2chblog.jp/index.rdf"},
    {"id": "i2chmeijin", "name": "2ch名人", "url": "http://i2chmeijin.blog.fc2.com/?xml"},
    {"id": "watch_times", "name": "ウォッチちゃんねる", "url": "http://watch-times.com/feed"},
    {"id": "tsurimatome", "name": "釣りまとめ速報", "url": "http://tsurimatome.com/index.rdf"},
    {"id": "ramen2ch", "name": "ラーメン速報｜2chまとめブログ", "url": "http://ramen2ch.com/?xml"},
    {"id": "manpukunews", "name": "まんぷくにゅーす", "url": "http://manpukunews.blog.jp/index.rdf"},
    {"id": "shouginews", "name": "将棋まとめた@２ｃｈ", "url": "http://shouginews.blog.jp/index.rdf"},
    {"id": "meshinews", "name": "メシニュース", "url": "http://meshinews.blog.jp/index.rdf"},
    {"id": "otameshivip", "name": "オタ飯VIP", "url": "http://otameshivip.com/index.rdf"},
    {"id": "gurum", "name": "おいしいお", "url": "http://www.gurum.biz/index.rdf"},
    {"id": "moeaudio", "name": "Sound Field", "url": "http://moeaudio.blog29.fc2.com/?xml"},
    {"id": "otomatome", "name": "音まとめ", "url": "http://blog.livedoor.jp/otomatome/index.rdf"},
    {"id": "gurumato", "name": "グルメまとめの「ぐるまと！」", "url": "http://gurumato.net/feed"},
    {"id": "fishing_sokuhou", "name": "フィッシング速報", "url": "http://fishing-sokuhou.com/index.rdf"},
    {"id": "techsoku", "name": "Tech速", "url": "https://techsoku.com/feed"},
    {"id": "ladyplus", "name": "宵越しの銭はもたぬ速報", "url": "https://ladyplus.xyz/feed/"},
    {"id": "gfoodd", "name": "明日は何を食べようか", "url": "http://gfoodd.com/feed"},
    {"id": "kintore_channel", "name": "筋トレちゃんねる(*´ω｀*)", "url": "http://kintore-channel.com/index.rdf"},
    {"id": "outdooor", "name": "アウトドアまとめちゃん", "url": "http://outdooor.blog.jp/index.rdf"},
    {"id": "rolesoku", "name": "ロレ速【腕時計ブログ】", "url": "http://www.rolesoku.tokyo/index.rdf"},
    {"id": "meshi2ch", "name": "2ch飯ちゃんねる", "url": "https://meshi2ch.blog.jp/index.rdf"},
    {"id": "kintore2018", "name": "筋トレ予備校まとめ", "url": "http://kintore2018.blog.jp/index.rdf"},
    {"id": "myoushu", "name": "将棋まとめブログ", "url": "https://myoushu.net/feed/"},
    {"id": "tabinolog", "name": "旅のろぐ", "url": "https://tabinolog.com/feed"},
    {"id": "campmag", "name": "Camping mag まとめちゃんねる", "url": "https://campmag.blog.jp/index.rdf"},
    {"id": "kintore_daietto", "name": "筋トレ×ダイエットまとめ", "url": "http://kintore-daietto.blog.jp/index.rdf"},
    {"id": "gotisoku", "name": "ごちそう速報", "url": "http://blog.livedoor.jp/gotisoku/index.rdf"},
    {"id": "trainch", "name": "鉄ヲタちゃんねる", "url": "http://trainch.blog.jp/index.rdf"},
    {"id": "a11", "name": "筋トレ速報", "url": "https://a11.work/index.rdf"},
    {"id": "mcri", "name": "マクド総研", "url": "http://mcri.blog/?feed=rss2"},
    {"id": "netshogimatome", "name": "ネト将まとめ", "url": "https://netshogimatome.blog.fc2.com/?xml"},
    {"id": "goto_outdoors", "name": "GOTOアウトドア", "url": "https://goto-outdoors.jp/index.rdf"},
    {"id": "slotmania222", "name": "スロパチ乱舞", "url": "http://slotmania222.com/index.rdf"},
    {"id": "suzusoku", "name": "鈴木さん速報", "url": "http://suzusoku.blog.jp/index.rdf"},
    {"id": "gomepachi", "name": "パチンコ激震速報", "url": "http://gomepachi.com/index.rdf"},
    {"id": "fiveslot777", "name": "スロ板-RUSH", "url": "http://fiveslot777.com/index.rdf"},
    {"id": "pachislotzone", "name": "スロパチゾーン　パチンコパチスロまとめ", "url": "http://pachislotzone.com/feed"},
    {"id": "pachi_yamete", "name": "ようこそ僕らのパチンコ業界へ！", "url": "https://pachi-yamete.com/feed"},
    {"id": "pachinkopachisro", "name": "パチンコ・パチスロ.com", "url": "http://pachinkopachisro.com/index.rdf"},
    {"id": "slo_matome", "name": "スロカク | パチスロデータ格付けブログ", "url": "https://slo-matome.com/category/news/feed/"},
    {"id": "slotlog", "name": "パチスロログ", "url": "https://slotlog.net/feed"},
    {"id": "parlourfullslotl", "name": "パーラーフルスロットル", "url": "https://parlourfullslotl.com/feed"},
    {"id": "pachinkolist", "name": "ぱちんこドキュメント!!", "url": "http://pachinkolist.com/index.rdf"},
    {"id": "metabopro", "name": "ぱちとろ速報", "url": "https://metabopro.net/feed"},
    {"id": "baiku_sokuho", "name": "バイク速報", "url": "http://baiku-sokuho.info/index.rdf"},
    {"id": "vehicle123", "name": "車速報", "url": "http://vehicle123.com/index.rdf"},
    {"id": "kurumachannel", "name": "車ちゃんねる", "url": "http://kurumachannel.com/index.rdf"},
    {"id": "cysoku", "name": "サイ速", "url": "http://cysoku.com/index.rdf"},
    {"id": "bikechannel", "name": "ばいくちゃんねる", "url": "https://www2.bikechannel.info/feed"},
    {"id": "mycarsoku", "name": "マイカー速報", "url": "http://mycarsoku.com/index.rdf"},
    {"id": "kurumania", "name": "くるまにあ速報", "url": "http://kurumania.blog.jp/index.rdf"},
    {"id": "norisoku", "name": "乗り物速報", "url": "http://norisoku.com/index.rdf"},
    {"id": "turbo_bee", "name": "Turbo Bee - 自動車・バイク動画のターボビー", "url": "http://turbo-bee.com/index.rdf"},
    {"id": "new24", "name": "くるまとめ", "url": "http://new24.blog.jp/index.rdf"},
    {"id": "bybybicycle", "name": "チャリ足", "url": "http://bybybicycle.blog.jp/index.rdf"},
    {"id": "baiku_life", "name": "バイクライフちゃんねる", "url": "https://baiku-life.com/feed"},
    {"id": "norimonoblog", "name": "乗り物BLOG", "url": "http://norimonoblog.com/index.rdf"},
    {"id": "kurumatome", "name": "くるまとめ！", "url": "https://www.kurumatome.fun/?feed=rss2"},
    {"id": "aqua2ch", "name": "アクアカタリスト", "url": "http://aqua2ch.net/index.rdf"},
    {"id": "usi32", "name": "うしみつ-2ch怖い話まとめ-", "url": "http://usi32.com/index.rdf"},
    {"id": "animalch", "name": "どうぶつちゃんねる", "url": "http://animalch.net/index.rdf"},
    {"id": "ocsoku", "name": "オカルト速報 - オカルト・洒落怖・怖い話・不可思議な話まとめ -", "url": "http://ocsoku.com/index.rdf"},
    {"id": "nagooka", "name": "なごめるおかると", "url": "http://nagooka.net/index.rdf"},
    {"id": "paranormal_ch", "name": "パラノーマルちゃんねる | 2ch怖い話まとめ", "url": "http://www.paranormal-ch.com/index.rdf"},
    {"id": "mojokosan", "name": "ほのぼの絵にっき", "url": "http://mojokosan.doorblog.jp/index.rdf"},
    {"id": "nekowan", "name": "猫の動画 ねこわん！", "url": "http://nekowan.com/index.rdf"},
    {"id": "fashion_news", "name": "ファ板速報", "url": "http://fashion-news.doorblog.jp/index.rdf"},
    {"id": "hatopo", "name": "ハトポ - 海外の反応", "url": "http://hatopo.doorblog.jp/archives/cat_288607.xml"},
    {"id": "nipasoku", "name": "にぱ速", "url": "http://nipasoku.blog.jp/index.rdf"},
    {"id": "mens_fashion", "name": "男子ファッション速報", "url": "http://mens-fashion.blog.jp/index.rdf"},
    {"id": "hokkorihann", "name": "ほっこりはん", "url": "https://hokkorihann.com/?xml"},
    {"id": "mkc", "name": "Men&#039;s化粧品ちゃんねる", "url": "http://mkc.blog.jp/index.rdf"},
    {"id": "zuy_san0119", "name": "ずわいまとめ〆〆", "url": "http://zuy-san0119.com/feed"},
    {"id": "kameburo", "name": "かめぶろ！", "url": "http://kameburo.blog.jp/index.rdf"},
    {"id": "highfashionmens", "name": "ハイファッションちゃんねる", "url": "https://highfashionmens.com/feed"},
    {"id": "world_study", "name": "世界歴史ちゃんねる", "url": "https://world-study.jp/feed"},
    {"id": "kitatouhoku_news", "name": "北と～ほぐニュース", "url": "http://kitatouhoku-news.blog.jp/index.rdf"},
    {"id": "neko_news", "name": "猫だらけニュース", "url": "http://neko-news.blog.jp/index.rdf"},
    {"id": "animal_world", "name": "どうぶつの世界　～動物まとめサイト～", "url": "http://animal-world.info/?xml"},
    {"id": "hakaseneet", "name": "博士ニートまとめ", "url": "http://hakaseneet.blog.jp/index.rdf"},
    {"id": "rekimato", "name": "歴ネタまとブ", "url": "http://rekimato.blog.jp/index.rdf"},
    {"id": "doubutsunet", "name": "動物愛好net", "url": "http://doubutsunet.com/index.rdf"},
    {"id": "wadatsumisokuhou", "name": "ワダツミ速報", "url": "https://wadatsumisokuhou.com/feed"},
    {"id": "kongaich", "name": "婚外ちゃんねる", "url": "http://kongaich.livedoor.biz/index.rdf"},
    {"id": "waruneko00326_002", "name": "歴史的速報", "url": "http://blog.livedoor.jp/waruneko00326-002/index.rdf"},
    {"id": "rikeinews", "name": "理系にゅーす", "url": "http://rikeinews.blog.jp/index.rdf"},
    {"id": "mofful", "name": "もっふるちゃんねる", "url": "http://mofful.livedoor.blog/index.rdf"},
    {"id": "ocalt", "name": "次元の扉　オカルトまとめ", "url": "http://ocalt.work/index.rdf"},
    {"id": "love_knowledge", "name": "知識の城　群雄割拠", "url": "https://love-knowledge.com/feed"},
    {"id": "sky_spider", "name": "自虐史感から脱却して世界を見る", "url": "https://blog.sky-spider.com/index.xml"},
    {"id": "nanjstu", "name": "なんじぇいスタジアム＠なんJまとめ", "url": "http://blog.livedoor.jp/nanjstu/index.rdf"},
    {"id": "yakiusoku", "name": "日刊やきう速報＠野球まとめ", "url": "http://blog.livedoor.jp/yakiusoku/index.rdf"},
    {"id": "rock1963roll", "name": "なんJ PRIDE", "url": "http://blog.livedoor.jp/rock1963roll/index.rdf"},
    {"id": "hanshintigers1", "name": "阪神タイガースちゃんねる", "url": "http://hanshintigers1.blog.jp/index.rdf"},
    {"id": "bbyakyu", "name": "竜速（りゅうそく）", "url": "http://blog.livedoor.jp/bbyakyu/index.rdf"},
    {"id": "livejupiter2", "name": "なんJ（まとめては）いかんのか？", "url": "http://blog.livedoor.jp/livejupiter2/index.rdf"},
    {"id": "fightersmatome", "name": "ポリー速報", "url": "http://blog.livedoor.jp/fightersmatome/index.rdf"},
    {"id": "matomelotte", "name": "まとめロッテ！", "url": "http://matomelotte.com/index.rdf"},
    {"id": "lions_matome", "name": "やみ速@なんJ西武まとめ", "url": "https://lions-matome.com/archives/category/%E8%A5%BF%E6%AD%A6/feed"},
    {"id": "tsubamesoku", "name": "ツバメ速報", "url": "http://tsubamesoku.blog.jp/index.rdf"},
    {"id": "oekaki_navi", "name": "野球お絵かきまとめ@おんJ", "url": "http://oekaki-navi.blog.jp/index.rdf"},
    {"id": "koisoku", "name": "鯉速＠広島東洋カープまとめブログ", "url": "http://koisoku.ldblog.jp/index.rdf"},
    {"id": "hawksmatome", "name": "鷹速@ホークスまとめブログ", "url": "http://blog.livedoor.jp/hawksmatome/index.rdf"},
    {"id": "carp_matome", "name": "広島東洋カープまとめブログ | かーぷぶーん", "url": "http://carp-matome.blog.jp/index.rdf"},
    {"id": "nanjde", "name": "ベイスターズ速報＠なんJ", "url": "http://nanjde.blog.jp/index.rdf"},
    {"id": "g_soku", "name": "Ｇ速@読売ジャイアンツまとめブログ", "url": "http://g-soku.blog.jp/index.rdf"},
    {"id": "kyuukaiou", "name": "ベースボールスレッド", "url": "http://kyuukaiou.ldblog.jp/index.rdf"},
    {"id": "nanj_atarimae", "name": "鴎速＠ロッテなんJ社畜ch", "url": "http://nanj-atarimae.doorblog.jp/index.rdf"},
    {"id": "sisitama", "name": "獅子の魂@西武ライオンズまとめ", "url": "http://sisitama.blog.jp/index.rdf"},
    {"id": "cowboy", "name": "ORIXBLOG＠オリックス・バファローズまとめブログ", "url": "http://cowboy.blog.jp/index.rdf"},
    {"id": "inuwashitimes", "name": "狗鷲タイムス", "url": "http://inuwashitimes.blog.jp/index.rdf"},
    {"id": "fighters_kingdom", "name": "ファイターズ王国＠日ハムまとめブログ", "url": "http://fighters-kingdom.blog.jp/index.rdf"},
    {"id": "npb_news", "name": "NPB NEWS@なんJまとめ", "url": "http://npb-news.com/index.rdf"},
    {"id": "blomaga_3", "name": "オリックス2ch野球まとめ速報ブログ｜ベル速@なんJ", "url": "http://buffaloesmatome.blomaga.jp/index.rdf"},
    {"id": "vipch_baseball", "name": "フィルダースチョイス", "url": "http://blog.livedoor.jp/vipch-baseball/index.rdf"},
    {"id": "de_baystars", "name": "De速", "url": "http://de-baystars.doorblog.jp/index.rdf"},
    {"id": "torasoku", "name": "虎速", "url": "http://torasoku.blog.jp/index.rdf"},
    {"id": "tigersden", "name": "タイガースデン", "url": "http://tigersden.blog.jp/index.rdf"},
    {"id": "onjsummarynet", "name": "おんｊサマリー＠なんｊホークスまとめ", "url": "http://onjsummarynet.net/index.rdf"},
    {"id": "toraho", "name": "とらほー速報", "url": "http://toraho.blog.jp/index.rdf"},
    {"id": "jnobankisya", "name": "Jの番記者", "url": "http://jnobankisya.2chblog.jp/index.rdf"},
    {"id": "egiants", "name": "永久不滅ジャイアンツ", "url": "http://egiants.blog.jp/index.rdf"},
    {"id": "nanjsyurai", "name": "なんJ襲来", "url": "http://blog.livedoor.jp/nanjsyurai/index.rdf"},
    {"id": "officialblog", "name": "BASEBALL DAYS ＠ なんJおんJ", "url": "http://baseballdays.officialblog.jp/index.rdf"},
    {"id": "pacificmatome", "name": "パ・リーグまとめ屋本舗", "url": "http://pacificmatome.livedoor.blog/index.rdf"},
    {"id": "pitch_bat", "name": "投打スタジアムCH", "url": "https://pitch-bat.com/feed"},
    {"id": "baseball_nanj", "name": "きうり♪やきう♪きうり♪＠なんJ", "url": "http://baseball-nanj.com/?xml"},
    {"id": "toralucky", "name": "虎 Lucky", "url": "http://toralucky.fun/index.rdf"},
    {"id": "giantskyojin2chmatome", "name": "読売ジャイアンツ　巨人　2chまとめ速報", "url": "http://giantskyojin2chmatome.blog.jp/index.rdf"},
    {"id": "nanjmagnus", "name": "なんＪは加速している", "url": "http://blog.livedoor.jp/nanjmagnus/index.rdf"},
    {"id": "jinniro", "name": "プロ野球いろいろ速報", "url": "http://jinniro.blog.fc2.com/?xml"},
    {"id": "ringofred53", "name": "Red★速報", "url": "https://ringofred53.com/index.rdf"},
    {"id": "giants_pride_news", "name": "GIANTS PRIDE ニュース", "url": "https://giants-pride-news.com/category/giants/feed/"},
    {"id": "soccerkusoyarou", "name": "サッカーミックスジュース", "url": "http://blog.livedoor.jp/soccerkusoyarou/index.rdf"},
    {"id": "sakarabo", "name": "サカラボ | サッカーまとめ速報", "url": "http://sakarabo.blog.jp/index.rdf"},
    {"id": "calciomatome", "name": "カルチョまとめブログ", "url": "http://www.calciomatome.net/index.rdf"},
    {"id": "samuraigoal", "name": "Samurai GOAL", "url": "http://samuraigoal.doorblog.jp/index.rdf"},
    {"id": "domesoccer", "name": "ドメサカブログ", "url": "http://blog.domesoccer.jp/index.rdf"},
    {"id": "football_2ch", "name": "フットボール速報", "url": "http://football-2ch.com/index.rdf"},
    {"id": "samuraisoccer", "name": "SAMURAI Footballers", "url": "http://samuraisoccer.doorblog.jp/index.rdf"},
    {"id": "world_samurai", "name": "海外サッカー日本人選手速報 WORLD SAMURAI", "url": "http://world-samurai.com/index.rdf"},
    {"id": "sakasaka10", "name": "サカサカ10【サッカーまとめ速報】", "url": "http://sakasaka10.blog.jp/index.rdf"},
    {"id": "footcalcio", "name": "フットカルチョ", "url": "http://blog.livedoor.jp/footcalcio/index.rdf"},
    {"id": "worldfn", "name": "WorldFootballNewS", "url": "http://worldfn.net/index.rdf"},
    {"id": "football2channel", "name": "蹴球まとめちゃんねる", "url": "http://football2channel.blog.fc2.com/?xml"},
    {"id": "footballnet", "name": "footballnet【サッカーまとめ】", "url": "http://footballnet.2chblog.jp/index.rdf"},
    {"id": "football_channelxo", "name": "Football　Select", "url": "http://football-channelxo.blog.jp/index.rdf"},
    {"id": "j2iroiro", "name": "Ｊ２いろいろ", "url": "http://j2iroiro.blog.jp/index.rdf"},
    {"id": "soccerrevolution", "name": "サッカーレボリューション", "url": "http://blog.livedoor.jp/soccerrevolution/index.rdf"},
    {"id": "ichliebefussball", "name": "ブンデスリーガ　ドイツの反応 Ich liebe Fussball!!", "url": "http://ichliebefussball.net/?xml"},
    {"id": "jf_2016", "name": "JとFの歩き方", "url": "http://jf-2016.com/index.rdf"},
    {"id": "soccer_area", "name": "サッカーエリア", "url": "http://soccer-area.com/index.rdf"},
    {"id": "aokisoccerdarbie", "name": "青き血のサッカーダービー", "url": "http://aokisoccerdarbie.doorblog.jp/index.rdf"},
    {"id": "syuukyuu", "name": "蹴球的情報ch", "url": "https://syuukyuu.com/feed"},
    {"id": "soccer_time", "name": "サッカータイム", "url": "https://soccer-time.net/index.rdf"},
    {"id": "sakamato", "name": "サカまと！【サッカーまとめ】", "url": "https://sakamato.com/feed/"},
    {"id": "soccer_pride", "name": "サッカー『PRIDE(プライド)』", "url": "https://soccer-pride.com/index.rdf"},
    {"id": "f1jouhou2", "name": "F1情報通", "url": "http://f1jouhou2.blog.fc2.com/?xml"},
    {"id": "keiba", "name": "競馬ろまん亭", "url": "http://keiba.blog.jp/index.rdf"},
    {"id": "nofootynolife", "name": "NO FOOTY NO LIFE", "url": "http://nofootynolife.net/?xml"},
    {"id": "haronbouchannel", "name": "ハロン棒ch　-競馬まとめ-", "url": "http://haronbouchannel.com/index.rdf"},
    {"id": "orufemorufenz", "name": "オルフェンズの仔～～競馬ネタ予想まとめ", "url": "http://orufemorufenz.com/index.rdf"},
    {"id": "iyaaaao", "name": "イヤァオ！速報　プロレスまとめサイト", "url": "http://iyaaaao.doorblog.jp/index.rdf"},
    {"id": "footballavi", "name": "海外の反応 | Early cross", "url": "https://footballavi.com/archives/category/oversea/feed"},
    {"id": "fukukitare", "name": "マチカネフクキタレ！", "url": "https://fukukitare.com/feed"},
    {"id": "xxhuyuzero", "name": "フィギュアスケートまとめ零", "url": "http://xxhuyuzero.jp/feed"},
    {"id": "aushio", "name": "つれさか　-徒然サッカー雑記- - 海外の反応", "url": "http://blog.livedoor.jp/aushio/archives/cat_150742.xml"},
    {"id": "iroirokeiba", "name": "ギャン速2ch　～競馬まとめブログ～", "url": "http://iroirokeiba.blog.fc2.com/?xml"},
    {"id": "siokan5000", "name": "塩韓スポーツ", "url": "http://siokan5000.blog.fc2.com/?xml"},
    {"id": "world_soccer_fan", "name": "ワールドサッカーファン 海外の反応", "url": "https://www.world-soccer-fan.com/rss"},
    {"id": "kaisupo", "name": "海外の反応スポーツ", "url": "https://www.kaisupo.com/rss.xml?alt=rss"},
    {"id": "running_sokuho", "name": "ランニング速報", "url": "http://running-sokuho.com/index.rdf"},
    {"id": "nba123channel", "name": "NBAまとめちゃんねる", "url": "https://nba123channel.com/?feed=rss2"},
    {"id": "xn__2ch_2d8eo32c60z", "name": "2ch大相撲", "url": "http://xn--2ch-2d8eo32c60z.xyz/atom.xml"},
    {"id": "keibazanmai", "name": "競馬まとめざんまい", "url": "https://keibazanmai.net/feed/"},
    {"id": "marasoku", "name": "マラソン速報", "url": "http://marasoku.info/index.rdf"},
    {"id": "smasoku", "name": "スマッシュ速報", "url": "http://smasoku.blog.jp/index.rdf"},
    {"id": "ochimusha", "name": "週末は落ち武者", "url": "http://ochimusha.blog.jp/index.rdf"},
    {"id": "umasoku", "name": "うま速@競馬まとめブログ", "url": "https://umasoku.com/feed"},
    {"id": "knocoknoco", "name": "ノックオンノックオン　ラグビーまとめ", "url": "http://knocoknoco.blog.jp/index.rdf"},
    {"id": "umaumanews", "name": "競馬まとめのまとめ", "url": "http://umaumanews.com/feed"},
    {"id": "basketballbbs", "name": "バスケまとめ・COM", "url": "http://basketballbbs.com/feed/"},
    {"id": "rokyu_okoku", "name": "籠球王国", "url": "http://rokyu-okoku.blog.jp/index.rdf"},
    {"id": "keiba_umanami", "name": "☆うまなみ・競馬にゅーす速報", "url": "https://keiba-umanami.com/index.rdf"},
    {"id": "abroadch", "name": "アブロードチャンネル｜サッカー専門の海外の反応サイト", "url": "https://abroadch.com/feed/"},
    {"id": "keibapedia", "name": "ケイバペディア", "url": "https://keibapedia.com/?feed=rss2"},
    {"id": "nanako5ch", "name": "ナナコのユメ　競馬5chまとめ", "url": "http://nanako5ch.blog.jp/index.rdf"},
    {"id": "hapiyuzu", "name": "氷上の王子様・お姫様", "url": "https://hapiyuzu.com/feed"},
    {"id": "ballparksokuhou", "name": "ボールパーク速報 海外の反応", "url": "https://www.ballparksokuhou.com/?xml"},
    {"id": "every1_matome", "name": "えゔりわんゴルフまとめ", "url": "https://every1-matome.com/index.rdf"},
    {"id": "digital_thread", "name": "デジタルニューススレッド", "url": "http://digital-thread.com/index.rdf"},
    {"id": "onecall2ch", "name": "わんこーる速報！", "url": "http://onecall2ch.com/index.rdf"},
    {"id": "rakusyasa", "name": "うるるんロギー", "url": "http://rakusyasa.blog41.fc2.com/?xml"},
    {"id": "otanews", "name": "萌えオタニュース速報", "url": "http://otanews.livedoor.biz/index.rdf"},
    {"id": "otakomu", "name": "オタク.com", "url": "http://otakomu.jp/index.rdf"},
    {"id": "otasoku", "name": "ヲタク速報", "url": "http://otasoku.livedoor.biz/index.rdf"},
    {"id": "checkmate_blog", "name": "チェックメイト | 2chまとめブログ", "url": "http://checkmate-blog.com/feed"},
    {"id": "blomaga_4", "name": "ガジェットライフ速報 -ガジェット・スマホ・PCまとめ-", "url": "http://gadgetlife2ch.blomaga.jp/index.rdf"},
    {"id": "otanew", "name": "オタクニュース", "url": "http://otanew.jp/index.rdf"},
    {"id": "youblog", "name": "もゆげん-萌癒元-", "url": "http://moyugenn.youblog.jp/index.rdf"},
    {"id": "osusoku", "name": "おすすめ速報｜おすすめ情報まとめブログ", "url": "http://osusoku.com/feed"},
    {"id": "kokopyon", "name": "あぁ^～こころがぴょんぴょんするんじゃぁ^～", "url": "http://kokopyon.net/?xml"},
    {"id": "suresuta", "name": "すれすた", "url": "http://suresuta.jp/feed"},
    {"id": "nijimen", "name": "にじめん", "url": "http://nijimen.net/index.rdf"},
    {"id": "ebitsu", "name": "えび通", "url": "http://ebitsu.net/index.rdf"},
    {"id": "yaraon_blog", "name": "やらおん！", "url": "http://yaraon-blog.com/feed"},
    {"id": "otakamu", "name": "オタカム", "url": "http://otakamu.com/index.rdf"},
    {"id": "tarosoku", "name": "たろそくWP", "url": "http://tarosoku.com/?feed=rss2"},
    {"id": "manga_to_anime", "name": "まんがとあにめ", "url": "http://www.manga-to-anime.net/index.rdf"},
    {"id": "cherio199", "name": "ヒロイモノ中毒", "url": "http://cherio199.blog120.fc2.com/?xml"},
    {"id": "chansoku", "name": "ちゃん速", "url": "http://chansoku.com/index.rdf"},
    {"id": "gundamlog", "name": "GUNDAM.LOG｜ガンダムまとめブログ", "url": "http://gundamlog.com/index.rdf"},
    {"id": "chomanga", "name": "超マンガ速報", "url": "http://chomanga.org/feed"},
    {"id": "g_matome", "name": "ガンダムまとめ速報", "url": "http://g-matome.com/index.rdf"},
    {"id": "anihatsu", "name": "アニはつ -アニメ発信場-", "url": "http://anihatsu.com/index.rdf"},
    {"id": "kemochan", "name": "けもちゃん", "url": "http://kemochan.com/feed"},
    {"id": "lovelivematocha", "name": "ラブライブ！まとめちゃんねる！！", "url": "http://lovelivematocha.com/?xml"},
    {"id": "pokesoku", "name": "ポケモン速報", "url": "http://pokesoku.jp/index.rdf"},
    {"id": "shingekikyojin", "name": "進撃の巨人ちゃんねる", "url": "http://shingekikyojin.net/index.rdf"},
    {"id": "chomangasokuho", "name": "超・マンガ速報", "url": "http://chomangasokuho.blog.jp/index.rdf"},
    {"id": "iroirosokuhou", "name": "色々まとめ速報", "url": "http://iroirosokuhou.com/index.rdf"},
    {"id": "anige_sokuhouvip", "name": "アニゲー速報", "url": "http://www.anige-sokuhouvip.com/?xml"},
    {"id": "gabiyori", "name": "げーあにびより｜ゲームやアニメの評価・感想まとめ", "url": "http://gabiyori.com/feed"},
    {"id": "mudasure", "name": "ムダスレ無き改革", "url": "http://mudasure.com/?xml"},
    {"id": "anige_labo", "name": "アニゲーラボ", "url": "https://anige-labo.com/feed"},
    {"id": "niziiro", "name": "にじいろびより", "url": "http://niziiro.net/index.rdf"},
    {"id": "blomaga_5", "name": "それからの出来事() アイマスまとめ", "url": "http://sorekarano.blomaga.jp/index.rdf"},
    {"id": "moeponzu", "name": "もえぽんず。", "url": "http://moeponzu.com/?xml"},
    {"id": "aaieba", "name": "ああ言えばForYou", "url": "http://aaieba.livedoor.biz/index.rdf"},
    {"id": "anibuta", "name": "アニ豚ニュース速報", "url": "http://www.anibuta.com/index.rdf"},
    {"id": "imasoku", "name": "いま速", "url": "https://imasoku.com/feed"},
    {"id": "nichijoukei", "name": "日常系アニメふぁん", "url": "http://nichijoukei.com/index.rdf"},
    {"id": "yomisoku", "name": "読み速", "url": "http://yomisoku.com/feed"},
    {"id": "coreserver", "name": "Glauber通信", "url": "http://lucky318b.m50.coreserver.jp/feed"},
    {"id": "neptsu", "name": "ネプテューヌ通信", "url": "https://neptsu.net/feed"},
    {"id": "manmato", "name": "漫まと", "url": "http://manmato.blog.jp/index.rdf"},
    {"id": "tachiyomitoday", "name": "今日の立ち読みまとめ", "url": "http://tachiyomitoday.com/index.rdf"},
    {"id": "cggekijo", "name": "でれげき -シンデレラガールズ劇場まとめ-", "url": "http://cggekijo.blog.fc2.com/?xml"},
    {"id": "youkaiwatch_nyansoku", "name": "妖怪ウォッチまとめ ニャン速", "url": "http://youkaiwatch-nyansoku.com/index.rdf"},
    {"id": "lovelive_you", "name": "ラブライブ! 曜ちゃんのヨーソロー!速報", "url": "http://lovelive-you.blog.jp/index.rdf"},
    {"id": "hatamoto_sokuhou", "name": "はたもと速報", "url": "http://hatamoto-sokuhou.com/index.rdf"},
    {"id": "hiari_srank", "name": "緋アリ速報", "url": "http://www.hiari-srank.com/index.rdf"},
    {"id": "ponpokonwes", "name": "ポンポコにゅーす ファン特化型アニメ感想サイト", "url": "https://ponpokonwes.com/index.rdf"},
    {"id": "jujutsu_matome", "name": "呪術廻戦まとめ速報", "url": "https://jujutsu-matome.com/feed"},
    {"id": "anichil", "name": "あにちる速報", "url": "https://anichil.com/index.rdf"},
    {"id": "fgo_babylonia_cafe", "name": "ばびろにあっ！", "url": "https://fgo-babylonia-cafe.jp/feed/"},
    {"id": "precurematome", "name": "プリキュアのまとめ", "url": "http://precurematome.com/feed/"},
    {"id": "dsara", "name": "ネット民の反応：国内・海外のゲーム・アニメの反応まとめ！", "url": "https://dsara.blog.fc2.com/?xml"},
    {"id": "comisoku", "name": "コミック速報", "url": "https://comisoku.com/feed"},
    {"id": "roboanime", "name": "ロボアニ速報", "url": "https://roboanime.com/index.rdf"},
    {"id": "2chmokomokocat", "name": "もこキャニュース", "url": "http://2chmokomokocat.blog72.fc2.com/?xml"},
    {"id": "magazinematome", "name": "マガジンまとめ速報", "url": "http://magazinematome.livedoor.blog/index.rdf"},
    {"id": "onepianimemanga", "name": "【GAC】ゲーム！アニメ！漫画便！", "url": "https://onepianimemanga.com/feed/"},
    {"id": "matome_new", "name": "新5chまとめ速報-ネオ速-", "url": "https://matome-new.com//?feed=rss2"},
    {"id": "oshicyara", "name": "おしキャラっ", "url": "http://oshicyara.blog.jp/atom.xml"},
    {"id": "heroacamatome", "name": "僕のヒーローアカデミアまとめ", "url": "http://heroacamatome.ldblog.jp/index.rdf"},
    {"id": "mizuki_0121", "name": "みず速", "url": "http://mizuki-0121.blog.jp/index.rdf"},
    {"id": "hanayorimanga", "name": "花より漫画", "url": "https://hanayorimanga.com/index.rdf"},
    {"id": "skyair0831", "name": "アニメ評論まとめ", "url": "https://skyair0831.livedoor.blog/index.rdf"},
    {"id": "shi0r1sarada", "name": "最新アニメまとめ", "url": "https://shi0r1sarada.livedoor.blog/index.rdf"},
    {"id": "n10h08h20h05", "name": "アニメまとめ2024", "url": "https://n10h08h20h05.livedoor.blog/index.rdf"},
    {"id": "chikara1454", "name": "アニメまとめカレンダー", "url": "https://chikara1454.livedoor.blog/index.rdf"},
    {"id": "hbr_square", "name": "ヘブバン広場", "url": "https://hbr-square.com/feed/"},
    {"id": "azurlane_sokuhou", "name": "アズレン速報", "url": "https://azurlane-sokuhou.com/?feed=rss2"},
    {"id": "snow0705", "name": "まどんぬのきっちりアニメブログ", "url": "https://snow0705.livedoor.blog/index.rdf"},
    {"id": "sduhrk", "name": "アニメの総合集", "url": "https://sduhrk.livedoor.blog/index.rdf"},
    {"id": "loveless0419", "name": "アニメまとめ", "url": "https://loveless0419.livedoor.blog/index.rdf"},
    {"id": "ksakamo0903", "name": "わちゃくちゃ速報", "url": "https://ksakamo0903.com/feed/"},
    {"id": "ad_ars_line", "name": "Collect animations", "url": "https://ad-ars-line.blog/?feed=rss2"},
    {"id": "manhwa2025", "name": "ハナちゃんのマンガメゾン", "url": "https://manhwa2025.livedoor.blog/index.rdf"},
    {"id": "poketuu", "name": "ポケモンまとめ速報", "url": "https://poketuu.blog.jp/index.rdf"},
    {"id": "saikyo_jump", "name": "最強ジャンプ放送局", "url": "http://www.saikyo-jump.com/index.rdf"},
    {"id": "jumpsokuhou_1", "name": "ジャンプ速報", "url": "http://jumpsokuhou.com/index.rdf"},
    {"id": "hunter31", "name": "ハンターハンター速報", "url": "http://hunter31.blog.fc2.com/?xml"},
    {"id": "seiyufan", "name": "ジャンプまとめ漫画アニメ声優ゲーム", "url": "http://seiyufan.livedoor.biz/index.rdf"},
    {"id": "jumpsokuhou_2", "name": "JUMP(ジャンプ)速報", "url": "http://jumpsokuhou.blog.jp/index.rdf"},
    {"id": "jumpmatome2ch_1", "name": "ジャンプまとめ速報", "url": "http://jumpmatome2ch.biz/feed"},
    {"id": "worldtriggermatome", "name": "ワールドトリガーまとめ", "url": "https://worldtriggermatome.ldblog.jp/index.rdf"},
    {"id": "jumpmatome2ch_2", "name": "超・ジャンプまとめ速報", "url": "https://jumpmatome2ch.net/feed"},
    {"id": "duellinks", "name": "遊戯王デュエルリンクス超速報！", "url": "http://duellinks.doorblog.jp/index.rdf"},
    {"id": "weblog", "name": "ワンピースまとめ", "url": "http://onepiece.weblog.to/index.rdf"},
    {"id": "jojo_matome", "name": "ジョジョまとめ速報ッ！", "url": "https://jojo-matome.blog.jp/index.rdf"},
    {"id": "jin115", "name": "オレ的ゲーム速報＠刃", "url": "http://jin115.com/index.rdf"},
    {"id": "gehasoku", "name": "ゲハ速", "url": "http://gehasoku.com/index.rdf"},
    {"id": "openworldnews", "name": "PS4速報！", "url": "http://openworldnews.net/index.rdf"},
    {"id": "akankore", "name": "あ艦これ ～艦隊これくしょんまとめブログ～", "url": "http://akankore.doorblog.jp/index.rdf"},
    {"id": "gamedaradara", "name": "ゲームだらだら速報", "url": "http://gamedaradara.doorblog.jp/index.rdf"},
    {"id": "ff14net", "name": "FF14速報", "url": "http://ff14net.2chblog.jp/index.rdf"},
    {"id": "owacon", "name": "終わらないコンテンツ速報", "url": "http://owacon.livedoor.biz/index.rdf"},
    {"id": "aatyu", "name": "ゲーハー黙示録", "url": "http://blog.livedoor.jp/aatyu/index.rdf"},
    {"id": "coleblog", "name": "2ch東方スレ観測所", "url": "http://blog.livedoor.jp/coleblog/index.rdf"},
    {"id": "kanmsu", "name": "かんむす！-艦隊これくしょんまとめブログ-", "url": "http://kanmsu.com/feed"},
    {"id": "xn__eckybzahmsm43ab5g5336c9iug", "name": "ニンテンドースイッチ速報", "url": "http://xn--eckybzahmsm43ab5g5336c9iug.com/feed"},
    {"id": "imas_cg", "name": "もばます！", "url": "http://imas-cg.net/index.rdf"},
    {"id": "kandatasokuho", "name": "カンダタ速報", "url": "http://kandatasokuho.blog.fc2.com/?xml"},
    {"id": "switchsoku", "name": "SWITCH速報", "url": "http://switchsoku.com/feed"},
    {"id": "ff14hikasensokuhou", "name": "FF14ひかせん速報", "url": "https://ff14hikasensokuhou.com/?xml"},
    {"id": "chigesoku3", "name": "チゲ速", "url": "http://chigesoku3.doorblog.jp/index.rdf"},
    {"id": "ge_soku", "name": "げぇ速", "url": "http://ge-soku.com/index.rdf"},
    {"id": "battlefield_soku", "name": "BF5速報 -バトルフィールドVまとめ", "url": "http://battlefield-soku.blog.jp/index.rdf"},
    {"id": "psneolog", "name": "PS4ProNEWS", "url": "http://psneolog.com/feed"},
    {"id": "monhang", "name": "MHW攻略まとめ モンハン！", "url": "http://monhang.net/feed"},
    {"id": "ff15soku", "name": "FF15速報", "url": "http://ff15soku.2chblog.jp/index.rdf"},
    {"id": "xn__p8j0cnw2b2487d", "name": "どうぶつの森 みんなでポケットキャンプ (ポケ森)", "url": "http://xn--p8j0cnw2b2487d.jp/feed"},
    {"id": "kancolle", "name": "艦これ速報　艦隊これくしょんまとめ", "url": "http://kancolle.doorblog.jp/index.rdf"},
    {"id": "sokuho_2", "name": "爆NEWゲーム速報", "url": "http://bnewg.sokuho.org/index.rdf"},
    {"id": "mhsoku", "name": "モンハン速報 モンハンワールドまとめ", "url": "http://mhsoku.doorblog.jp/index.rdf"},
    {"id": "monhan_mhw", "name": "モンハンワールド2chまとめ速報 - MHW攻略", "url": "http://monhan-mhw.com/index.rdf"},
    {"id": "monst_sokuhou", "name": "モンスト速報　モンスターストライクまとめ", "url": "http://monst-sokuhou.blog.jp/index.rdf"},
    {"id": "minigob_matome", "name": "ミニゴブ速報 ～グラブルまとめ～", "url": "http://minigob-matome.blog.jp/index.rdf"},
    {"id": "pazusoku", "name": "パズ速 -パズドラ情報まとめ-", "url": "http://pazusoku.blog.fc2.com/?xml"},
    {"id": "pawapuro_matome", "name": "パワプロスマホアプリまとめ", "url": "http://pawapuro-matome.jp/index.rdf"},
    {"id": "forzaxbox", "name": "最新ゲーム速報！がんばれXboxヾ(。゜▽゜).", "url": "http://forzaxbox.net/?xml"},
    {"id": "sagareuniversesoku", "name": "ロマサガRS攻略速報", "url": "http://sagareuniversesoku.com/?xml"},
    {"id": "sumaburayasan", "name": "スマブラ屋さん | スマブラSPまとめ攻略", "url": "http://sumaburayasan.com/index.rdf"},
    {"id": "h_pon", "name": "オーガch.-パズドラ攻略まとめ速報", "url": "http://h-pon.doorblog.jp/index.rdf"},
    {"id": "yabesoku", "name": "矢部速報 | スマホアプリ版パワプロ攻略まとめブログ", "url": "http://yabesoku.blog.jp/archives/cat_863201.xml"},
    {"id": "game084", "name": "ゲーム攻略のまるはし", "url": "http://blog.game084.com/index.rdf"},
    {"id": "gamerlife", "name": "ゲーム生活はじめました", "url": "http://gamerlife.blog.jp/index.rdf"},
    {"id": "matome_agent56", "name": "モンスト！まとめーじぇんと。", "url": "http://matome-agent56.blog.jp/index.rdf"},
    {"id": "dark_soku", "name": "ダークソウルまとめ速報", "url": "http://dark-soku.blog.jp/index.rdf"},
    {"id": "umadori0726", "name": "馬鳥速報", "url": "http://blog.livedoor.jp/umadori0726/index.rdf"},
    {"id": "gtavphoto", "name": "グランド・セフト・オート5写真大好きブログ！GTA5攻略情報ほか", "url": "http://gtavphoto.blog.jp/index.rdf"},
    {"id": "arknights_matome", "name": "アクナイ速報 -アークナイツまとめ-", "url": "http://arknights-matome.blog.jp/index.rdf"},
    {"id": "yurugame", "name": "ゆるゲーマー遅報", "url": "http://yurugame.doorblog.jp/index.rdf"},
    {"id": "rpg_matome", "name": "RPGまとめぷらす", "url": "https://rpg-matome.com/feed"},
    {"id": "azurlane", "name": "アズールレーン速報-アズレンまとめ", "url": "http://azurlane.doorblog.jp/index.rdf"},
    {"id": "pubgmatome", "name": "PUBGスマホまとめ｜パブジーモバイル", "url": "http://pubgmatome.blog.jp/index.rdf"},
    {"id": "shoujyozennsen", "name": "エピックセブン攻略まとめ", "url": "http://shoujyozennsen.blog.jp/index.rdf"},
    {"id": "kuromoba", "name": "アークナイツ速報ーアクナイまとめ", "url": "http://kuromoba.doorblog.jp/index.rdf"},
    {"id": "fireembs", "name": "ルフレch. - FEH攻略まとめ速報", "url": "http://fireembs.blog.jp/index.rdf"},
    {"id": "tohopoke", "name": "徒歩のポケモンまとめブログ", "url": "http://blog.livedoor.jp/tohopoke/index.rdf"},
    {"id": "srwmatome", "name": "スパロボまとめ速報", "url": "https://srwmatome.com/feed"},
    {"id": "ysokuhou", "name": "Y速報", "url": "http://ysokuhou.blog.jp/index.rdf"},
    {"id": "nokuo", "name": "本田未央ちゃん応援まとめ速報", "url": "http://nokuo.blog.jp/index.rdf"},
    {"id": "mutyun", "name": "mutyunのゲーム+αブログ", "url": "https://www.mutyun.com/feed"},
    {"id": "lol_yordle", "name": "よーどる速報-LoL5chまとめ", "url": "http://lol-yordle.blog.jp/index.rdf"},
    {"id": "mgif", "name": "エムジフ～音ゲー情報局(MGIF)～", "url": "http://www.mgif.jp/index.rdf"},
    {"id": "gameimpression", "name": "ゲーム感想・評価まとめ＠2ｃｈ", "url": "http://gameimpression.doorblog.jp/index.rdf"},
    {"id": "pokemon_matome", "name": "ぽけりん＠ポケモンソードシールド(剣盾)まとめ", "url": "http://pokemon-matome.net/index.rdf"},
    {"id": "pusonisokuhou", "name": "ぷそに速報！～PSO2,PSO2es,イドラまとめ～", "url": "http://pusonisokuhou.work/index.rdf"},
    {"id": "more_gamer_1", "name": "アークナイツまとめタイムズ", "url": "http://arknights.more-gamer.com/feed"},
    {"id": "splatoon_nawabari", "name": "スプラトゥーン攻略 – ナワバリ速報", "url": "https://splatoon-nawabari.com/feed"},
    {"id": "pokemongo_master", "name": "ポケモンまとめマスター", "url": "http://pokemongo-master.com/feed"},
    {"id": "fatego_matome", "name": "FGOまとめ速報", "url": "https://www.fatego-matome.com/feed/"},
    {"id": "fate_grandorder", "name": "Fate/Grand Order攻略情報まとめ", "url": "http://fate-grandorder.jp/?feed=rss2"},
    {"id": "xn__hhr014byylm9m90fi1p", "name": "荒野行動攻略まとめ隊", "url": "https://xn--hhr014byylm9m90fi1p.com/feed"},
    {"id": "xn__o9j0bk3kzb8d3ee20ala8a", "name": "ドラガリアロスト攻略まとめ隊", "url": "https://xn--o9j0bk3kzb8d3ee20ala8a.com/feed"},
    {"id": "xn__mckr6j9b9367e", "name": "ロマサガRS攻略まとめ隊", "url": "https://xn--mckr6j9b9367e.com/feed"},
    {"id": "xn__eckhu0c0d1b5kcu5305ksfpb", "name": "ドラクエライバルズ攻略まとめ隊", "url": "https://xn--eckhu0c0d1b5kcu5305ksfpb.com/feed"},
    {"id": "xn__gdkl0dubtwb7e", "name": "モンハンワールド攻略まとめ隊", "url": "https://xn--gdkl0dubtwb7e.net/feed"},
    {"id": "xn__cck5b2he9a1cc", "name": "アズレン攻略まとめ隊", "url": "https://xn--cck5b2he9a1cc.com/feed"},
    {"id": "xn__o9j0bk3mocyap0jsh2eyam2gf4k", "name": "ドラゴンボールレジェンズ攻略まとめ隊", "url": "https://xn--o9j0bk3mocyap0jsh2eyam2gf4k.net/feed"},
    {"id": "xn__o9j0bk9175aoqh34d491f", "name": "ドールズフロントライン 攻略まとめ隊", "url": "https://xn--o9j0bk9175aoqh34d491f.com/feed"},
    {"id": "xn__zcka9bza7pybd5118hco4a", "name": "ハースストーン攻略まとめ速報", "url": "https://xn--zcka9bza7pybd5118hco4a.com/feed"},
    {"id": "xn__o9j0bk9l8cn4i9byj2jo863c0ssb", "name": "シャドウバース攻略まとめ隊", "url": "https://xn--o9j0bk9l8cn4i9byj2jo863c0ssb.com/feed"},
    {"id": "xn__o9j0bk1rwe8bvh", "name": "プリコネ攻略まとめ隊", "url": "https://xn--o9j0bk1rwe8bvh.com/feed"},
    {"id": "xn__o9j0bk5t7exbwe", "name": "スマブラ攻略まとめ隊", "url": "https://xn--o9j0bk5t7exbwe.com/feed"},
    {"id": "xn__fgo_gh8fn72e", "name": "FGO攻略まとめ隊", "url": "https://xn--fgo-gh8fn72e.com/feed"},
    {"id": "gamerstand_1", "name": "アークナイツ攻略まとめGS", "url": "https://xn--ccke6azf2a21a.gamerstand.net/feed"},
    {"id": "gamerstand_2", "name": "ドラクエウォーク攻略まとめ GS", "url": "https://xn--gckdevd5myivf.gamerstand.net/feed"},
    {"id": "gamerstand_3", "name": "スパロボDD攻略まとめ GAMER STAND", "url": "https://gamerstand.net/srw-dd/feed"},
    {"id": "gamerstand_4", "name": "ランモバ攻略まとめGS", "url": "https://xn--ndk9au4b.gamerstand.net/feed"},
    {"id": "gamerstand_5", "name": "FFBE幻影戦争 攻略まとめGS", "url": "https://ffbe-wotv.gamerstand.net/feed"},
    {"id": "gamerstand_6", "name": "デュエプレ攻略まとめ GS", "url": "https://xn--ick1c6c0a.gamerstand.net/feed"},
    {"id": "draquewalk", "name": "ドラクエウォーク速報", "url": "https://draquewalk.blog.fc2.com/?xml"},
    {"id": "xn__fgo_yb4b8dta56dif", "name": "FGOまとめマン速報", "url": "https://xn--fgo-yb4b8dta56dif.xyz/feed/"},
    {"id": "fgonovum", "name": "FGOノウムカルデア攻略速報", "url": "https://fgonovum.com/feed/"},
    {"id": "pawapuro", "name": "パワ速@プロスピA攻略まとめ", "url": "http://pawapuro.xyz/?feed=rss2"},
    {"id": "hachinai", "name": "ハチナイ速報＠八月のシンデレラナイン攻略まとめ", "url": "http://hachinai.net/?feed=rss2"},
    {"id": "pokemongo_kouryakumatome", "name": "ポケモンGO攻略まとめ速報！！", "url": "http://pokemongo-kouryakumatome.net/index.rdf"},
    {"id": "more_gamer_2", "name": "仁王まとめ速報｜仁王2", "url": "http://nioh.more-gamer.com/feed"},
    {"id": "butumori", "name": "どうぶつの森まとめ速報", "url": "http://butumori.com/index.rdf"},
    {"id": "dq11switch", "name": "ドラクエ大好きまとめ速報!", "url": "http://dq11switch.com//index.rdf"},
    {"id": "sinkain", "name": "原神まとめ究極とめ", "url": "https://sinkain.net/?feed=rss2"},
    {"id": "fate_go_guidebook", "name": "Fate/GO攻略ガイドブック", "url": "http://fate-go-guidebook.blog.jp/index.rdf"},
    {"id": "amage_matome", "name": "アマゲーまとめ", "url": "http://www.amage-matome.com/index.rdf"},
    {"id": "ps5sokunews", "name": "PS5速報", "url": "https://ps5sokunews.com//?feed=rss2"},
    {"id": "n_switch", "name": "NS-NEWS ニンテンドースイッチまとめ速報", "url": "https://n-switch.com/feed/"},
    {"id": "genshin", "name": "原神攻略情報まとめ ～旅人チャンネル～", "url": "https://genshin.blog.jp/index.rdf"},
    {"id": "gurumiku_sokuhou", "name": "グルミク速報", "url": "https://gurumiku-sokuhou.xyz/feed/"},
    {"id": "paimonmatome", "name": "パイモンまとめ速報　ー原神まとめー", "url": "https://paimonmatome.com/feed"},
    {"id": "dragonquestwalk", "name": "ウマ娘まとめ超速報！", "url": "http://dragonquestwalk.blog.jp/index.rdf"},
    {"id": "chodq10", "name": "ドラクエ10攻略まとめ　〜超DQ10速報〜", "url": "http://chodq10.blog.jp/index.rdf"},
    {"id": "mhrmatome", "name": "モンハンライズまとめG", "url": "https://mhrmatome.com/feed"},
    {"id": "mhw", "name": "モンハンまとめ速報【モンハンライズ攻略】", "url": "http://mhw.2chblog.jp/index.rdf"},
    {"id": "xn___fate_grandorder_794ovb07b7ht176ef78bjy3dxb0g", "name": "Fate-Grand Order攻略速報 | FGO攻略・まとめ", "url": "http://xn---fate-grandorder-794ovb07b7ht176ef78bjy3dxb0g.com/index.rdf"},
    {"id": "fgochaldeas", "name": "FGOまとめ　カルデア速報", "url": "http://fgochaldeas.com/index.rdf"},
    {"id": "gamejksokuhou", "name": "ゲーム実況者速報", "url": "http://gamejksokuhou.com/index.rdf"},
    {"id": "ps_vr", "name": "PSVR速報", "url": "http://ps-vr.blog.jp/index.rdf"},
    {"id": "estalucia", "name": "グラブルまとめ！いすたるしあ通信", "url": "https://estalucia.com/feed"},
    {"id": "smashbros_matome", "name": "スマブラSPまとめ速報", "url": "http://smashbros-matome.com/index.rdf"},
    {"id": "xn__gckdevd5myivf", "name": "すらりんch - ドラクエウォークまとめ速報", "url": "http://xn--gckdevd5myivf.site/index.rdf"},
    {"id": "pokemonunite", "name": "ポケモンユナイト作戦会議", "url": "https://pokemonunite.blog.fc2.com/?xml"},
    {"id": "madoyuka", "name": "ゲーハーの窓", "url": "http://blog.livedoor.jp/madoyuka//index.rdf"},
    {"id": "db_gohan", "name": "アルティメット速報", "url": "https://db-gohan.blog.jp/index.rdf"},
    {"id": "ntgsoku", "name": "ネトゲ攻略速報", "url": "http://ntgsoku.com/index.rdf"},
    {"id": "opt_matome", "name": "【大陸の覇者】オクトパストラベラー攻略まとめ速報！", "url": "http://opt-matome.xyz/index.rdf"},
    {"id": "dragonquest_matomesoku", "name": "ドラゴンクエストウォークまとめ速報", "url": "http://dragonquest-matomesoku.blog.jp/index.rdf"},
    {"id": "monsterhunter_rise", "name": "モンスターハンターライズまとめ速報", "url": "http://monsterhunter-rise.blog.jp/index.rdf"},
    {"id": "gamehig", "name": "ウマ娘うまだっち速報", "url": "http://gamehig.com/index.rdf"},
    {"id": "genshin_daruma", "name": "原神攻略まとめ＠むじだる速報", "url": "https://genshin-daruma.com/feed"},
    {"id": "uma_log", "name": "うまろぐ", "url": "https://uma-log.net/feed/"},
    {"id": "mari_soku", "name": "まりえる速報", "url": "https://mari-soku.com/feed/"},
    {"id": "lv1000", "name": "ポケモンSVまとめぇる", "url": "https://pokemon.lv1000.net/feed/"},
    {"id": "yuzu2323gin", "name": "モンハン総合ブログ", "url": "https://yuzu2323gin.livedoor.blog/index.rdf"},
    {"id": "gadjeizu", "name": "ガジェットの泉ちゃんねる", "url": "https://gadjeizu.net/?feed=rss2"},
    {"id": "nintendoevery", "name": "ニンテンドーエブリー", "url": "https://nintendoevery.com/feed/"},
    {"id": "2chomeseikei", "name": "鋼嵐-メタルストーム-攻略速報@まとめ2丁目", "url": "https://metalstorm.2chomeseikei.jp/feed"},
    {"id": "matome_gamers_1", "name": "Gジェネエターナルまとめ速報攻略ゲーマーズ！", "url": "https://gundam.matome-gamers.com/feed"},
    {"id": "df_browser_games", "name": "ブラウザゲーム速報", "url": "https://df-browser-games.com/?xml"},
    {"id": "matome_gamers_2", "name": "ジョジョの奇妙な冒険オラオラオーバードライブ（オラドラ）まとめ速報攻略ゲーマーズ！", "url": "https://jojo.matome-gamers.com/feed"},
    {"id": "gamezu", "name": "ゲーマー速報！", "url": "https://gamezu.blog.jp/index.rdf"},
    {"id": "morikinoko", "name": "SS 森きのこ！", "url": "http://morikinoko.com/index.rdf"},
    {"id": "elephant", "name": "エレファント速報：SSまとめブログ", "url": "http://elephant.2chblog.jp/index.rdf"},
    {"id": "horahorazoon", "name": "ホライゾーン - SSまとめサイト", "url": "http://horahorazoon.blog134.fc2.com/?xml"},
    {"id": "potittoss", "name": "ポチッとSS!! SSまとめ", "url": "http://potittoss.blog.jp/index.rdf"},
    {"id": "ayamevip", "name": "あやめ速報-SSまとめ-", "url": "http://ayamevip.com/index.rdf"},
    {"id": "kokon55", "name": "SS古今東西", "url": "http://blog.livedoor.jp/kokon55/index.rdf"},
    {"id": "ssbiyori", "name": "SSびより", "url": "http://ssbiyori.blog.fc2.com/?xml"},
    {"id": "ssimas72", "name": "プロデューサーさんっ！SSですよ、SS！-アイマスSSまとめ", "url": "http://ssimas72.blog.jp/index.rdf"},
    {"id": "ss_navi", "name": "SSなび", "url": "http://ss-navi.com/?xml"},
    {"id": "ssimas", "name": "全ては跡地。", "url": "http://ssimas.blog.fc2.com/?xml"},
    {"id": "h616r825", "name": "えすえすゲー速報", "url": "http://blog.livedoor.jp/h616r825/index.rdf"},
    {"id": "esusokuhou", "name": "SSまにあっくす！", "url": "http://esusokuhou.blog.jp/index.rdf"},
    {"id": "grasoku", "name": "ぐら速 -声優まとめ速報-", "url": "http://grasoku.com/index.rdf"},
    {"id": "otakumix", "name": "おたくみくす　声優まとめ", "url": "http://otakumix.doorblog.jp/index.rdf"},
    {"id": "aniran", "name": "声優速報", "url": "http://aniran.blog.jp/index.rdf"},
    {"id": "moeillust", "name": "萌えイラストを描きたい!!", "url": "http://moeillust.net/?xml"},
    {"id": "masked", "name": "ヒーローNEWS", "url": "http://masked.blog.jp/index.rdf"},
    {"id": "chokkanteki", "name": "かいちょく", "url": "https://chokkanteki.com/feed/"},
    {"id": "anicai", "name": "海外の反応  –  あにかい | アニメ・ゲーム海外の反応まとめ", "url": "https://anicai.jp/archives/category/kaigaihanou/feed"},
    {"id": "kokuani", "name": "国際的アニメ日常", "url": "http://kokuani.blog.jp/index.rdf"},
    {"id": "lolninja", "name": "海外の反応 | LOL忍者", "url": "https://lolninja.net/category/%e6%b5%b7%e5%a4%96%e3%81%ae%e5%8f%8d%e5%bf%9c/feed/"},
    {"id": "uminomukoudeha", "name": "海の向こうでは", "url": "http://uminomukoudeha.site/index.rdf"},
    {"id": "eigotoka", "name": "eigotoka 　〜海外スレ翻訳所〜", "url": "https://eigotoka.com/feed"},
    {"id": "cough", "name": "ほらみぃ", "url": "http://cough.cocolog-nifty.com/blog/rss.xml"},
    {"id": "kakugeblog", "name": "格ゲーブログ（仮） - 海外の反応", "url": "http://kakugeblog.blog.jp/archives/cat_1131921.xml"},
    {"id": "kagerou", "name": "海外の反応で英語の勉強", "url": "http://www.kagerou.biz/index.rdf"},
    {"id": "watamotetrans", "name": "蠱惑の壺 | 漫画・アニメ海外の反応まとめ", "url": "http://watamotetrans.livedoor.blog/index.rdf"},
    {"id": "grewgrehrg", "name": "ミク廃！！", "url": "https://grewgrehrg.blog.fc2.com/?xml"},
    {"id": "kaigaichan", "name": "かいがいchan", "url": "https://kaigaichan.net/feed/rss"},
    {"id": "game_honyaku", "name": "ゲームほんやくコンニャク", "url": "http://game-honyaku.com/feed/"},
    {"id": "kamenrider2", "name": "仮面ライダーまとめ２号", "url": "http://kamenrider2.net/feed"},
    {"id": "koebuta", "name": "声豚速報", "url": "http://koebuta.ldblog.jp/index.rdf"},
    {"id": "hatenablog", "name": "アニメリアクト", "url": "https://animereact.hatenablog.com/rss"},
]
