# scripts/feeds.py

FEEDS = [
    {"id": "1", "name": "SS 森きのこ！", "url": "http://morikinoko.com/index.rdf"},
    {"id": "2", "name": "【2ch】コピペ情報局", "url": "http://news.2chblog.jp/index.rdf"},
    {"id": "3", "name": "哲学ニュースnwk", "url": "http://blog.livedoor.jp/nwknews/index.rdf"},
    {"id": "4", "name": "【2ch】ニュー速クオリティ", "url": "http://news4vip.livedoor.biz/index.rdf"},
    {"id": "5", "name": "まとめたニュース", "url": "http://matometanews.com/index.rdf"},
    {"id": "6", "name": "常識的に考えた", "url": "http://blog.livedoor.jp/jyoushiki43/index.rdf"},
    {"id": "7", "name": "暇人＼(^o^)／速報", "url": "http://himasoku.com/index.rdf"},
    {"id": "8", "name": "痛いニュース(ﾉ∀`)", "url": "http://blog.livedoor.jp/dqnplus/index.rdf"},
    {"id": "9", "name": "エクサワロス | ニュースまとめサイト", "url": "http://exawarosu.net/index.rdf"},
    {"id": "10", "name": "ゆめ痛 -NEWS ALERT-", "url": "http://blog.livedoor.jp/yu_ps13/index.rdf"},
    {"id": "11", "name": "政経ch", "url": "http://fxya.blog129.fc2.com/?xml"},
    {"id": "12", "name": "ちゃんねるZ", "url": "http://channelz.blog.fc2.com/?xml"},
    {"id": "13", "name": "みそパンNEWS", "url": "http://blog.livedoor.jp/misopan_news/index.rdf"},
    {"id": "14", "name": "ゴタゴタシタニュース", "url": "http://blog.livedoor.jp/gotagotashita/index.rdf"},
    {"id": "15", "name": "ニュース30over", "url": "http://www.news30over.com/index.rdf"},
    {"id": "16", "name": "ガハろぐNewsヽ(･ω･)/ｽﾞｺｰ", "url": "http://blog.livedoor.jp/funs/index.rdf"},
    {"id": "17", "name": "流速VIP", "url": "http://ryusoku.com/index.rdf"},
    {"id": "18", "name": "黒マッチョニュース", "url": "http://kuromacyo.livedoor.biz/index.rdf"},
    {"id": "19", "name": "笑　韓　ブログ", "url": "http://blog.livedoor.jp/warakan2ch/index.rdf"},
    {"id": "20", "name": "(*ﾟ∀ﾟ)ゞカガクニュース隊", "url": "http://www.scienceplus2ch.com/index.rdf"},
    {"id": "21", "name": "VIPPERな俺", "url": "http://blog.livedoor.jp/news23vip/index.rdf"},
    {"id": "22", "name": "何でもありんす", "url": "http://milfled.seesaa.net/index.rdf"},
    {"id": "23", "name": "ぶる速-VIP", "url": "http://burusoku-vip.com/index.rdf"},
    {"id": "24", "name": "ハムスター速報", "url": "http://hamusoku.com/index.rdf"},
    {"id": "25", "name": "カナ速", "url": "http://kanasoku.info/index.rdf"},
    {"id": "26", "name": "ゴールデンタイムズ", "url": "http://blog.livedoor.jp/goldennews/index.rdf"},
    {"id": "27", "name": "働くモノニュース : 人生VIP職人ブログwww", "url": "http://workingnews.blog117.fc2.com/?xml"},
    {"id": "28", "name": "デジタルニューススレッド", "url": "http://digital-thread.com/index.rdf"},
    {"id": "29", "name": "カオスちゃんねる", "url": "http://chaos2ch.com/index.rdf"},
    {"id": "30", "name": "ジュピ速", "url": "http://lamsect.blog112.fc2.com/?xml"},
    {"id": "31", "name": "キニ速", "url": "http://blog.livedoor.jp/kinisoku/index.rdf"},
    {"id": "32", "name": "ワラノート", "url": "http://waranote.livedoor.biz/index.rdf"},
    {"id": "33", "name": "情弱VIP2ちゃんねる", "url": "http://blog.livedoor.jp/joujakuvip2ch/index.rdf"},
    {"id": "34", "name": "もみあげチャ～シュ～", "url": "http://michaelsan.livedoor.biz/index.rdf"},
    {"id": "35", "name": "はれぞう", "url": "http://blog.livedoor.jp/darkm/index.rdf"},
    {"id": "36", "name": "サッカーミックスジュース", "url": "http://blog.livedoor.jp/soccerkusoyarou/index.rdf"},
    {"id": "37", "name": "アルファルファモザイク", "url": "http://alfalfalfa.com/index.rdf"},
    {"id": "38", "name": "ライフハックちゃんねる弐式", "url": "http://lifehack2ch.livedoor.biz/index.rdf"},
    {"id": "39", "name": "子育てちゃんねる", "url": "http://kosodatech.blog133.fc2.com/?xml"},
    {"id": "40", "name": "結婚・恋愛ニュースぷらす", "url": "http://blog.livedoor.jp/kekkongo/index.rdf"},
    {"id": "41", "name": "わんこーる速報！", "url": "http://onecall2ch.com/index.rdf"},
    {"id": "42", "name": "うるるんロギー", "url": "http://rakusyasa.blog41.fc2.com/?xml"},
    {"id": "43", "name": "ろぼ速VIP", "url": "http://blog.livedoor.jp/robosoku/index.rdf"},
    {"id": "44", "name": "はちま起稿", "url": "http://blog.esuteru.com/index.rdf"},
    {"id": "45", "name": "オレ的ゲーム速報＠刃", "url": "http://jin115.com/index.rdf"},
    {"id": "46", "name": "続・妄想的日常", "url": "http://mousouteki.blog53.fc2.com/?xml"},
    {"id": "47", "name": "2chコピペ保存道場", "url": "http://2chcopipe.com/index.rdf"},
    {"id": "48", "name": "いろんな人ガイル", "url": "http://mogeonna.blog.fc2.com/?xml"},
    {"id": "49", "name": "オタク.com", "url": "http://otakomu.jp/index.rdf"},
    {"id": "50", "name": "ヒロイモノ中毒", "url": "http://cherio199.blog120.fc2.com/?xml"},
    {"id": "51", "name": "ほんわかMkⅡ", "url": "http://honwaka2ch.livedoor.biz/index.rdf"},
    {"id": "52", "name": "なんじぇいスタジアム＠なんJまとめ", "url": "http://blog.livedoor.jp/nanjstu/index.rdf"},
    {"id": "53", "name": "すかっとしていきませんか | sk2ch", "url": "http://sk2ch.net/feed"},
    {"id": "54", "name": "大艦巨砲主義！", "url": "http://military38.com/index.rdf"},
    {"id": "55", "name": "保守速報", "url": "http://hosyusokuhou.jp/index.rdf"},
    {"id": "56", "name": "NEWSまとめもりー｜2chまとめブログ", "url": "http://www.akb48matomemory.com/index.rdf"},
    {"id": "57", "name": "うしみつ-2ch怖い話まとめ-", "url": "http://usi32.com/index.rdf"},
    {"id": "58", "name": "GUNDAM.LOG｜ガンダムまとめブログ", "url": "http://gundamlog.com/index.rdf"},
    {"id": "59", "name": "ダイエット速報＠2ちゃんねる", "url": "http://blog.livedoor.jp/diet2channel/index.rdf"},
    {"id": "60", "name": "不思議.net", "url": "http://world-fusigi.net/index.rdf"},
    {"id": "61", "name": "オーバージョイド！　　2chまとめサイト", "url": "http://overjoyed.info/feed"},
    {"id": "62", "name": "超マンガ速報", "url": "http://chomanga.org/feed"},
    {"id": "63", "name": "VIPPER速報", "url": "http://vippers.jp/index.rdf"},
    {"id": "64", "name": "日刊やきう速報＠野球まとめ", "url": "http://blog.livedoor.jp/yakiusoku/index.rdf"},
    {"id": "65", "name": "浮気ちゃんねる", "url": "http://uwakich.com/index.rdf"},
    {"id": "66", "name": "ラビット速報", "url": "http://rabitsokuhou.2chblog.jp/index.rdf"},
    {"id": "67", "name": "キチガイママまとめ保管庫", "url": "http://www.kitimama-matome.net/index.rdf"},
    {"id": "68", "name": "鬼女まとめログ｜生活2chまとめブログ", "url": "http://www.kijomatomelog.com/index.rdf"},
    {"id": "69", "name": "F1情報通", "url": "http://f1jouhou2.blog.fc2.com/?xml"},
    {"id": "70", "name": "稲妻速報", "url": "http://inazumanews2.com/index.rdf"},
    {"id": "71", "name": "カイカイ反応通信", "url": "http://blog.livedoor.jp/kaikaihanno/index.rdf"},
    {"id": "72", "name": "正義の見方", "url": "https://www.honmotakeshi.com/feed"},
    {"id": "73", "name": "最強ジャンプ放送局", "url": "http://www.saikyo-jump.com/index.rdf"},
    {"id": "74", "name": "竜速（りゅうそく）", "url": "http://blog.livedoor.jp/bbyakyu/index.rdf"},
    {"id": "75", "name": "あらまめ2ch", "url": "http://aramame.net/feed"},
    {"id": "76", "name": "なんJ（まとめては）いかんのか？", "url": "http://blog.livedoor.jp/livejupiter2/index.rdf"},
    {"id": "77", "name": "ポリー速報", "url": "http://blog.livedoor.jp/fightersmatome/index.rdf"},
    {"id": "78", "name": "芸能かめはめ波", "url": "http://geinoukame.blog.fc2.com/?xml"},
    {"id": "79", "name": "ジャンプ速報", "url": "http://jumpsokuhou.com/index.rdf"},
    {"id": "80", "name": "まとめロッテ！", "url": "http://matomelotte.com/index.rdf"},
    {"id": "81", "name": "ガンダムまとめ速報", "url": "http://g-matome.com/index.rdf"},
    {"id": "82", "name": "GOSSIP速報", "url": "http://gossip1.net/index.rdf"},
    {"id": "83", "name": "サカラボ | サッカーまとめ速報", "url": "http://sakarabo.blog.jp/index.rdf"},
    {"id": "84", "name": "キスログ", "url": "http://kisslog2.com/index.rdf"},
    {"id": "85", "name": "キムチ速報", "url": "http://kimsoku.com/index.rdf"},
    {"id": "86", "name": "カルチョまとめブログ", "url": "http://www.calciomatome.net/index.rdf"},
    {"id": "87", "name": "まにゅそく 2chまとめニュース速報VIP", "url": "http://2ch-matomenews.com/feed"},
    {"id": "88", "name": "はーとログ", "url": "http://blog.livedoor.jp/love120331/index.rdf"},
    {"id": "89", "name": "素敵な鬼女様", "url": "http://sutekinakijo.com/index.rdf"},
    {"id": "90", "name": "やみ速@なんJ西武まとめ", "url": "https://lions-matome.com/archives/category/%E8%A5%BF%E6%AD%A6/feed"},
    {"id": "91", "name": "2ch東方スレ観測所", "url": "http://blog.livedoor.jp/coleblog/index.rdf"},
    {"id": "92", "name": "NO FOOTY NO LIFE", "url": "http://nofootynolife.net/?xml"},
    {"id": "93", "name": "1000mg", "url": "http://1000mg.jp/feed"},
    {"id": "94", "name": "気団まとめ-噫無情-｜嫁・浮気・メシマズ", "url": "http://kidan-m.com/index.rdf"},
    {"id": "95", "name": "気団談", "url": "http://blog.livedoor.jp/kidandan/index.rdf"},
    {"id": "96", "name": "鬼嫁日記〜2ch生活まとめ〜", "url": "http://oniyomediary.com/index.rdf"},
    {"id": "97", "name": "【海外の反応】　パンドラの憂鬱", "url": "http://kaigainohannoublog.blog55.fc2.com/?xml"},
    {"id": "98", "name": "かんむす！-艦隊これくしょんまとめブログ-", "url": "http://kanmsu.com/feed"},
    {"id": "99", "name": "海外の反応　お隣速報", "url": "https://www.otonarisoku.com/feed"},
    {"id": "100", "name": "フットボール速報", "url": "http://football-2ch.com/index.rdf"},
    {"id": "101", "name": "ネギ速", "url": "http://www.negisoku.com/index.rdf"},
    {"id": "102", "name": "軍事・ミリタリー速報☆彡", "url": "http://blog.livedoor.jp/corez18c24-mili777/index.rdf"},
    {"id": "103", "name": "鷹速@ホークスまとめブログ", "url": "http://blog.livedoor.jp/hawksmatome/index.rdf"},
    {"id": "104", "name": "SAMURAI Footballers", "url": "http://samuraisoccer.doorblog.jp/index.rdf"},
    {"id": "105", "name": "ニンテンドースイッチ速報", "url": "http://xn--eckybzahmsm43ab5g5336c9iug.com/feed"},
    {"id": "106", "name": "モナニュース", "url": "http://mona-news.com/index.rdf"},
    {"id": "107", "name": "２ちゃんを斬る！", "url": "http://kiru2ch.com/index.rdf"},
    {"id": "108", "name": "鬼女速", "url": "http://kijosoku.com/index.rdf"},
    {"id": "109", "name": "２ろぐちゃんねる", "url": "https://2logch.com/feed"},
    {"id": "110", "name": "海外サッカー日本人選手速報 WORLD SAMURAI", "url": "http://world-samurai.com/index.rdf"},
    {"id": "111", "name": "オトコの本音｜生活2chまとめブログ", "url": "http://www.otoko-honne.com/index.rdf"},
    {"id": "112", "name": "日本人＿難民。～2ｃｈ読み物まとめ～", "url": "http://nihonjinnanmin.com/index.rdf"},
    {"id": "113", "name": "どんぐりこ - 海外の反応", "url": "http://dng65.com/?xml"},
    {"id": "114", "name": "ネタめし.com", "url": "http://www.netamesi.com/index.rdf"},
    {"id": "115", "name": "芸能人の気になる噂", "url": "http://blog.livedoor.jp/uwasainfo/index.rdf"},
    {"id": "116", "name": "もばます！", "url": "http://imas-cg.net/index.rdf"},
    {"id": "117", "name": "地下帝国-AKB48まとめ", "url": "http://chikakb.ldblog.jp/index.rdf"},
    {"id": "118", "name": "ってなんじぇですかー", "url": "http://blog.livedoor.jp/bmaysu/index.rdf"},
    {"id": "119", "name": "2ch名人", "url": "http://i2chmeijin.blog.fc2.com/?xml"},
    {"id": "120", "name": "まとめでぃあ", "url": "http://totalmatomedia.blog.fc2.com/?xml"},
    {"id": "121", "name": "カンダタ速報", "url": "http://kandatasokuho.blog.fc2.com/?xml"},
    {"id": "122", "name": "ばいくちゃんねる", "url": "https://www2.bikechannel.info/feed"},
    {"id": "123", "name": "SWITCH速報", "url": "http://switchsoku.com/feed"},
    {"id": "124", "name": "どうぶつちゃんねる", "url": "http://animalch.net/index.rdf"},
    {"id": "125", "name": "劇訳表示。", "url": "http://www.gekiyaku.com/index.rdf"},
    {"id": "126", "name": "チェックメイト | 2chまとめブログ", "url": "http://checkmate-blog.com/feed"},
    {"id": "127", "name": "アニはつ -アニメ発信場-", "url": "http://anihatsu.com/index.rdf"},
    {"id": "128", "name": "けもちゃん", "url": "http://kemochan.com/feed"},
    {"id": "129", "name": "スロパチ乱舞", "url": "http://slotmania222.com/index.rdf"},
    {"id": "130", "name": "おうち速報", "url": "http://ouchinews.doorblog.jp/index.rdf"},
    {"id": "131", "name": "オンナの本音｜2ch生活まとめ-鬼女ライフハック", "url": "http://www.kijolifehack.com/index.rdf"},
    {"id": "132", "name": "AKB48情報まとめたった", "url": "http://www.akb48mt.com/index.rdf"},
    {"id": "133", "name": "­海外反応　キキミミ", "url": "http://xxxkikimimixxx.blog.fc2.com/?xml"},
    {"id": "134", "name": "暇は無味無臭の劇薬", "url": "http://blog.livedoor.jp/drazuli/index.rdf"},
    {"id": "135", "name": "マイカー速報", "url": "http://mycarsoku.com/index.rdf"},
    {"id": "136", "name": "まとめニュースちゃんねるぷらす", "url": "http://blog.livedoor.jp/ainbekker-news2/index.rdf"},
    {"id": "137", "name": "すらるど - 海外の反応", "url": "http://sow.blog.jp/index.rdf"},
    {"id": "138", "name": "ラブライブ！まとめちゃんねる！！", "url": "http://lovelivematocha.com/?xml"},
    {"id": "139", "name": "台湾の反応ブログ", "url": "http://www.taiwannohannou.com/index.rdf"},
    {"id": "140", "name": "なんJ 野球をまとめてみたよ", "url": "http://bb.doorblog.jp/index.rdf"},
    {"id": "141", "name": "ニッコリン", "url": "http://niccorin.com/index.rdf"},
    {"id": "142", "name": "V系まとめ速報", "url": "http://visual-matome.com/index.rdf"},
    {"id": "143", "name": "watch＠２ちゃんねる", "url": "http://www.watch2chan.com/index.rdf"},
    {"id": "144", "name": "FF14ひかせん速報", "url": "https://ff14hikasensokuhou.com/?xml"},
    {"id": "145", "name": "（　｀ハ´）中国の反応ブログ", "url": "http://asiareaction.blog.fc2.com/?xml"},
    {"id": "146", "name": "蹴球まとめちゃんねる", "url": "http://football2channel.blog.fc2.com/?xml"},
    {"id": "147", "name": "ウォッチちゃんねる", "url": "http://watch-times.com/feed"},
    {"id": "148", "name": "海外の反応 ディミヌート", "url": "https://www.dimikai.com/?xml"},
    {"id": "149", "name": "海外の万国反応記＠海外の反応", "url": "http://www.all-nationz.com/index.rdf"},
    {"id": "150", "name": "SS古今東西", "url": "http://blog.livedoor.jp/kokon55/index.rdf"},
    {"id": "151", "name": "SSびより", "url": "http://ssbiyori.blog.fc2.com/?xml"},
    {"id": "152", "name": "ガラパゴスジャパン - 海外の反応", "url": "http://galapagosjapan.blog.fc2.com/?xml"},
    {"id": "153", "name": "チャルバンを翻訳してみた【海外の反応】", "url": "http://tchal.net/index.rdf"},
    {"id": "154", "name": "げぇ速", "url": "http://ge-soku.com/index.rdf"},
    {"id": "155", "name": "NMB48まとめスピリッツ", "url": "http://nmb48-mtm.com/index.rdf"},
    {"id": "156", "name": "じゃぽにか反応帳", "url": "http://www.japohan.net/feed"},
    {"id": "157", "name": "進撃の巨人ちゃんねる", "url": "http://shingekikyojin.net/index.rdf"},
    {"id": "158", "name": "海外の反応 | 海外報道翻訳所", "url": "http://foreignnews.biz/archives/cat_382414.xml"},
    {"id": "159", "name": "【海外の反応】タメナル", "url": "http://tamenal.com/feed"},
    {"id": "160", "name": "PS4ProNEWS", "url": "http://psneolog.com/feed"},
    {"id": "161", "name": "中国四千年の反応！ 海外の反応ブログ", "url": "http://chinareaction.com/?xml"},
    {"id": "162", "name": "海外の反応 | 翻訳部", "url": "http://kaigainohannou.info/feed/"},
    {"id": "163", "name": "サッカーレボリューション", "url": "http://blog.livedoor.jp/soccerrevolution/index.rdf"},
    {"id": "164", "name": "どうぶつの森 みんなでポケットキャンプ (ポケ森)", "url": "http://xn--p8j0cnw2b2487d.jp/feed"},
    {"id": "165", "name": "ブンデスリーガ　ドイツの反応 Ich liebe Fussball!!", "url": "http://ichliebefussball.net/?xml"},
    {"id": "166", "name": "NEWSぽけまとめーる", "url": "http://pokemon-goh.doorblog.jp/index.rdf"},
    {"id": "167", "name": "スコールちゃんねる｜２ちゃんまとめブログ", "url": "http://squallchannel.doorblog.jp/index.rdf"},
    {"id": "168", "name": "なんJクエスト", "url": "http://inutomo11.com/index.rdf"},
    {"id": "169", "name": "はーとらいふ -出会い・子育て・生活系まとめ-", "url": "http://heartlife-matome.com/index.rdf"},
    {"id": "170", "name": "マジ卍速報", "url": "http://majimanjisokuhou.com/index.rdf"},
    {"id": "171", "name": "がーるずレポート - ガールズちゃんねるまとめブログ", "url": "http://girlsreport.net/index.rdf"},
    {"id": "172", "name": "無題のドキュメント", "url": "http://www.mudainodocument.com/index.rdf"},
    {"id": "173", "name": "ふぇー速", "url": "http://fesoku.net/index.rdf"},
    {"id": "174", "name": "億ったー", "url": "http://www.okutta.net/index.rdf"},
    {"id": "175", "name": "鬼女日記 -鬼女・修羅場・キチママ系まとめ-", "url": "http://kijonikki.net/index.rdf"},
    {"id": "176", "name": "鬼女タウン", "url": "http://kijyotown.net/index.rdf"},
    {"id": "177", "name": "鬼女乱舞-キチママ・鬼女・修羅場系まとめ-", "url": "http://kijorabu.com/index.rdf"},
    {"id": "178", "name": "鬼女まとめちゃんねる｜生活2chまとめブログ", "url": "http://kijyomatome-ch.com/index.rdf"},
    {"id": "179", "name": "鬼女の生活｜2ch修羅場まとめブログ", "url": "http://kijyokatu.com/index.rdf"},
    {"id": "180", "name": "鬼女はみた -修羅場・恋愛・育児系まとめサイト-", "url": "http://kijyomita.com/index.rdf"},
    {"id": "181", "name": "鬼女の浮気速報｜ 2ch鬼女・キチママ・修羅場まとめ", "url": "http://kizyonouwaki.com/index.rdf"},
    {"id": "182", "name": "鬼女のつぶやき〜2ch鬼女・キチママ・生活まとめ〜", "url": "http://kijyotsubu.net/index.rdf"},
    {"id": "183", "name": "鬼女の宅配便 - 修羅場・浮気からほのぼの系まで[まとめサイト]", "url": "http://kijonotakuhaibin.com/index.rdf"},
    {"id": "184", "name": "鬼女の井戸端会議-鬼女、キチママ、修羅場、生活まとめ-", "url": "http://kijyokaigi.com/index.rdf"},
    {"id": "185", "name": "長編にちゃんまとめ　修羅場・浮気", "url": "http://2chmatome.net/index.rdf"},
    {"id": "186", "name": "釣りまとめ速報", "url": "http://tsurimatome.com/index.rdf"},
    {"id": "187", "name": "超・マンガ速報", "url": "http://chomangasokuho.blog.jp/index.rdf"},
    {"id": "188", "name": "質問ある？まとめ速報", "url": "http://shitsumon-aru.net/index.rdf"},
    {"id": "189", "name": "芸能人ニュース速報", "url": "http://blog.livedoor.jp/sky_wing2010-geinou/index.rdf"},
    {"id": "190", "name": "芸能ネタはこれだけでおｋ", "url": "http://koredakedeok.blog.jp/index.rdf"},
    {"id": "191", "name": "爆NEWゲーム速報", "url": "http://bnewg.sokuho.org/index.rdf"},
    {"id": "192", "name": "気団ログ", "url": "http://kidanlog.com/feed"},
    {"id": "193", "name": "気になる芸能まとめ", "url": "http://kininaru-geinou-m.blog.jp/index.rdf"},
    {"id": "194", "name": "気になった生活スレまとめ", "url": "http://kininatta2chmatome.doorblog.jp/index.rdf"},
    {"id": "195", "name": "日向坂46まとめ速報", "url": "http://hiraganakeyaki.blog.jp/index.rdf"},
    {"id": "196", "name": "政経ワロスまとめニュース♪", "url": "http://seikeidouga.blog.jp/index.rdf"},
    {"id": "197", "name": "拝啓、鬼女様", "url": "http://polite-kijyo.net/index.rdf"},
    {"id": "198", "name": "情報屋さん。", "url": "http://jyouhouya3.net/feed"},
    {"id": "199", "name": "恋愛速報｜2chまとめサイト", "url": "http://www.recosoku.com/index.rdf"},
    {"id": "200", "name": "基地沢直樹-復讐・修羅場・DQN返し【2chスカッとする話まとめ】", "url": "http://kitizawa.com/index.rdf"},
    {"id": "201", "name": "噂の鬼女様", "url": "http://uwasakijo.net/index.rdf"},
    {"id": "202", "name": "2ちゃんねるまとめ 名前はまだない", "url": "http://heekogirl.blog.fc2.com/?xml"},
    {"id": "203", "name": "修羅場ノート-2ch修羅場・復讐まとめ-", "url": "http://shurabanote.com/index.rdf"},
    {"id": "204", "name": "修羅場な話まとめ", "url": "http://shurabana.com/index.rdf"},
    {"id": "205", "name": "修羅場ハザード -復讐・DQN返し・衝撃系まとめ-", "url": "http://syurabahazard.com/index.rdf"},
    {"id": "206", "name": "修羅場ちゃんねる", "url": "http://shurabach.org/index.rdf"},
    {"id": "207", "name": "伝説の鬼女 ～修羅場・キチママ・生活まとめ～", "url": "http://densetsunokijo.net/index.rdf"},
    {"id": "208", "name": "修羅ママ速報", "url": "http://syuramama.com/index.rdf"},
    {"id": "209", "name": "一回は一回です。。｜ 2ch修羅場・復讐まとめ", "url": "http://www.matometemitatta.com/index.rdf"},
    {"id": "210", "name": "今日速2ch", "url": "http://kyousoku.net/index.rdf"},
    {"id": "211", "name": "反日愚国　恨寓瘻", "url": "http://hannichigukoku.info/?xml"},
    {"id": "212", "name": "ラブラドール速報～生活・修羅場・鬼女まとめ～", "url": "http://labradorsokuho.net/index.rdf"},
    {"id": "213", "name": "モンハンワールド2chまとめ速報 - MHW攻略", "url": "http://monhan-mhw.com/index.rdf"},
    {"id": "214", "name": "乃木坂46まとめんばー", "url": "http://nogitweet.com/feed"},
    {"id": "215", "name": "マジワロ速報", "url": "http://maji-w.blog.jp/index.rdf"},
    {"id": "216", "name": "プリンはのみものです。｜にちゃん生活まとめ", "url": "http://purinisdrink.net/index.rdf"},
    {"id": "217", "name": "ヒーローNEWS", "url": "http://masked.blog.jp/index.rdf"},
    {"id": "218", "name": "パチンコ激震速報", "url": "http://gomepachi.com/index.rdf"},
    {"id": "219", "name": "パズ速 -パズドラ情報まとめ-", "url": "http://pazusoku.blog.fc2.com/?xml"},
    {"id": "220", "name": "ハロン棒ch　-競馬まとめ-", "url": "http://haronbouchannel.com/index.rdf"},
    {"id": "221", "name": "セロリのマリネ", "url": "http://celery-marine.net/feed"},
    {"id": "222", "name": "スカッとする修羅場まとめ", "url": "http://sukashuraba.net/index.rdf"},
    {"id": "223", "name": "スカッとじゃぱん", "url": "http://sukattojapan.com/index.rdf"},
    {"id": "224", "name": "ドロドロ速報-鬼女・不倫・浮気・修羅場系まとめ", "url": "http://dorosoku.com/index.rdf"},
    {"id": "225", "name": "スロパチゾーン　パチンコパチスロまとめ", "url": "http://pachislotzone.com/feed"},
    {"id": "226", "name": "ガールズにちゃんまとめ～生活・鬼女～", "url": "http://girls2chmatome.net/index.rdf"},
    {"id": "227", "name": "キチママまとめちゃんねる", "url": "http://kichimama.net/index.rdf"},
    {"id": "228", "name": "ソニック速報", "url": "http://sonicch.com/index.rdf"},
    {"id": "229", "name": "ガールズVIPまとめ", "url": "http://girlsvip-matome.com/index.rdf"},
    {"id": "230", "name": "オルフェンズの仔～～競馬ネタ予想まとめ", "url": "http://orufemorufenz.com/index.rdf"},
    {"id": "231", "name": "オタクニュース", "url": "http://otanew.jp/index.rdf"},
    {"id": "232", "name": "アニゲー速報", "url": "http://www.anige-sokuhouvip.com/?xml"},
    {"id": "233", "name": "もえるあじあ(･∀･)", "url": "https://www.moeruasia.net/index.rdf"},
    {"id": "234", "name": "もりえってぃー", "url": "http://netmorie.com/feed"},
    {"id": "235", "name": "まじかる☆にゅーす", "url": "http://magical-news.blog.jp/index.rdf"},
    {"id": "236", "name": "ぽめぷー速報 ～修羅場・キチママ・生活まとめ～", "url": "http://pomepuu.net/index.rdf"},
    {"id": "237", "name": "ぱる速報", "url": "http://parusoku.com/index.rdf"},
    {"id": "238", "name": "にゃんこ速報～修羅場・キチママ・生活まとめ～", "url": "http://nyankosokuho.com/index.rdf"},
    {"id": "239", "name": "なんJ Dream", "url": "http://blog.livedoor.jp/nanj_dream/index.rdf"},
    {"id": "240", "name": "すまいる(^-^)ぶろぐ", "url": "http://blog.livedoor.jp/whoistrueenemy/index.rdf"},
    {"id": "241", "name": "ねたーる", "url": "http://neta-ru.com/feed"},
    {"id": "242", "name": "げーあにびより｜ゲームやアニメの評価・感想まとめ", "url": "http://gabiyori.com/feed"},
    {"id": "243", "name": "きまぐれ鬼女-鬼女・不倫・浮気・修羅場系まとめ", "url": "http://kimagure-kijyo.com/index.rdf"},
    {"id": "244", "name": "おーるじゃんる", "url": "http://crx7601.com/index.rdf"},
    {"id": "245", "name": "おうまがタイムズ", "url": "http://www.oumaga-times.com/index.rdf"},
    {"id": "246", "name": "mashlife通信", "url": "http://mashlife.doorblog.jp/index.rdf"},
    {"id": "247", "name": "easterEgg", "url": "http://eegg.fun/index.rdf"},
    {"id": "248", "name": "U-1 NEWS", "url": "https://you1news.com/feed"},
    {"id": "249", "name": "NaNじぇい", "url": "http://blog.livedoor.jp/g_ogasawara/index.rdf"},
    {"id": "250", "name": "NPB NEWS@なんJまとめ", "url": "http://npb-news.com/index.rdf"},
    {"id": "251", "name": "HKTまとめもん【HKT48のまとめ】", "url": "http://blog.livedoor.jp/hktmatomemon/index.rdf"},
    {"id": "252", "name": "SSなび", "url": "http://ss-navi.com/?xml"},
    {"id": "253", "name": "FX2ちゃんねる|投資系2chまとめ", "url": "http://www.fx2ch.net/feed"},
    {"id": "254", "name": "MIZUHO no KUNI ≪2ch≫特亜ニュース", "url": "http://mizuhonokuni2ch.com/feed"},
    {"id": "255", "name": "世界の反応", "url": "https://kaigaino.net/feed"},
    {"id": "256", "name": "ムダスレ無き改革", "url": "http://mudasure.com/?xml"},
    {"id": "257", "name": "キチママらいふ－浮気・不倫・修羅場－", "url": "http://kichimama-life.com/index.rdf"},
    {"id": "258", "name": "QQQ(海外の反応)", "url": "http://no-one-no.net/index.rdf"},
    {"id": "259", "name": "NEWSOKU BLOG", "url": "https://newsoku.blog/feed"},
    {"id": "260", "name": "ちわわ速報｜修羅場・鬼女・２ちゃん生活まとめ", "url": "http://chiwasoku.com/index.rdf"},
    {"id": "261", "name": "コノユビ", "url": "http://konoyubitomare.jp/index.rdf"},
    {"id": "262", "name": "ロミオ伝説｜にちゃんまとめ", "url": "http://romeodensetsu.com/index.rdf"},
    {"id": "263", "name": "ラーメン速報｜2chまとめブログ", "url": "http://ramen2ch.com/?xml"},
    {"id": "264", "name": "修羅場まとめの殿堂～離婚・復讐・不倫・浮気まとめ～", "url": "http://shuraba-dendo.com/index.rdf"},
    {"id": "265", "name": "/)；｀ω´)＜国家総動員報", "url": "http://totalwar.doorblog.jp/index.rdf"},
    {"id": "266", "name": "国難にあってもの申す！！", "url": "http://www.kokunanmonomousu.com/index.rdf"},
    {"id": "267", "name": "楽韓Web", "url": "http://rakukan.net/index.rdf"},
    {"id": "268", "name": "大地震・前兆・予言.com", "url": "https://jishin-yogen.com/?xml"},
    {"id": "269", "name": "韓国の反応 | 海外のリアクション", "url": "http://kaigai-otaku.jp/category/korea/feed"},
    {"id": "270", "name": "海外のお前ら　海外の反応", "url": "https://kaigainoomaera.com/?xml"},
    {"id": "271", "name": "稼げるまとめ速報", "url": "http://kasegeru.blog.jp/index.rdf"},
    {"id": "272", "name": "翻訳ちゃんねる | 海外の反応まとめブログ", "url": "http://blog.livedoor.jp/kaigaisoku/index.rdf"},
    {"id": "273", "name": "タイの反応 タイコエ", "url": "https://thainokoe.com/feed/"},
    {"id": "274", "name": "２ちゃんねるニュース超速まとめ＋", "url": "http://2chnewsblog.blog.jp/index.rdf"},
    {"id": "275", "name": "スマブラ屋さん | スマブラSPまとめ攻略", "url": "http://sumaburayasan.com/index.rdf"},
    {"id": "276", "name": "銀河系まとめブログ", "url": "http://ginnga.blog.jp/index.rdf"},
    {"id": "277", "name": "汎用型自作PCまとめ", "url": "http://www.jisaka.com/index.rdf"},
    {"id": "278", "name": "わろたにえん速報", "url": "https://warotanien.net/feed"},
    {"id": "279", "name": "NMB48まとめといたで", "url": "http://nmb48matome.net/feed"},
    {"id": "280", "name": "中国 ~100年遅れの帝国主義~ まとめ", "url": "http://china-aggressor-nation.blog.jp/index.rdf"},
    {"id": "281", "name": "投資ちゃんねる", "url": "http://toushichannel.net/index.rdf"},
    {"id": "282", "name": "キチママ警報 -キチママ・生活系まとめ-", "url": "http://kichimama.com/index.rdf"},
    {"id": "283", "name": "ジャンプまとめ速報", "url": "http://jumpmatome2ch.biz/feed"},
    {"id": "284", "name": "かいこれ！ 海外の反応 コレクション", "url": "https://kaikore.blogspot.com/feeds/posts/default?alt=rss"},
    {"id": "285", "name": "物見ニュース", "url": "http://monomi-news.blog.jp/index.rdf"},
    {"id": "286", "name": "フィギュアスケートまとめ零", "url": "http://xxhuyuzero.jp/feed"},
    {"id": "287", "name": "欅坂46まとめラボ", "url": "http://www.keyakizaka46matomerabo.com/index.rdf"},
    {"id": "288", "name": "ねこのあまやどり", "url": "http://bluebluesunset.blog.fc2.com/?xml"},
    {"id": "289", "name": "あまつぶし", "url": "http://blog.livedoor.jp/amatsubushi/index.rdf"},
    {"id": "290", "name": "あぁ^～こころがぴょんぴょんするんじゃぁ^～", "url": "http://kokopyon.net/?xml"},
    {"id": "291", "name": "あのころの", "url": "http://na2ka4.blog.fc2.com/?xml"},
    {"id": "292", "name": "エアライン本舗", "url": "http://airlinehonpo.blog.fc2.com/?xml"},
    {"id": "293", "name": "マネーライフ2ch|クレジット関連・お金関係", "url": "http://money-life.doorblog.jp/index.rdf"},
    {"id": "294", "name": "理想ちゃんねる", "url": "http://ideal2ch.livedoor.biz/index.rdf"},
    {"id": "295", "name": "もえぽんず。", "url": "http://moeponzu.com/?xml"},
    {"id": "296", "name": "映画.net", "url": "http://www.movient.net/index.rdf"},
    {"id": "297", "name": "ガジェット2ch", "url": "http://www.gadget2ch.com/index.rdf"},
    {"id": "298", "name": "くまニュース", "url": "http://blog.livedoor.jp/qmanews/index.rdf"},
    {"id": "299", "name": "すれすた", "url": "http://suresuta.jp/feed"},
    {"id": "300", "name": "にじめん", "url": "http://nijimen.net/index.rdf"},
    {"id": "301", "name": "パチンコ・パチスロ.com", "url": "http://pachinkopachisro.com/index.rdf"},
    {"id": "302", "name": "De速", "url": "http://de-baystars.doorblog.jp/index.rdf"},
    {"id": "303", "name": "おいしいお", "url": "http://www.gurum.biz/index.rdf"},
    {"id": "304", "name": "PCパーツまとめ", "url": "http://blog.livedoor.jp/bluejay01-review/index.rdf"},
    {"id": "305", "name": "えび通", "url": "http://ebitsu.net/index.rdf"},
    {"id": "306", "name": "つれさか　-徒然サッカー雑記- - 海外の反応", "url": "http://blog.livedoor.jp/aushio/archives/cat_150742.xml"},
    {"id": "307", "name": "イケイケ速報", "url": "http://ikeike2ch.jp/index.rdf"},
    {"id": "308", "name": "ギャン速2ch　～競馬まとめブログ～", "url": "http://iroirokeiba.blog.fc2.com/?xml"},
    {"id": "309", "name": "AKB48地下速報", "url": "http://blog.livedoor.jp/akb48rhyh/index.rdf"},
    {"id": "310", "name": "Sound Field", "url": "http://moeaudio.blog29.fc2.com/?xml"},
    {"id": "311", "name": "音まとめ", "url": "http://blog.livedoor.jp/otomatome/index.rdf"},
    {"id": "312", "name": "ポーランドボール 翻訳", "url": "http://polandball.blog.fc2.com/?xml"},
    {"id": "313", "name": "海外の反応ジャーナル", "url": "https://overseasresponse.com/feed"},
    {"id": "314", "name": "べビメタだらけの・・・", "url": "https://www.babymetal-darake.com/feed"},
    {"id": "315", "name": "ゲーム攻略のまるはし", "url": "http://blog.game084.com/index.rdf"},
    {"id": "316", "name": "全ては跡地。", "url": "http://ssimas.blog.fc2.com/?xml"},
    {"id": "317", "name": "海外反応！　I LOVE JAPAN", "url": "http://blog.livedoor.jp/zzcj/index.rdf"},
    {"id": "318", "name": "やらおん！", "url": "http://yaraon-blog.com/feed"},
    {"id": "319", "name": "馬鳥速報", "url": "http://blog.livedoor.jp/umadori0726/index.rdf"},
    {"id": "320", "name": "TweetPocket", "url": "http://blog.livedoor.jp/pocketcamp/index.rdf"},
    {"id": "321", "name": "なんJ HERO", "url": "http://nanj-hero.com/index.rdf"},
    {"id": "322", "name": "オタカム", "url": "http://otakamu.com/index.rdf"},
    {"id": "323", "name": "IT速報", "url": "http://blog.livedoor.jp/itsoku/index.rdf"},
    {"id": "324", "name": "ぱわわ速報", "url": "http://pawawa.sokuho.org/index20.rdf"},
    {"id": "325", "name": "ベア速", "url": "http://beasoku.com/index20.rdf"},
    {"id": "326", "name": "まとめ映ぇぇ", "url": "http://matmebae.net/index20.rdf"},
    {"id": "327", "name": "マイルドちゃんねる", "url": "http://mildch.com/index.rdf"},
    {"id": "328", "name": "アドちゃんねる", "url": "http://blog.livedoor.jp/sasuga801-koukokugyoukai/index.rdf"},
    {"id": "329", "name": "いくじったー", "url": "http://blog.livedoor.jp/ikuzitter/index.rdf"},
    {"id": "330", "name": "ビッグバンちゃんねる", "url": "http://bigbangchannel.net/index.rdf"},
    {"id": "331", "name": "らばQ - 海外の反応", "url": "http://labaq.com/archives/cat_50037985.xml"},
    {"id": "332", "name": "こんなニュースにでくわした", "url": "http://stumbleon.blog.fc2.com/?xml"},
    {"id": "333", "name": "今日も荷物が届かない。@海外の反応", "url": "http://baychannel.blog.fc2.com/?xml"},
    {"id": "334", "name": "BABYMETALIZE", "url": "http://babymetalize.com/feed"},
    {"id": "335", "name": "【動画翻訳】かっとびジャパン - 海外の反応", "url": "http://www.kattobi-japan.com/index.rdf"},
    {"id": "336", "name": "かいちょく", "url": "https://chokkanteki.com/feed/"},
    {"id": "337", "name": "海外の反応  –  あにかい | アニメ・ゲーム海外の反応まとめ", "url": "https://anicai.jp/archives/category/kaigaihanou/feed"},
    {"id": "338", "name": "海外の反応 ニッポンの翻訳", "url": "http://kaigai-nippon.com/?feed=rss2"},
    {"id": "339", "name": "海外の反応 | LOL忍者", "url": "https://lolninja.net/category/%e6%b5%b7%e5%a4%96%e3%81%ae%e5%8f%8d%e5%bf%9c/feed/"},
    {"id": "340", "name": "eigotoka 　〜海外スレ翻訳所〜", "url": "https://eigotoka.com/feed"},
    {"id": "341", "name": "「日中文化交流」と書いてオタ活動と読む", "url": "http://blog.livedoor.jp/kashikou/index.rdf"},
    {"id": "342", "name": "格ゲーブログ（仮） - 海外の反応", "url": "http://kakugeblog.blog.jp/archives/cat_1131921.xml"},
    {"id": "343", "name": "塩韓スポーツ", "url": "http://siokan5000.blog.fc2.com/?xml"},
    {"id": "344", "name": "新世代台湾人の反応", "url": "https://twfunnymovie.com/?xml"},
    {"id": "345", "name": "海外の小反応", "url": "http://mykeibamemory.blog.fc2.com/?xml"},
    {"id": "346", "name": "中国人の戯言～大中華思想～", "url": "http://chinesestyle.seesaa.net/index.rdf"},
    {"id": "347", "name": "フォゲラバリ（海外の反応）", "url": "http://closetotokyo.blog.fc2.com/?xml"},
    {"id": "348", "name": "世界の憂鬱 海外・韓国の反応", "url": "http://blog.livedoor.jp/sekaiminzoku/index.rdf"},
    {"id": "349", "name": "イワド新報", "url": "https://iwado.work/feed"},
    {"id": "350", "name": "コーヒーと翻訳", "url": "https://coffeehonyaku.blogspot.com/feeds/posts/default?alt=rss&orderby=published"},
    {"id": "351", "name": "海外の反応で英語の勉強", "url": "http://www.kagerou.biz/index.rdf"},
    {"id": "352", "name": "蠱惑の壺 | 漫画・アニメ海外の反応まとめ", "url": "http://watamotetrans.livedoor.blog/index.rdf"},
    {"id": "353", "name": "かんこく！　韓国の反応翻訳ブログ", "url": "https://kankokunohannou.org/?xml"},
    {"id": "354", "name": "海外さんいらっしゃい　海外の反応", "url": "https://kaigaiwelcome.com/?xml"},
    {"id": "355", "name": "世界の反応　さら速", "url": "http://sarasoku.net/feed/"},
    {"id": "356", "name": "ボイスオブコリア韓国の反応翻訳まとめ", "url": "https://k-han.com/?xml"},
    {"id": "357", "name": "ほっこりはん", "url": "https://hokkorihann.com/?xml"},
    {"id": "358", "name": "YouTube海外の反応まとめ", "url": "http://kaigaihannnoumatome.ldblog.jp/index.rdf"},
    {"id": "359", "name": "パンコリ", "url": "https://pankori.net/feed/"},
    {"id": "360", "name": "韓国の反応  |  海外トークログ", "url": "https://muryou-tanoshimu.com/category/kankoku/feed/"},
    {"id": "361", "name": "ミク廃！！", "url": "https://grewgrehrg.blog.fc2.com/?xml"},
    {"id": "362", "name": "海外の反応スポーツ", "url": "https://www.kaisupo.com/rss.xml?alt=rss"},
    {"id": "363", "name": "KoreAction", "url": "https://koreaction.net/feed/"},
    {"id": "364", "name": "かいがいchan", "url": "https://kaigaichan.net/feed/rss"},
    {"id": "365", "name": "航空万能論GF", "url": "https://grandfleet.info/feed/"},
    {"id": "366", "name": "ゲームほんやくコンニャク", "url": "http://game-honyaku.com/feed/"},
    {"id": "367", "name": "海外の反応 | 海外トークログ", "url": "https://toku-log.com/feed/?cat=-5"},
    {"id": "368", "name": "海外の反応 | 海外のリアクション", "url": "http://kaigai-otaku.jp/category/world/feed"},
    {"id": "369", "name": "日本第一！ニュース録", "url": "https://incident-wo.com/feed/"},
    {"id": "370", "name": "ちまたのアラカルト", "url": "http://a-la-carte.blog.jp/index.rdf"},
    {"id": "371", "name": "暇読み", "url": "https://himayomi.com/feed"},
    {"id": "372", "name": "グルメまとめの「ぐるまと！」", "url": "http://gurumato.net/feed"},
    {"id": "373", "name": "まとめＴｏｋ", "url": "http://tiktok-p.blog.jp/index.rdf"},
    {"id": "374", "name": "2ch大相撲", "url": "http://xn--2ch-2d8eo32c60z.xyz/atom.xml"},
    {"id": "375", "name": "米国株ETFまとめ速報", "url": "http://beikokukabu-etf-matome.com/index.rdf"},
    {"id": "376", "name": "いま速", "url": "https://imasoku.com/feed"},
    {"id": "377", "name": "おんｊサマリー＠なんｊホークスまとめ", "url": "http://onjsummarynet.net/index.rdf"},
    {"id": "378", "name": "SHOWBIZ JAPAN", "url": "http://showbizjapan.blog.fc2.com/?xml"},
    {"id": "379", "name": "ハロプロニュース", "url": "http://hellopronews.blog.jp/index.rdf"},
    {"id": "380", "name": "日刊バーチャル", "url": "http://revuestarlightre.com/index.rdf"},
    {"id": "381", "name": "マラソン速報", "url": "http://marasoku.info/index.rdf"},
    {"id": "382", "name": "Revival Japan 日本復活を叫ぶ", "url": "http://rejapan.blog.jp/index.rdf"},
    {"id": "383", "name": "櫻坂46まとめちゃんねる", "url": "https://keyakizaka46ch.jp/feed"},
    {"id": "384", "name": "宵越しの銭はもたぬ速報", "url": "https://ladyplus.xyz/feed/"},
    {"id": "385", "name": "まんがとあにめ", "url": "http://www.manga-to-anime.net/index.rdf"},
    {"id": "386", "name": "なんJ政治ネタまとめ", "url": "http://j-seiji.blog.jp/index.rdf"},
    {"id": "387", "name": "スマッシュ速報", "url": "http://smasoku.blog.jp/index.rdf"},
    {"id": "388", "name": "徒歩のポケモンまとめブログ", "url": "http://blog.livedoor.jp/tohopoke/index.rdf"},
    {"id": "389", "name": "スパロボまとめ速報", "url": "https://srwmatome.com/feed"},
    {"id": "390", "name": "News Bomb｜ニュースまとめサイト", "url": "http://news-bomb.com/feed"},
    {"id": "391", "name": "音ちゃんねる", "url": "https://oto-ch.net/feed"},
    {"id": "392", "name": "うま速@競馬まとめブログ", "url": "https://umasoku.com/feed"},
    {"id": "393", "name": "ハイファッションちゃんねる", "url": "https://highfashionmens.com/feed"},
    {"id": "394", "name": "明日は何を食べようか", "url": "http://gfoodd.com/feed"},
    {"id": "395", "name": "mutyunのゲーム+αブログ", "url": "https://www.mutyun.com/feed"},
    {"id": "396", "name": "ピンキリ速報 - レスバもまとめる5chブログ -", "url": "http://sfgidf.blog.jp/index.rdf"},
    {"id": "397", "name": "くろす速報", "url": "https://tapittalk.com/feed/"},
    {"id": "398", "name": "守銭奴日報", "url": "https://financial-c.net/feed"},
    {"id": "399", "name": "エムジフ～音ゲー情報局(MGIF)～", "url": "http://www.mgif.jp/index.rdf"},
    {"id": "400", "name": "雑なまとめ", "url": "https://zatuzatu.com/feed"},
    {"id": "401", "name": "ぽけりん＠ポケモンソードシールド(剣盾)まとめ", "url": "http://pokemon-matome.net/index.rdf"},
    {"id": "402", "name": "日本と韓国は敵か？味方か？", "url": "http://blog.livedoor.jp/japan_and_korea/index.rdf"},
    {"id": "403", "name": "BABYMETALまとめもりー", "url": "http://blog.livedoor.jp/bbmt46/index.rdf"},
    {"id": "404", "name": "暇つぶ速報", "url": "http://himatubusokuho.blog.jp/index.rdf"},
    {"id": "405", "name": "Glauber通信", "url": "http://lucky318b.m50.coreserver.jp/feed"},
    {"id": "406", "name": "かたすみ速報", "url": "http://katasumisokuhou.blog.jp/index.rdf"},
    {"id": "407", "name": "まるたろうの怖い心霊ブログ", "url": "http://www.maruhorror.com/index.rdf"},
    {"id": "408", "name": "CRただいま速報", "url": "http://a711.work/index.rdf"},
    {"id": "409", "name": "世界歴史ちゃんねる", "url": "https://world-study.jp/feed"},
    {"id": "410", "name": "アークナイツまとめタイムズ", "url": "http://arknights.more-gamer.com/feed"},
    {"id": "411", "name": "気になるVtuber速報", "url": "https://moti-soku.com/feed/"},
    {"id": "412", "name": "とらのまき", "url": "https://www.news-toranomaki.net/?feed=rss2"},
    {"id": "413", "name": "まとめ安倍速報", "url": "http://blog.livedoor.jp/abechan_matome/index.rdf"},
    {"id": "414", "name": "今日の立ち読みまとめ", "url": "http://tachiyomitoday.com/index.rdf"},
    {"id": "415", "name": "競馬まとめのまとめ", "url": "http://umaumanews.com/feed"},
    {"id": "416", "name": "ぴろり速報", "url": "http://pirori2ch.com/feed"},
    {"id": "417", "name": "蹴球的情報ch", "url": "https://syuukyuu.com/feed"},
    {"id": "418", "name": "FGOまとめ速報", "url": "https://www.fatego-matome.com/feed/"},
    {"id": "419", "name": "なんJ襲来", "url": "http://blog.livedoor.jp/nanjsyurai/index.rdf"},
    {"id": "420", "name": "でれげき -シンデレラガールズ劇場まとめ-", "url": "http://cggekijo.blog.fc2.com/?xml"},
    {"id": "421", "name": "Fate/Grand Order攻略情報まとめ", "url": "http://fate-grandorder.jp/?feed=rss2"},
    {"id": "422", "name": "じゃぱそく！", "url": "http://jpsoku.blog.jp/index.rdf"},
    {"id": "423", "name": "脱亜論", "url": "http://datsuaron.blog.jp/index.rdf"},
    {"id": "424", "name": "投打スタジアムCH", "url": "https://pitch-bat.com/feed"},
    {"id": "425", "name": "荒野行動攻略まとめ隊", "url": "https://xn--hhr014byylm9m90fi1p.com/feed"},
    {"id": "426", "name": "ロマサガRS攻略まとめ隊", "url": "https://xn--mckr6j9b9367e.com/feed"},
    {"id": "427", "name": "ドラクエライバルズ攻略まとめ隊", "url": "https://xn--eckhu0c0d1b5kcu5305ksfpb.com/feed"},
    {"id": "428", "name": "モンハンワールド攻略まとめ隊", "url": "https://xn--gdkl0dubtwb7e.net/feed"},
    {"id": "429", "name": "ドラゴンボールレジェンズ攻略まとめ隊", "url": "https://xn--o9j0bk3mocyap0jsh2eyam2gf4k.net/feed"},
    {"id": "430", "name": "ドールズフロントライン 攻略まとめ隊", "url": "https://xn--o9j0bk9175aoqh34d491f.com/feed"},
    {"id": "431", "name": "ハースストーン攻略まとめ速報", "url": "https://xn--zcka9bza7pybd5118hco4a.com/feed"},
    {"id": "432", "name": "シャドウバース攻略まとめ隊", "url": "https://xn--o9j0bk9l8cn4i9byj2jo863c0ssb.com/feed"},
    {"id": "433", "name": "プリコネ攻略まとめ隊", "url": "https://xn--o9j0bk1rwe8bvh.com/feed"},
    {"id": "434", "name": "スマブラ攻略まとめ隊", "url": "https://xn--o9j0bk5t7exbwe.com/feed"},
    {"id": "435", "name": "FGO攻略まとめ隊", "url": "https://xn--fgo-gh8fn72e.com/feed"},
    {"id": "436", "name": "アークナイツ攻略まとめGS", "url": "https://xn--ccke6azf2a21a.gamerstand.net/feed"},
    {"id": "437", "name": "スパロボDD攻略まとめ GAMER STAND", "url": "https://gamerstand.net/srw-dd/feed"},
    {"id": "438", "name": "ランモバ攻略まとめGS", "url": "https://xn--ndk9au4b.gamerstand.net/feed"},
    {"id": "439", "name": "FFBE幻影戦争 攻略まとめGS", "url": "https://ffbe-wotv.gamerstand.net/feed"},
    {"id": "440", "name": "デュエプレ攻略まとめ GS", "url": "https://xn--ick1c6c0a.gamerstand.net/feed"},
    {"id": "441", "name": "ネラーボイス", "url": "http://netizen-voice.blog.jp/index.rdf"},
    {"id": "442", "name": "欅坂46まとめもり～", "url": "http://keyakizaka46matomemory.net/index.rdf"},
    {"id": "443", "name": "日向坂46まとめもり～", "url": "http://46matome.net/index.rdf"},
    {"id": "444", "name": "ドラクエウォーク速報", "url": "https://draquewalk.blog.fc2.com/?xml"},
    {"id": "445", "name": "FGOまとめマン速報", "url": "https://xn--fgo-yb4b8dta56dif.xyz/feed/"},
    {"id": "446", "name": "FGOノウムカルデア攻略速報", "url": "https://fgonovum.com/feed/"},
    {"id": "447", "name": "もえるにほん彡(^)(^)", "url": "http://moerunihon.blog.jp/index.rdf"},
    {"id": "448", "name": "パワ速@プロスピA攻略まとめ", "url": "http://pawapuro.xyz/?feed=rss2"},
    {"id": "449", "name": "ハチナイ速報＠八月のシンデレラナイン攻略まとめ", "url": "http://hachinai.net/?feed=rss2"},
    {"id": "450", "name": "おフトンからまとめ", "url": "http://blog.livedoor.jp/daunti/index.rdf"},
    {"id": "451", "name": "2chまとめ放題", "url": "http://blog.livedoor.jp/himacyan/index.rdf"},
    {"id": "452", "name": "超・ジャンプまとめ速報", "url": "https://jumpmatome2ch.net/feed"},
    {"id": "453", "name": "ほのぼのしない動物速報 (Ф∀Ф)", "url": "http://hnbnfun.blog.jp/index.rdf"},
    {"id": "454", "name": "ポケモンGO攻略まとめ速報！！", "url": "http://pokemongo-kouryakumatome.net/index.rdf"},
    {"id": "455", "name": "仮面ライダーまとめ２号", "url": "http://kamenrider2.net/feed"},
    {"id": "456", "name": "仁王まとめ速報｜仁王2", "url": "http://nioh.more-gamer.com/feed"},
    {"id": "457", "name": "2chNEWSまとめ", "url": "http://shikaku105.blog.jp/index.rdf"},
    {"id": "458", "name": "バスケまとめ・COM", "url": "http://basketballbbs.com/feed/"},
    {"id": "459", "name": "どうぶつの森まとめ速報", "url": "http://butumori.com/index.rdf"},
    {"id": "460", "name": "きうり♪やきう♪きうり♪＠なんJ", "url": "http://baseball-nanj.com/?xml"},
    {"id": "461", "name": "サッカータイム", "url": "https://soccer-time.net/index.rdf"},
    {"id": "462", "name": "スロカク | パチスロデータ格付けブログ", "url": "https://slo-matome.com/category/news/feed/"},
    {"id": "463", "name": "旅のろぐ", "url": "https://tabinolog.com/feed"},
    {"id": "464", "name": "パチスロログ", "url": "https://slotlog.net/feed"},
    {"id": "465", "name": "パーラーフルスロットル", "url": "https://parlourfullslotl.com/feed"},
    {"id": "466", "name": "大陸日報", "url": "http://continent-news.blog.jp/atom.xml"},
    {"id": "467", "name": "PS5速報", "url": "https://ps5sokunews.com//?feed=rss2"},
    {"id": "468", "name": "バイクライフちゃんねる", "url": "https://baiku-life.com/feed"},
    {"id": "469", "name": "ホロ速", "url": "https://holosoku.com/feed/"},
    {"id": "470", "name": "かじとじむ", "url": "https://kaji2jimu.work/index.rdf"},
    {"id": "471", "name": "ブラブラブラウジング", "url": "http://brow2ing.com/index.rdf"},
    {"id": "472", "name": "ニチカン!", "url": "https://betweenjpandkr.blog/feed"},
    {"id": "473", "name": "2chまとめ・読み物・長編・名作/2MONKEYS.JP", "url": "http://www.2monkeys.jp/index.rdf"},
    {"id": "474", "name": "トーイチャンネット", "url": "http://toychan.blog.jp/index.rdf"},
    {"id": "475", "name": "まとめる", "url": "http://matomeru1.livedoor.blog/index.rdf"},
    {"id": "476", "name": "ばびろにあっ！", "url": "https://fgo-babylonia-cafe.jp/feed/"},
    {"id": "477", "name": "プリキュアのまとめ", "url": "http://precurematome.com/feed/"},
    {"id": "478", "name": "コイン速報 | 仮想通貨ニュース・暗号資産相場情報・5chまとめ", "url": "http://blog.livedoor.jp/kumokumowatawata/index.rdf"},
    {"id": "479", "name": "歴史的速報", "url": "http://blog.livedoor.jp/waruneko00326-002/index.rdf"},
    {"id": "480", "name": "チーム8まとめりか(AKB48Team8まとめ)", "url": "http://akb48team8.net/feed/"},
    {"id": "481", "name": "まとめだかニュース速報＠", "url": "http://medakamatome.tokyo/index.rdf"},
    {"id": "482", "name": "じわるチャンネル-雑談まとめブログ-", "url": "http://jiwachan.net/index.rdf"},
    {"id": "483", "name": "修羅場家の日常", "url": "http://syurabake.com/index.rdf"},
    {"id": "484", "name": "FGOまとめ　カルデア速報", "url": "http://fgochaldeas.com/index.rdf"},
    {"id": "485", "name": "鬼女の刃", "url": "http://blog.livedoor.jp/kijyonoyaiba/index.rdf"},
    {"id": "486", "name": "女と男の幸せがいっぱい", "url": "http://gooddays-wedding.com/feed/"},
    {"id": "487", "name": "結婚総研", "url": "http://kekkon-souken.com/index.rdf"},
    {"id": "488", "name": "ごちそう速報", "url": "http://blog.livedoor.jp/gotisoku/index.rdf"},
    {"id": "489", "name": "ネット民の反応：国内・海外のゲーム・アニメの反応まとめ！", "url": "https://dsara.blog.fc2.com/?xml"},
    {"id": "490", "name": "VIPPERlog", "url": "http://vipperlog.com/index.rdf"},
    {"id": "491", "name": "アブロードチャンネル｜サッカー専門の海外の反応サイト", "url": "https://abroadch.com/feed/"},
    {"id": "492", "name": "グラブルまとめ！いすたるしあ通信", "url": "https://estalucia.com/feed"},
    {"id": "493", "name": "SKE48まとめもらんだむ", "url": "http://ske48matomemo.doorblog.jp/index.rdf"},
    {"id": "494", "name": "VTuberNews", "url": "http://vtubernews.jp/index.rdf"},
    {"id": "495", "name": "ハロプロ×LIFE", "url": "http://blog.livedoor.jp/morning77/index.rdf"},
    {"id": "496", "name": "ポケモンユナイト作戦会議", "url": "https://pokemonunite.blog.fc2.com/?xml"},
    {"id": "497", "name": "ぶいちゅーばー速報", "url": "http://vtubersokuhou.com/feed"},
    {"id": "498", "name": "Vtuber速報@バーチャルYouTuberまとめ", "url": "http://vrtuber-news.com/index.rdf"},
    {"id": "499", "name": "ゲーハーの窓", "url": "http://blog.livedoor.jp/madoyuka//index.rdf"},
    {"id": "500", "name": "ZAPZAP!", "url": "https://zapzapjp.com/index.rdf"},
    {"id": "501", "name": "新5chまとめ速報-ネオ速-", "url": "https://matome-new.com//?feed=rss2"},
    {"id": "502", "name": "20ＸＸニュース", "url": "http://20xxnyu-su.blog.jp/index.rdf"},
    {"id": "503", "name": "ジオろぐ", "url": "http://geolog-book.com/index.rdf"},
    {"id": "504", "name": "ニダアル速報＋", "url": "http://nida-aru.com/index.rdf"},
    {"id": "505", "name": "GIOGIOの奇妙な速報‐AKB48・チーム8まとめたの", "url": "http://www.giogio48.com/index.rdf"},
    {"id": "506", "name": "NMB時々AKBとか", "url": "http://nmbfan.seesaa.net/index20.rdf"},
    {"id": "507", "name": "なんＪは加速している", "url": "http://blog.livedoor.jp/nanjmagnus/index.rdf"},
    {"id": "508", "name": "ぱちんこドキュメント!!", "url": "http://pachinkolist.com/index.rdf"},
    {"id": "509", "name": "ゆいたんねる", "url": "https://yuitannel.blog.jp/index.rdf"},
    {"id": "510", "name": "プロ野球いろいろ速報", "url": "http://jinniro.blog.fc2.com/?xml"},
    {"id": "511", "name": "為になる？質問ある？まとめ", "url": "http://shitsumonaru.com/feed"},
    {"id": "512", "name": "Vtuberまとめるよ～ん", "url": "http://vtuber-matomeruyon.blog.jp/index.rdf"},
    {"id": "513", "name": "軍事・ミリタリーログ", "url": "http://o2military.blog.jp/index.rdf"},
    {"id": "514", "name": "知識の城　群雄割拠", "url": "https://love-knowledge.com/feed"},
    {"id": "515", "name": "ケイバペディア", "url": "https://keibapedia.com/?feed=rss2"},
    {"id": "516", "name": "ボントロちゃんねる", "url": "https://trombonechannel.net/feed"},
    {"id": "517", "name": "しゅーキチ速報", "url": "http://shukichisokuhou.blog/index.rdf"},
    {"id": "518", "name": "しゅららら物語", "url": "https://shurarara-monogatari.com/feed/"},
    {"id": "519", "name": "お笑いまとめ　芸人速報", "url": "https://geininsokuhou.com/feed"},
    {"id": "520", "name": "育ママ速報", "url": "http://ikumamasokuhou.com/index.rdf"},
    {"id": "521", "name": "うまろぐ", "url": "https://uma-log.net/feed/"},
    {"id": "522", "name": "マクド総研", "url": "http://mcri.blog/?feed=rss2"},
    {"id": "523", "name": "まりえる速報", "url": "https://mari-soku.com/feed/"},
    {"id": "524", "name": "ネト将まとめ", "url": "https://netshogimatome.blog.fc2.com/?xml"},
    {"id": "525", "name": "芸能7days", "url": "http://geinou-7days.net/feed"},
    {"id": "526", "name": "ぱちとろ速報", "url": "https://metabopro.net/feed"},
    {"id": "527", "name": "ボールパーク速報 海外の反応", "url": "https://www.ballparksokuhou.com/?xml"},
    {"id": "528", "name": "まるっと翻訳", "url": "https://marutoo.com/feed"},
    {"id": "529", "name": "自虐史感から脱却して世界を見る", "url": "https://blog.sky-spider.com/index.xml"},
    {"id": "530", "name": "ガジェットの泉ちゃんねる", "url": "https://gadjeizu.net/?feed=rss2"},
    {"id": "531", "name": "ネット速報まとめ超", "url": "https://netsokuhou.seesaa.net/index20.rdf"},
    {"id": "532", "name": "ヘブバン広場", "url": "https://hbr-square.com/feed/"},
    {"id": "533", "name": "アズレン速報", "url": "https://azurlane-sokuhou.com/?feed=rss2"},
    {"id": "534", "name": "アニメの総合集", "url": "https://sduhrk.livedoor.blog/index.rdf"},
    {"id": "535", "name": "VTuberまとめ情報", "url": "http://moon0502.blog.jp/index.rdf"},
    {"id": "536", "name": "寝落ち速報", "url": "https://neochisokuhou.net/feed/"},
    {"id": "537", "name": "時事ネタニュース速報", "url": "http://jijinews.online/index.rdf"},
    {"id": "538", "name": "おいしいまとめ", "url": "https://oishiimatome.com/?xml"},
    {"id": "539", "name": "投資ネタ集めておいたのだ！", "url": "https://invest-news-source.com/?feed=rss2"},
    {"id": "540", "name": "わちゃくちゃ速報", "url": "https://ksakamo0903.com/feed/"},
    {"id": "541", "name": "僕青ちゃんねる", "url": "https://gootore.xyz/?feed=rss2"},
    {"id": "542", "name": "ハロアップデート", "url": "https://hpupdate.info/?feed=rss2"},
    {"id": "543", "name": "しゅらさん｜キチママ・修羅場の生活まとめ", "url": "https://www.syurasan.com/?xml"},
    {"id": "544", "name": "めちゃヤバ速報", "url": "https://metyayaba.com/?feed=rss2"},
    {"id": "545", "name": "ブラウザゲーム速報", "url": "https://df-browser-games.com/?xml"},
    {"id": "546", "name": "ネタンゴ！", "url": "https://nogizakajyoho46.com/index.rdf"},
    {"id": "547", "name": "Collect animations", "url": "https://ad-ars-line.blog/?feed=rss2"},
    {"id": "548", "name": "爆速まとめめんと", "url": "https://matomemento.com/feed/rdf/"},
    {"id": "549", "name": "Ask Reddit まとめ", "url": "https://reddit-matome.com/feed"},
    {"id": "550", "name": "世界反応図鑑", "url": "https://sekai-zukan.blog/feed/"},
    {"id": "551", "name": "GIANTS PRIDE ニュース", "url": "https://giants-pride-news.com/category/giants/feed/"},
    {"id": "552", "name": "乃木坂LIFE -坂道・48高速まとめ-", "url": "https://nogizakalife.tokyo/?feed=rss2"},
    {"id": "553", "name": "Red4 海外の反応まとめ", "url": "https://red4-kaigaimatome.com/feed/"},
    {"id": "554", "name": "投資.com", "url": "https://keizai4567.blog.jp/index.rdf"},
    {"id": "555", "name": "ハロスポ＠ハロプロまとめ", "url": "https://halospo.com/feed/"},
    {"id": "556", "name": "せかはん（世界の反応）", "url": "https://sekahan0623.com/feed"},
]
