# scripts/feeds.py

FEEDS = [
    {"id": "morikinoko_com", "name": "SS 森きのこ！", "url": "http://morikinoko.com/index.rdf"},
    {"id": "news_2chblog_jp", "name": "【2ch】コピペ情報局", "url": "http://news.2chblog.jp/index.rdf"},
    {"id": "blog_livedoor_jp_nwknews", "name": "哲学ニュースnwk", "url": "http://blog.livedoor.jp/nwknews/index.rdf"},
    {"id": "news4vip_livedoor_biz", "name": "【2ch】ニュー速クオリティ", "url": "http://news4vip.livedoor.biz/index.rdf"},
    {"id": "matometanews_com", "name": "まとめたニュース", "url": "http://matometanews.com/index.rdf"},
    {"id": "blog_livedoor_jp_jyoushiki43", "name": "常識的に考えた", "url": "http://blog.livedoor.jp/jyoushiki43/index.rdf"},
    {"id": "himasoku_com", "name": "暇人＼(^o^)／速報", "url": "http://himasoku.com/index.rdf"},
    {"id": "blog_livedoor_jp_dqnplus", "name": "痛いニュース(ﾉ∀`)", "url": "http://blog.livedoor.jp/dqnplus/index.rdf"},
    {"id": "exawarosu_net", "name": "エクサワロス | ニュースまとめサイト", "url": "http://exawarosu.net/index.rdf"},
    {"id": "blog_livedoor_jp_yu_ps13", "name": "ゆめ痛 -NEWS ALERT-", "url": "http://blog.livedoor.jp/yu_ps13/index.rdf"},
    {"id": "fxya_blog129_fc2_com", "name": "政経ch", "url": "http://fxya.blog129.fc2.com/?xml"},
    {"id": "channelz_blog_fc2_com", "name": "ちゃんねるZ", "url": "http://channelz.blog.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_misopan_news", "name": "みそパンNEWS", "url": "http://blog.livedoor.jp/misopan_news/index.rdf"},
    {"id": "blog_livedoor_jp_gotagotashita", "name": "ゴタゴタシタニュース", "url": "http://blog.livedoor.jp/gotagotashita/index.rdf"},
    {"id": "www_news30over_com", "name": "ニュース30over", "url": "http://www.news30over.com/index.rdf"},
    {"id": "blog_livedoor_jp_funs", "name": "ガハろぐNewsヽ(･ω･)/ｽﾞｺｰ", "url": "http://blog.livedoor.jp/funs/index.rdf"},
    {"id": "ryusoku_com", "name": "流速VIP", "url": "http://ryusoku.com/index.rdf"},
    {"id": "kuromacyo_livedoor_biz", "name": "黒マッチョニュース", "url": "http://kuromacyo.livedoor.biz/index.rdf"},
    {"id": "blog_livedoor_jp_warakan2ch", "name": "笑　韓　ブログ", "url": "http://blog.livedoor.jp/warakan2ch/index.rdf"},
    {"id": "www_scienceplus2ch_com", "name": "(*ﾟ∀ﾟ)ゞカガクニュース隊", "url": "http://www.scienceplus2ch.com/index.rdf"},
    {"id": "blog_livedoor_jp_news23vip", "name": "VIPPERな俺", "url": "http://blog.livedoor.jp/news23vip/index.rdf"},
    {"id": "milfled_seesaa_net", "name": "何でもありんす", "url": "http://milfled.seesaa.net/index.rdf"},
    {"id": "burusoku_vip_com", "name": "ぶる速-VIP", "url": "http://burusoku-vip.com/index.rdf"},
    {"id": "hamusoku_com", "name": "ハムスター速報", "url": "http://hamusoku.com/index.rdf"},
    {"id": "kanasoku_info", "name": "カナ速", "url": "http://kanasoku.info/index.rdf"},
    {"id": "blog_livedoor_jp_goldennews", "name": "ゴールデンタイムズ", "url": "http://blog.livedoor.jp/goldennews/index.rdf"},
    {"id": "workingnews_blog117_fc2_com", "name": "働くモノニュース : 人生VIP職人ブログwww", "url": "http://workingnews.blog117.fc2.com/?xml"},
    {"id": "digital_thread_com", "name": "デジタルニューススレッド", "url": "http://digital-thread.com/index.rdf"},
    {"id": "chaos2ch_com", "name": "カオスちゃんねる", "url": "http://chaos2ch.com/index.rdf"},
    {"id": "lamsect_blog112_fc2_com", "name": "ジュピ速", "url": "http://lamsect.blog112.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_kinisoku", "name": "キニ速", "url": "http://blog.livedoor.jp/kinisoku/index.rdf"},
    {"id": "waranote_livedoor_biz", "name": "ワラノート", "url": "http://waranote.livedoor.biz/index.rdf"},
    {"id": "blog_livedoor_jp_joujakuvip2ch", "name": "情弱VIP2ちゃんねる", "url": "http://blog.livedoor.jp/joujakuvip2ch/index.rdf"},
    {"id": "michaelsan_livedoor_biz", "name": "もみあげチャ～シュ～", "url": "http://michaelsan.livedoor.biz/index.rdf"},
    {"id": "blog_livedoor_jp_darkm", "name": "はれぞう", "url": "http://blog.livedoor.jp/darkm/index.rdf"},
    {"id": "blog_livedoor_jp_soccerkusoyarou", "name": "サッカーミックスジュース", "url": "http://blog.livedoor.jp/soccerkusoyarou/index.rdf"},
    {"id": "alfalfalfa_com", "name": "アルファルファモザイク", "url": "http://alfalfalfa.com/index.rdf"},
    {"id": "lifehack2ch_livedoor_biz", "name": "ライフハックちゃんねる弐式", "url": "http://lifehack2ch.livedoor.biz/index.rdf"},
    {"id": "kosodatech_blog133_fc2_com", "name": "子育てちゃんねる", "url": "http://kosodatech.blog133.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_kekkongo", "name": "結婚・恋愛ニュースぷらす", "url": "http://blog.livedoor.jp/kekkongo/index.rdf"},
    {"id": "onecall2ch_com", "name": "わんこーる速報！", "url": "http://onecall2ch.com/index.rdf"},
    {"id": "rakusyasa_blog41_fc2_com", "name": "うるるんロギー", "url": "http://rakusyasa.blog41.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_robosoku", "name": "ろぼ速VIP", "url": "http://blog.livedoor.jp/robosoku/index.rdf"},
    {"id": "blog_esuteru_com", "name": "はちま起稿", "url": "http://blog.esuteru.com/index.rdf"},
    {"id": "jin115_com", "name": "オレ的ゲーム速報＠刃", "url": "http://jin115.com/index.rdf"},
    {"id": "mousouteki_blog53_fc2_com", "name": "続・妄想的日常", "url": "http://mousouteki.blog53.fc2.com/?xml"},
    {"id": "2chcopipe_com", "name": "2chコピペ保存道場", "url": "http://2chcopipe.com/index.rdf"},
    {"id": "mogeonna_blog_fc2_com", "name": "いろんな人ガイル", "url": "http://mogeonna.blog.fc2.com/?xml"},
    {"id": "otakomu_jp", "name": "オタク.com", "url": "http://otakomu.jp/index.rdf"},
    {"id": "cherio199_blog120_fc2_com", "name": "ヒロイモノ中毒", "url": "http://cherio199.blog120.fc2.com/?xml"},
    {"id": "honwaka2ch_livedoor_biz", "name": "ほんわかMkⅡ", "url": "http://honwaka2ch.livedoor.biz/index.rdf"},
    {"id": "blog_livedoor_jp_nanjstu", "name": "なんじぇいスタジアム＠なんJまとめ", "url": "http://blog.livedoor.jp/nanjstu/index.rdf"},
    {"id": "sk2ch_net", "name": "すかっとしていきませんか | sk2ch", "url": "http://sk2ch.net/feed"},
    {"id": "military38_com", "name": "大艦巨砲主義！", "url": "http://military38.com/index.rdf"},
    {"id": "hosyusokuhou_jp", "name": "保守速報", "url": "http://hosyusokuhou.jp/index.rdf"},
    {"id": "www_akb48matomemory_com", "name": "NEWSまとめもりー｜2chまとめブログ", "url": "http://www.akb48matomemory.com/index.rdf"},
    {"id": "usi32_com", "name": "うしみつ-2ch怖い話まとめ-", "url": "http://usi32.com/index.rdf"},
    {"id": "gundamlog_com", "name": "GUNDAM.LOG｜ガンダムまとめブログ", "url": "http://gundamlog.com/index.rdf"},
    {"id": "blog_livedoor_jp_diet2channel", "name": "ダイエット速報＠2ちゃんねる", "url": "http://blog.livedoor.jp/diet2channel/index.rdf"},
    {"id": "world_fusigi_net", "name": "不思議.net", "url": "http://world-fusigi.net/index.rdf"},
    {"id": "overjoyed_info", "name": "オーバージョイド！　　2chまとめサイト", "url": "http://overjoyed.info/feed"},
    {"id": "chomanga_org", "name": "超マンガ速報", "url": "http://chomanga.org/feed"},
    {"id": "vippers_jp", "name": "VIPPER速報", "url": "http://vippers.jp/index.rdf"},
    {"id": "blog_livedoor_jp_yakiusoku", "name": "日刊やきう速報＠野球まとめ", "url": "http://blog.livedoor.jp/yakiusoku/index.rdf"},
    {"id": "uwakich_com", "name": "浮気ちゃんねる", "url": "http://uwakich.com/index.rdf"},
    {"id": "rabitsokuhou_2chblog_jp", "name": "ラビット速報", "url": "http://rabitsokuhou.2chblog.jp/index.rdf"},
    {"id": "www_kitimama_matome_net", "name": "キチガイママまとめ保管庫", "url": "http://www.kitimama-matome.net/index.rdf"},
    {"id": "www_kijomatomelog_com", "name": "鬼女まとめログ｜生活2chまとめブログ", "url": "http://www.kijomatomelog.com/index.rdf"},
    {"id": "f1jouhou2_blog_fc2_com", "name": "F1情報通", "url": "http://f1jouhou2.blog.fc2.com/?xml"},
    {"id": "inazumanews2_com", "name": "稲妻速報", "url": "http://inazumanews2.com/index.rdf"},
    {"id": "blog_livedoor_jp_kaikaihanno", "name": "カイカイ反応通信", "url": "http://blog.livedoor.jp/kaikaihanno/index.rdf"},
    {"id": "www_honmotakeshi_com", "name": "正義の見方", "url": "https://www.honmotakeshi.com/feed"},
    {"id": "www_saikyo_jump_com", "name": "最強ジャンプ放送局", "url": "http://www.saikyo-jump.com/index.rdf"},
    {"id": "blog_livedoor_jp_bbyakyu", "name": "竜速（りゅうそく）", "url": "http://blog.livedoor.jp/bbyakyu/index.rdf"},
    {"id": "aramame_net", "name": "あらまめ2ch", "url": "http://aramame.net/feed"},
    {"id": "blog_livedoor_jp_livejupiter2", "name": "なんJ（まとめては）いかんのか？", "url": "http://blog.livedoor.jp/livejupiter2/index.rdf"},
    {"id": "blog_livedoor_jp_fightersmatome", "name": "ポリー速報", "url": "http://blog.livedoor.jp/fightersmatome/index.rdf"},
    {"id": "geinoukame_blog_fc2_com", "name": "芸能かめはめ波", "url": "http://geinoukame.blog.fc2.com/?xml"},
    {"id": "jumpsokuhou_com", "name": "ジャンプ速報", "url": "http://jumpsokuhou.com/index.rdf"},
    {"id": "matomelotte_com", "name": "まとめロッテ！", "url": "http://matomelotte.com/index.rdf"},
    {"id": "g_matome_com", "name": "ガンダムまとめ速報", "url": "http://g-matome.com/index.rdf"},
    {"id": "gossip1_net", "name": "GOSSIP速報", "url": "http://gossip1.net/index.rdf"},
    {"id": "sakarabo_blog_jp", "name": "サカラボ | サッカーまとめ速報", "url": "http://sakarabo.blog.jp/index.rdf"},
    {"id": "kisslog2_com", "name": "キスログ", "url": "http://kisslog2.com/index.rdf"},
    {"id": "kimsoku_com", "name": "キムチ速報", "url": "http://kimsoku.com/index.rdf"},
    {"id": "www_calciomatome_net", "name": "カルチョまとめブログ", "url": "http://www.calciomatome.net/index.rdf"},
    {"id": "2ch_matomenews_com", "name": "まにゅそく 2chまとめニュース速報VIP", "url": "http://2ch-matomenews.com/feed"},
    {"id": "blog_livedoor_jp_love120331", "name": "はーとログ", "url": "http://blog.livedoor.jp/love120331/index.rdf"},
    {"id": "sutekinakijo_com", "name": "素敵な鬼女様", "url": "http://sutekinakijo.com/index.rdf"},
    {"id": "lions_matome_com_archives_category_e8_a5_bf_e6_ad_a6", "name": "やみ速@なんJ西武まとめ", "url": "https://lions-matome.com/archives/category/%E8%A5%BF%E6%AD%A6/feed"},
    {"id": "blog_livedoor_jp_coleblog", "name": "2ch東方スレ観測所", "url": "http://blog.livedoor.jp/coleblog/index.rdf"},
    {"id": "nofootynolife_net", "name": "NO FOOTY NO LIFE", "url": "http://nofootynolife.net/?xml"},
    {"id": "1000mg_jp", "name": "1000mg", "url": "http://1000mg.jp/feed"},
    {"id": "kidan_m_com", "name": "気団まとめ-噫無情-｜嫁・浮気・メシマズ", "url": "http://kidan-m.com/index.rdf"},
    {"id": "blog_livedoor_jp_kidandan", "name": "気団談", "url": "http://blog.livedoor.jp/kidandan/index.rdf"},
    {"id": "oniyomediary_com", "name": "鬼嫁日記〜2ch生活まとめ〜", "url": "http://oniyomediary.com/index.rdf"},
    {"id": "kaigainohannoublog_blog55_fc2_com", "name": "【海外の反応】　パンドラの憂鬱", "url": "http://kaigainohannoublog.blog55.fc2.com/?xml"},
    {"id": "kanmsu_com", "name": "かんむす！-艦隊これくしょんまとめブログ-", "url": "http://kanmsu.com/feed"},
    {"id": "www_otonarisoku_com", "name": "海外の反応　お隣速報", "url": "https://www.otonarisoku.com/feed"},
    {"id": "football_2ch_com", "name": "フットボール速報", "url": "http://football-2ch.com/index.rdf"},
    {"id": "www_negisoku_com", "name": "ネギ速", "url": "http://www.negisoku.com/index.rdf"},
    {"id": "blog_livedoor_jp_corez18c24_mili777", "name": "軍事・ミリタリー速報☆彡", "url": "http://blog.livedoor.jp/corez18c24-mili777/index.rdf"},
    {"id": "blog_livedoor_jp_hawksmatome", "name": "鷹速@ホークスまとめブログ", "url": "http://blog.livedoor.jp/hawksmatome/index.rdf"},
    {"id": "samuraisoccer_doorblog_jp", "name": "SAMURAI Footballers", "url": "http://samuraisoccer.doorblog.jp/index.rdf"},
    {"id": "xn_eckybzahmsm43ab5g5336c9iug_com", "name": "ニンテンドースイッチ速報", "url": "http://xn--eckybzahmsm43ab5g5336c9iug.com/feed"},
    {"id": "mona_news_com", "name": "モナニュース", "url": "http://mona-news.com/index.rdf"},
    {"id": "kiru2ch_com", "name": "２ちゃんを斬る！", "url": "http://kiru2ch.com/index.rdf"},
    {"id": "kijosoku_com", "name": "鬼女速", "url": "http://kijosoku.com/index.rdf"},
    {"id": "2logch_com", "name": "２ろぐちゃんねる", "url": "https://2logch.com/feed"},
    {"id": "world_samurai_com", "name": "海外サッカー日本人選手速報 WORLD SAMURAI", "url": "http://world-samurai.com/index.rdf"},
    {"id": "www_otoko_honne_com", "name": "オトコの本音｜生活2chまとめブログ", "url": "http://www.otoko-honne.com/index.rdf"},
    {"id": "nihonjinnanmin_com", "name": "日本人＿難民。～2ｃｈ読み物まとめ～", "url": "http://nihonjinnanmin.com/index.rdf"},
    {"id": "dng65_com", "name": "どんぐりこ - 海外の反応", "url": "http://dng65.com/?xml"},
    {"id": "www_netamesi_com", "name": "ネタめし.com", "url": "http://www.netamesi.com/index.rdf"},
    {"id": "blog_livedoor_jp_uwasainfo", "name": "芸能人の気になる噂", "url": "http://blog.livedoor.jp/uwasainfo/index.rdf"},
    {"id": "imas_cg_net", "name": "もばます！", "url": "http://imas-cg.net/index.rdf"},
    {"id": "chikakb_ldblog_jp", "name": "地下帝国-AKB48まとめ", "url": "http://chikakb.ldblog.jp/index.rdf"},
    {"id": "blog_livedoor_jp_bmaysu", "name": "ってなんじぇですかー", "url": "http://blog.livedoor.jp/bmaysu/index.rdf"},
    {"id": "i2chmeijin_blog_fc2_com", "name": "2ch名人", "url": "http://i2chmeijin.blog.fc2.com/?xml"},
    {"id": "totalmatomedia_blog_fc2_com", "name": "まとめでぃあ", "url": "http://totalmatomedia.blog.fc2.com/?xml"},
    {"id": "kandatasokuho_blog_fc2_com", "name": "カンダタ速報", "url": "http://kandatasokuho.blog.fc2.com/?xml"},
    {"id": "www2_bikechannel_info", "name": "ばいくちゃんねる", "url": "https://www2.bikechannel.info/feed"},
    {"id": "switchsoku_com", "name": "SWITCH速報", "url": "http://switchsoku.com/feed"},
    {"id": "animalch_net", "name": "どうぶつちゃんねる", "url": "http://animalch.net/index.rdf"},
    {"id": "www_gekiyaku_com", "name": "劇訳表示。", "url": "http://www.gekiyaku.com/index.rdf"},
    {"id": "checkmate_blog_com", "name": "チェックメイト | 2chまとめブログ", "url": "http://checkmate-blog.com/feed"},
    {"id": "anihatsu_com", "name": "アニはつ -アニメ発信場-", "url": "http://anihatsu.com/index.rdf"},
    {"id": "kemochan_com", "name": "けもちゃん", "url": "http://kemochan.com/feed"},
    {"id": "slotmania222_com", "name": "スロパチ乱舞", "url": "http://slotmania222.com/index.rdf"},
    {"id": "ouchinews_doorblog_jp", "name": "おうち速報", "url": "http://ouchinews.doorblog.jp/index.rdf"},
    {"id": "www_kijolifehack_com", "name": "オンナの本音｜2ch生活まとめ-鬼女ライフハック", "url": "http://www.kijolifehack.com/index.rdf"},
    {"id": "www_akb48mt_com", "name": "AKB48情報まとめたった", "url": "http://www.akb48mt.com/index.rdf"},
    {"id": "xxxkikimimixxx_blog_fc2_com", "name": "­海外反応　キキミミ", "url": "http://xxxkikimimixxx.blog.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_drazuli", "name": "暇は無味無臭の劇薬", "url": "http://blog.livedoor.jp/drazuli/index.rdf"},
    {"id": "mycarsoku_com", "name": "マイカー速報", "url": "http://mycarsoku.com/index.rdf"},
    {"id": "blog_livedoor_jp_ainbekker_news2", "name": "まとめニュースちゃんねるぷらす", "url": "http://blog.livedoor.jp/ainbekker-news2/index.rdf"},
    {"id": "sow_blog_jp", "name": "すらるど - 海外の反応", "url": "http://sow.blog.jp/index.rdf"},
    {"id": "lovelivematocha_com", "name": "ラブライブ！まとめちゃんねる！！", "url": "http://lovelivematocha.com/?xml"},
    {"id": "www_taiwannohannou_com", "name": "台湾の反応ブログ", "url": "http://www.taiwannohannou.com/index.rdf"},
    {"id": "bb_doorblog_jp", "name": "なんJ 野球をまとめてみたよ", "url": "http://bb.doorblog.jp/index.rdf"},
    {"id": "niccorin_com", "name": "ニッコリン", "url": "http://niccorin.com/index.rdf"},
    {"id": "visual_matome_com", "name": "V系まとめ速報", "url": "http://visual-matome.com/index.rdf"},
    {"id": "www_watch2chan_com", "name": "watch＠２ちゃんねる", "url": "http://www.watch2chan.com/index.rdf"},
    {"id": "ff14hikasensokuhou_com", "name": "FF14ひかせん速報", "url": "https://ff14hikasensokuhou.com/?xml"},
    {"id": "asiareaction_blog_fc2_com", "name": "（　｀ハ´）中国の反応ブログ", "url": "http://asiareaction.blog.fc2.com/?xml"},
    {"id": "football2channel_blog_fc2_com", "name": "蹴球まとめちゃんねる", "url": "http://football2channel.blog.fc2.com/?xml"},
    {"id": "watch_times_com", "name": "ウォッチちゃんねる", "url": "http://watch-times.com/feed"},
    {"id": "www_dimikai_com", "name": "海外の反応 ディミヌート", "url": "https://www.dimikai.com/?xml"},
    {"id": "www_all_nationz_com", "name": "海外の万国反応記＠海外の反応", "url": "http://www.all-nationz.com/index.rdf"},
    {"id": "blog_livedoor_jp_kokon55", "name": "SS古今東西", "url": "http://blog.livedoor.jp/kokon55/index.rdf"},
    {"id": "ssbiyori_blog_fc2_com", "name": "SSびより", "url": "http://ssbiyori.blog.fc2.com/?xml"},
    {"id": "galapagosjapan_blog_fc2_com", "name": "ガラパゴスジャパン - 海外の反応", "url": "http://galapagosjapan.blog.fc2.com/?xml"},
    {"id": "tchal_net", "name": "チャルバンを翻訳してみた【海外の反応】", "url": "http://tchal.net/index.rdf"},
    {"id": "ge_soku_com", "name": "げぇ速", "url": "http://ge-soku.com/index.rdf"},
    {"id": "nmb48_mtm_com", "name": "NMB48まとめスピリッツ", "url": "http://nmb48-mtm.com/index.rdf"},
    {"id": "www_japohan_net", "name": "じゃぽにか反応帳", "url": "http://www.japohan.net/feed"},
    {"id": "shingekikyojin_net", "name": "進撃の巨人ちゃんねる", "url": "http://shingekikyojin.net/index.rdf"},
    {"id": "foreignnews_biz_archives_cat_382414_xml", "name": "海外の反応 | 海外報道翻訳所", "url": "http://foreignnews.biz/archives/cat_382414.xml"},
    {"id": "tamenal_com", "name": "【海外の反応】タメナル", "url": "http://tamenal.com/feed"},
    {"id": "psneolog_com", "name": "PS4ProNEWS", "url": "http://psneolog.com/feed"},
    {"id": "chinareaction_com", "name": "中国四千年の反応！ 海外の反応ブログ", "url": "http://chinareaction.com/?xml"},
    {"id": "kaigainohannou_info", "name": "海外の反応 | 翻訳部", "url": "http://kaigainohannou.info/feed/"},
    {"id": "blog_livedoor_jp_soccerrevolution", "name": "サッカーレボリューション", "url": "http://blog.livedoor.jp/soccerrevolution/index.rdf"},
    {"id": "xn_p8j0cnw2b2487d_jp", "name": "どうぶつの森 みんなでポケットキャンプ (ポケ森)", "url": "http://xn--p8j0cnw2b2487d.jp/feed"},
    {"id": "ichliebefussball_net", "name": "ブンデスリーガ　ドイツの反応 Ich liebe Fussball!!", "url": "http://ichliebefussball.net/?xml"},
    {"id": "pokemon_goh_doorblog_jp", "name": "NEWSぽけまとめーる", "url": "http://pokemon-goh.doorblog.jp/index.rdf"},
    {"id": "squallchannel_doorblog_jp", "name": "スコールちゃんねる｜２ちゃんまとめブログ", "url": "http://squallchannel.doorblog.jp/index.rdf"},
    {"id": "inutomo11_com", "name": "なんJクエスト", "url": "http://inutomo11.com/index.rdf"},
    {"id": "heartlife_matome_com", "name": "はーとらいふ -出会い・子育て・生活系まとめ-", "url": "http://heartlife-matome.com/index.rdf"},
    {"id": "majimanjisokuhou_com", "name": "マジ卍速報", "url": "http://majimanjisokuhou.com/index.rdf"},
    {"id": "girlsreport_net", "name": "がーるずレポート - ガールズちゃんねるまとめブログ", "url": "http://girlsreport.net/index.rdf"},
    {"id": "www_mudainodocument_com", "name": "無題のドキュメント", "url": "http://www.mudainodocument.com/index.rdf"},
    {"id": "fesoku_net", "name": "ふぇー速", "url": "http://fesoku.net/index.rdf"},
    {"id": "www_okutta_net", "name": "億ったー", "url": "http://www.okutta.net/index.rdf"},
    {"id": "kijonikki_net", "name": "鬼女日記 -鬼女・修羅場・キチママ系まとめ-", "url": "http://kijonikki.net/index.rdf"},
    {"id": "kijyotown_net", "name": "鬼女タウン", "url": "http://kijyotown.net/index.rdf"},
    {"id": "kijorabu_com", "name": "鬼女乱舞-キチママ・鬼女・修羅場系まとめ-", "url": "http://kijorabu.com/index.rdf"},
    {"id": "kijyomatome_ch_com", "name": "鬼女まとめちゃんねる｜生活2chまとめブログ", "url": "http://kijyomatome-ch.com/index.rdf"},
    {"id": "kijyokatu_com", "name": "鬼女の生活｜2ch修羅場まとめブログ", "url": "http://kijyokatu.com/index.rdf"},
    {"id": "kijyomita_com", "name": "鬼女はみた -修羅場・恋愛・育児系まとめサイト-", "url": "http://kijyomita.com/index.rdf"},
    {"id": "kizyonouwaki_com", "name": "鬼女の浮気速報｜ 2ch鬼女・キチママ・修羅場まとめ", "url": "http://kizyonouwaki.com/index.rdf"},
    {"id": "kijyotsubu_net", "name": "鬼女のつぶやき〜2ch鬼女・キチママ・生活まとめ〜", "url": "http://kijyotsubu.net/index.rdf"},
    {"id": "kijonotakuhaibin_com", "name": "鬼女の宅配便 - 修羅場・浮気からほのぼの系まで[まとめサイト]", "url": "http://kijonotakuhaibin.com/index.rdf"},
    {"id": "kijyokaigi_com", "name": "鬼女の井戸端会議-鬼女、キチママ、修羅場、生活まとめ-", "url": "http://kijyokaigi.com/index.rdf"},
    {"id": "2chmatome_net", "name": "長編にちゃんまとめ　修羅場・浮気", "url": "http://2chmatome.net/index.rdf"},
    {"id": "tsurimatome_com", "name": "釣りまとめ速報", "url": "http://tsurimatome.com/index.rdf"},
    {"id": "chomangasokuho_blog_jp", "name": "超・マンガ速報", "url": "http://chomangasokuho.blog.jp/index.rdf"},
    {"id": "shitsumon_aru_net", "name": "質問ある？まとめ速報", "url": "http://shitsumon-aru.net/index.rdf"},
    {"id": "blog_livedoor_jp_sky_wing2010_geinou", "name": "芸能人ニュース速報", "url": "http://blog.livedoor.jp/sky_wing2010-geinou/index.rdf"},
    {"id": "koredakedeok_blog_jp", "name": "芸能ネタはこれだけでおｋ", "url": "http://koredakedeok.blog.jp/index.rdf"},
    {"id": "bnewg_sokuho_org", "name": "爆NEWゲーム速報", "url": "http://bnewg.sokuho.org/index.rdf"},
    {"id": "kidanlog_com", "name": "気団ログ", "url": "http://kidanlog.com/feed"},
    {"id": "kininaru_geinou_m_blog_jp", "name": "気になる芸能まとめ", "url": "http://kininaru-geinou-m.blog.jp/index.rdf"},
    {"id": "kininatta2chmatome_doorblog_jp", "name": "気になった生活スレまとめ", "url": "http://kininatta2chmatome.doorblog.jp/index.rdf"},
    {"id": "hiraganakeyaki_blog_jp", "name": "日向坂46まとめ速報", "url": "http://hiraganakeyaki.blog.jp/index.rdf"},
    {"id": "seikeidouga_blog_jp", "name": "政経ワロスまとめニュース♪", "url": "http://seikeidouga.blog.jp/index.rdf"},
    {"id": "polite_kijyo_net", "name": "拝啓、鬼女様", "url": "http://polite-kijyo.net/index.rdf"},
    {"id": "jyouhouya3_net", "name": "情報屋さん。", "url": "http://jyouhouya3.net/feed"},
    {"id": "www_recosoku_com", "name": "恋愛速報｜2chまとめサイト", "url": "http://www.recosoku.com/index.rdf"},
    {"id": "kitizawa_com", "name": "基地沢直樹-復讐・修羅場・DQN返し【2chスカッとする話まとめ】", "url": "http://kitizawa.com/index.rdf"},
    {"id": "uwasakijo_net", "name": "噂の鬼女様", "url": "http://uwasakijo.net/index.rdf"},
    {"id": "heekogirl_blog_fc2_com", "name": "2ちゃんねるまとめ 名前はまだない", "url": "http://heekogirl.blog.fc2.com/?xml"},
    {"id": "shurabanote_com", "name": "修羅場ノート-2ch修羅場・復讐まとめ-", "url": "http://shurabanote.com/index.rdf"},
    {"id": "shurabana_com", "name": "修羅場な話まとめ", "url": "http://shurabana.com/index.rdf"},
    {"id": "syurabahazard_com", "name": "修羅場ハザード -復讐・DQN返し・衝撃系まとめ-", "url": "http://syurabahazard.com/index.rdf"},
    {"id": "shurabach_org", "name": "修羅場ちゃんねる", "url": "http://shurabach.org/index.rdf"},
    {"id": "densetsunokijo_net", "name": "伝説の鬼女 ～修羅場・キチママ・生活まとめ～", "url": "http://densetsunokijo.net/index.rdf"},
    {"id": "syuramama_com", "name": "修羅ママ速報", "url": "http://syuramama.com/index.rdf"},
    {"id": "www_matometemitatta_com", "name": "一回は一回です。。｜ 2ch修羅場・復讐まとめ", "url": "http://www.matometemitatta.com/index.rdf"},
    {"id": "kyousoku_net", "name": "今日速2ch", "url": "http://kyousoku.net/index.rdf"},
    {"id": "hannichigukoku_info", "name": "反日愚国　恨寓瘻", "url": "http://hannichigukoku.info/?xml"},
    {"id": "labradorsokuho_net", "name": "ラブラドール速報～生活・修羅場・鬼女まとめ～", "url": "http://labradorsokuho.net/index.rdf"},
    {"id": "monhan_mhw_com", "name": "モンハンワールド2chまとめ速報 - MHW攻略", "url": "http://monhan-mhw.com/index.rdf"},
    {"id": "nogitweet_com", "name": "乃木坂46まとめんばー", "url": "http://nogitweet.com/feed"},
    {"id": "maji_w_blog_jp", "name": "マジワロ速報", "url": "http://maji-w.blog.jp/index.rdf"},
    {"id": "purinisdrink_net", "name": "プリンはのみものです。｜にちゃん生活まとめ", "url": "http://purinisdrink.net/index.rdf"},
    {"id": "masked_blog_jp", "name": "ヒーローNEWS", "url": "http://masked.blog.jp/index.rdf"},
    {"id": "gomepachi_com", "name": "パチンコ激震速報", "url": "http://gomepachi.com/index.rdf"},
    {"id": "pazusoku_blog_fc2_com", "name": "パズ速 -パズドラ情報まとめ-", "url": "http://pazusoku.blog.fc2.com/?xml"},
    {"id": "haronbouchannel_com", "name": "ハロン棒ch　-競馬まとめ-", "url": "http://haronbouchannel.com/index.rdf"},
    {"id": "celery_marine_net", "name": "セロリのマリネ", "url": "http://celery-marine.net/feed"},
    {"id": "sukashuraba_net", "name": "スカッとする修羅場まとめ", "url": "http://sukashuraba.net/index.rdf"},
    {"id": "sukattojapan_com", "name": "スカッとじゃぱん", "url": "http://sukattojapan.com/index.rdf"},
    {"id": "dorosoku_com", "name": "ドロドロ速報-鬼女・不倫・浮気・修羅場系まとめ", "url": "http://dorosoku.com/index.rdf"},
    {"id": "pachislotzone_com", "name": "スロパチゾーン　パチンコパチスロまとめ", "url": "http://pachislotzone.com/feed"},
    {"id": "girls2chmatome_net", "name": "ガールズにちゃんまとめ～生活・鬼女～", "url": "http://girls2chmatome.net/index.rdf"},
    {"id": "kichimama_net", "name": "キチママまとめちゃんねる", "url": "http://kichimama.net/index.rdf"},
    {"id": "sonicch_com", "name": "ソニック速報", "url": "http://sonicch.com/index.rdf"},
    {"id": "girlsvip_matome_com", "name": "ガールズVIPまとめ", "url": "http://girlsvip-matome.com/index.rdf"},
    {"id": "orufemorufenz_com", "name": "オルフェンズの仔～～競馬ネタ予想まとめ", "url": "http://orufemorufenz.com/index.rdf"},
    {"id": "otanew_jp", "name": "オタクニュース", "url": "http://otanew.jp/index.rdf"},
    {"id": "www_anige_sokuhouvip_com", "name": "アニゲー速報", "url": "http://www.anige-sokuhouvip.com/?xml"},
    {"id": "www_moeruasia_net", "name": "もえるあじあ(･∀･)", "url": "https://www.moeruasia.net/index.rdf"},
    {"id": "netmorie_com", "name": "もりえってぃー", "url": "http://netmorie.com/feed"},
    {"id": "magical_news_blog_jp", "name": "まじかる☆にゅーす", "url": "http://magical-news.blog.jp/index.rdf"},
    {"id": "pomepuu_net", "name": "ぽめぷー速報 ～修羅場・キチママ・生活まとめ～", "url": "http://pomepuu.net/index.rdf"},
    {"id": "parusoku_com", "name": "ぱる速報", "url": "http://parusoku.com/index.rdf"},
    {"id": "nyankosokuho_com", "name": "にゃんこ速報～修羅場・キチママ・生活まとめ～", "url": "http://nyankosokuho.com/index.rdf"},
    {"id": "blog_livedoor_jp_nanj_dream", "name": "なんJ Dream", "url": "http://blog.livedoor.jp/nanj_dream/index.rdf"},
    {"id": "blog_livedoor_jp_whoistrueenemy", "name": "すまいる(^-^)ぶろぐ", "url": "http://blog.livedoor.jp/whoistrueenemy/index.rdf"},
    {"id": "neta_ru_com", "name": "ねたーる", "url": "http://neta-ru.com/feed"},
    {"id": "gabiyori_com", "name": "げーあにびより｜ゲームやアニメの評価・感想まとめ", "url": "http://gabiyori.com/feed"},
    {"id": "kimagure_kijyo_com", "name": "きまぐれ鬼女-鬼女・不倫・浮気・修羅場系まとめ", "url": "http://kimagure-kijyo.com/index.rdf"},
    {"id": "crx7601_com", "name": "おーるじゃんる", "url": "http://crx7601.com/index.rdf"},
    {"id": "www_oumaga_times_com", "name": "おうまがタイムズ", "url": "http://www.oumaga-times.com/index.rdf"},
    {"id": "mashlife_doorblog_jp", "name": "mashlife通信", "url": "http://mashlife.doorblog.jp/index.rdf"},
    {"id": "eegg_fun", "name": "easterEgg", "url": "http://eegg.fun/index.rdf"},
    {"id": "you1news_com", "name": "U-1 NEWS", "url": "https://you1news.com/feed"},
    {"id": "blog_livedoor_jp_g_ogasawara", "name": "NaNじぇい", "url": "http://blog.livedoor.jp/g_ogasawara/index.rdf"},
    {"id": "npb_news_com", "name": "NPB NEWS@なんJまとめ", "url": "http://npb-news.com/index.rdf"},
    {"id": "blog_livedoor_jp_hktmatomemon", "name": "HKTまとめもん【HKT48のまとめ】", "url": "http://blog.livedoor.jp/hktmatomemon/index.rdf"},
    {"id": "ss_navi_com", "name": "SSなび", "url": "http://ss-navi.com/?xml"},
    {"id": "www_fx2ch_net", "name": "FX2ちゃんねる|投資系2chまとめ", "url": "http://www.fx2ch.net/feed"},
    {"id": "mizuhonokuni2ch_com", "name": "MIZUHO no KUNI ≪2ch≫特亜ニュース", "url": "http://mizuhonokuni2ch.com/feed"},
    {"id": "kaigaino_net", "name": "世界の反応", "url": "https://kaigaino.net/feed"},
    {"id": "mudasure_com", "name": "ムダスレ無き改革", "url": "http://mudasure.com/?xml"},
    {"id": "kichimama_life_com", "name": "キチママらいふ－浮気・不倫・修羅場－", "url": "http://kichimama-life.com/index.rdf"},
    {"id": "no_one_no_net", "name": "QQQ(海外の反応)", "url": "http://no-one-no.net/index.rdf"},
    {"id": "newsoku_blog", "name": "NEWSOKU BLOG", "url": "https://newsoku.blog/feed"},
    {"id": "chiwasoku_com", "name": "ちわわ速報｜修羅場・鬼女・２ちゃん生活まとめ", "url": "http://chiwasoku.com/index.rdf"},
    {"id": "konoyubitomare_jp", "name": "コノユビ", "url": "http://konoyubitomare.jp/index.rdf"},
    {"id": "romeodensetsu_com", "name": "ロミオ伝説｜にちゃんまとめ", "url": "http://romeodensetsu.com/index.rdf"},
    {"id": "ramen2ch_com", "name": "ラーメン速報｜2chまとめブログ", "url": "http://ramen2ch.com/?xml"},
    {"id": "shuraba_dendo_com", "name": "修羅場まとめの殿堂～離婚・復讐・不倫・浮気まとめ～", "url": "http://shuraba-dendo.com/index.rdf"},
    {"id": "totalwar_doorblog_jp", "name": "/)；｀ω´)＜国家総動員報", "url": "http://totalwar.doorblog.jp/index.rdf"},
    {"id": "www_kokunanmonomousu_com", "name": "国難にあってもの申す！！", "url": "http://www.kokunanmonomousu.com/index.rdf"},
    {"id": "rakukan_net", "name": "楽韓Web", "url": "http://rakukan.net/index.rdf"},
    {"id": "jishin_yogen_com", "name": "大地震・前兆・予言.com", "url": "https://jishin-yogen.com/?xml"},
    {"id": "kaigai_otaku_jp_category_korea", "name": "韓国の反応 | 海外のリアクション", "url": "http://kaigai-otaku.jp/category/korea/feed"},
    {"id": "kaigainoomaera_com", "name": "海外のお前ら　海外の反応", "url": "https://kaigainoomaera.com/?xml"},
    {"id": "kasegeru_blog_jp", "name": "稼げるまとめ速報", "url": "http://kasegeru.blog.jp/index.rdf"},
    {"id": "blog_livedoor_jp_kaigaisoku", "name": "翻訳ちゃんねる | 海外の反応まとめブログ", "url": "http://blog.livedoor.jp/kaigaisoku/index.rdf"},
    {"id": "thainokoe_com", "name": "タイの反応 タイコエ", "url": "https://thainokoe.com/feed/"},
    {"id": "2chnewsblog_blog_jp", "name": "２ちゃんねるニュース超速まとめ＋", "url": "http://2chnewsblog.blog.jp/index.rdf"},
    {"id": "sumaburayasan_com", "name": "スマブラ屋さん | スマブラSPまとめ攻略", "url": "http://sumaburayasan.com/index.rdf"},
    {"id": "ginnga_blog_jp", "name": "銀河系まとめブログ", "url": "http://ginnga.blog.jp/index.rdf"},
    {"id": "www_jisaka_com", "name": "汎用型自作PCまとめ", "url": "http://www.jisaka.com/index.rdf"},
    {"id": "warotanien_net", "name": "わろたにえん速報", "url": "https://warotanien.net/feed"},
    {"id": "nmb48matome_net", "name": "NMB48まとめといたで", "url": "http://nmb48matome.net/feed"},
    {"id": "china_aggressor_nation_blog_jp", "name": "中国 ~100年遅れの帝国主義~ まとめ", "url": "http://china-aggressor-nation.blog.jp/index.rdf"},
    {"id": "toushichannel_net", "name": "投資ちゃんねる", "url": "http://toushichannel.net/index.rdf"},
    {"id": "kichimama_com", "name": "キチママ警報 -キチママ・生活系まとめ-", "url": "http://kichimama.com/index.rdf"},
    {"id": "jumpmatome2ch_biz", "name": "ジャンプまとめ速報", "url": "http://jumpmatome2ch.biz/feed"},
    {"id": "kaikore_blogspot_com_feeds_posts_default_alt", "name": "かいこれ！ 海外の反応 コレクション", "url": "https://kaikore.blogspot.com/feeds/posts/default?alt=rss"},
    {"id": "monomi_news_blog_jp", "name": "物見ニュース", "url": "http://monomi-news.blog.jp/index.rdf"},
    {"id": "xxhuyuzero_jp", "name": "フィギュアスケートまとめ零", "url": "http://xxhuyuzero.jp/feed"},
    {"id": "www_keyakizaka46matomerabo_com", "name": "欅坂46まとめラボ", "url": "http://www.keyakizaka46matomerabo.com/index.rdf"},
    {"id": "bluebluesunset_blog_fc2_com", "name": "ねこのあまやどり", "url": "http://bluebluesunset.blog.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_amatsubushi", "name": "あまつぶし", "url": "http://blog.livedoor.jp/amatsubushi/index.rdf"},
    {"id": "kokopyon_net", "name": "あぁ^～こころがぴょんぴょんするんじゃぁ^～", "url": "http://kokopyon.net/?xml"},
    {"id": "na2ka4_blog_fc2_com", "name": "あのころの", "url": "http://na2ka4.blog.fc2.com/?xml"},
    {"id": "airlinehonpo_blog_fc2_com", "name": "エアライン本舗", "url": "http://airlinehonpo.blog.fc2.com/?xml"},
    {"id": "money_life_doorblog_jp", "name": "マネーライフ2ch|クレジット関連・お金関係", "url": "http://money-life.doorblog.jp/index.rdf"},
    {"id": "ideal2ch_livedoor_biz", "name": "理想ちゃんねる", "url": "http://ideal2ch.livedoor.biz/index.rdf"},
    {"id": "moeponzu_com", "name": "もえぽんず。", "url": "http://moeponzu.com/?xml"},
    {"id": "www_movient_net", "name": "映画.net", "url": "http://www.movient.net/index.rdf"},
    {"id": "www_gadget2ch_com", "name": "ガジェット2ch", "url": "http://www.gadget2ch.com/index.rdf"},
    {"id": "blog_livedoor_jp_qmanews", "name": "くまニュース", "url": "http://blog.livedoor.jp/qmanews/index.rdf"},
    {"id": "suresuta_jp", "name": "すれすた", "url": "http://suresuta.jp/feed"},
    {"id": "nijimen_net", "name": "にじめん", "url": "http://nijimen.net/index.rdf"},
    {"id": "pachinkopachisro_com", "name": "パチンコ・パチスロ.com", "url": "http://pachinkopachisro.com/index.rdf"},
    {"id": "de_baystars_doorblog_jp", "name": "De速", "url": "http://de-baystars.doorblog.jp/index.rdf"},
    {"id": "www_gurum_biz", "name": "おいしいお", "url": "http://www.gurum.biz/index.rdf"},
    {"id": "blog_livedoor_jp_bluejay01_review", "name": "PCパーツまとめ", "url": "http://blog.livedoor.jp/bluejay01-review/index.rdf"},
    {"id": "ebitsu_net", "name": "えび通", "url": "http://ebitsu.net/index.rdf"},
    {"id": "blog_livedoor_jp_aushio_archives_cat_150742_xml", "name": "つれさか　-徒然サッカー雑記- - 海外の反応", "url": "http://blog.livedoor.jp/aushio/archives/cat_150742.xml"},
    {"id": "ikeike2ch_jp", "name": "イケイケ速報", "url": "http://ikeike2ch.jp/index.rdf"},
    {"id": "iroirokeiba_blog_fc2_com", "name": "ギャン速2ch　～競馬まとめブログ～", "url": "http://iroirokeiba.blog.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_akb48rhyh", "name": "AKB48地下速報", "url": "http://blog.livedoor.jp/akb48rhyh/index.rdf"},
    {"id": "moeaudio_blog29_fc2_com", "name": "Sound Field", "url": "http://moeaudio.blog29.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_otomatome", "name": "音まとめ", "url": "http://blog.livedoor.jp/otomatome/index.rdf"},
    {"id": "polandball_blog_fc2_com", "name": "ポーランドボール 翻訳", "url": "http://polandball.blog.fc2.com/?xml"},
    {"id": "overseasresponse_com", "name": "海外の反応ジャーナル", "url": "https://overseasresponse.com/feed"},
    {"id": "www_babymetal_darake_com", "name": "べビメタだらけの・・・", "url": "https://www.babymetal-darake.com/feed"},
    {"id": "blog_game084_com", "name": "ゲーム攻略のまるはし", "url": "http://blog.game084.com/index.rdf"},
    {"id": "ssimas_blog_fc2_com", "name": "全ては跡地。", "url": "http://ssimas.blog.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_zzcj", "name": "海外反応！　I LOVE JAPAN", "url": "http://blog.livedoor.jp/zzcj/index.rdf"},
    {"id": "yaraon_blog_com", "name": "やらおん！", "url": "http://yaraon-blog.com/feed"},
    {"id": "blog_livedoor_jp_umadori0726", "name": "馬鳥速報", "url": "http://blog.livedoor.jp/umadori0726/index.rdf"},
    {"id": "blog_livedoor_jp_pocketcamp", "name": "TweetPocket", "url": "http://blog.livedoor.jp/pocketcamp/index.rdf"},
    {"id": "nanj_hero_com", "name": "なんJ HERO", "url": "http://nanj-hero.com/index.rdf"},
    {"id": "otakamu_com", "name": "オタカム", "url": "http://otakamu.com/index.rdf"},
    {"id": "blog_livedoor_jp_itsoku", "name": "IT速報", "url": "http://blog.livedoor.jp/itsoku/index.rdf"},
    {"id": "pawawa_sokuho_org_index20", "name": "ぱわわ速報", "url": "http://pawawa.sokuho.org/index20.rdf"},
    {"id": "beasoku_com_index20", "name": "ベア速", "url": "http://beasoku.com/index20.rdf"},
    {"id": "matmebae_net_index20", "name": "まとめ映ぇぇ", "url": "http://matmebae.net/index20.rdf"},
    {"id": "mildch_com", "name": "マイルドちゃんねる", "url": "http://mildch.com/index.rdf"},
    {"id": "blog_livedoor_jp_sasuga801_koukokugyoukai", "name": "アドちゃんねる", "url": "http://blog.livedoor.jp/sasuga801-koukokugyoukai/index.rdf"},
    {"id": "blog_livedoor_jp_ikuzitter", "name": "いくじったー", "url": "http://blog.livedoor.jp/ikuzitter/index.rdf"},
    {"id": "bigbangchannel_net", "name": "ビッグバンちゃんねる", "url": "http://bigbangchannel.net/index.rdf"},
    {"id": "labaq_com_archives_cat_50037985_xml", "name": "らばQ - 海外の反応", "url": "http://labaq.com/archives/cat_50037985.xml"},
    {"id": "stumbleon_blog_fc2_com", "name": "こんなニュースにでくわした", "url": "http://stumbleon.blog.fc2.com/?xml"},
    {"id": "baychannel_blog_fc2_com", "name": "今日も荷物が届かない。@海外の反応", "url": "http://baychannel.blog.fc2.com/?xml"},
    {"id": "babymetalize_com", "name": "BABYMETALIZE", "url": "http://babymetalize.com/feed"},
    {"id": "www_kattobi_japan_com", "name": "【動画翻訳】かっとびジャパン - 海外の反応", "url": "http://www.kattobi-japan.com/index.rdf"},
    {"id": "chokkanteki_com", "name": "かいちょく", "url": "https://chokkanteki.com/feed/"},
    {"id": "anicai_jp_archives_category_kaigaihanou", "name": "海外の反応  –  あにかい | アニメ・ゲーム海外の反応まとめ", "url": "https://anicai.jp/archives/category/kaigaihanou/feed"},
    {"id": "kaigai_nippon_com_feed", "name": "海外の反応 ニッポンの翻訳", "url": "http://kaigai-nippon.com/?feed=rss2"},
    {"id": "lolninja_net_category_e6_b5_b7_e5_a4_96_e3_81_ae_e5_8f_8d_e5_bf_9c", "name": "海外の反応 | LOL忍者", "url": "https://lolninja.net/category/%e6%b5%b7%e5%a4%96%e3%81%ae%e5%8f%8d%e5%bf%9c/feed/"},
    {"id": "eigotoka_com", "name": "eigotoka 　〜海外スレ翻訳所〜", "url": "https://eigotoka.com/feed"},
    {"id": "blog_livedoor_jp_kashikou", "name": "「日中文化交流」と書いてオタ活動と読む", "url": "http://blog.livedoor.jp/kashikou/index.rdf"},
    {"id": "kakugeblog_blog_jp_archives_cat_1131921_xml", "name": "格ゲーブログ（仮） - 海外の反応", "url": "http://kakugeblog.blog.jp/archives/cat_1131921.xml"},
    {"id": "siokan5000_blog_fc2_com", "name": "塩韓スポーツ", "url": "http://siokan5000.blog.fc2.com/?xml"},
    {"id": "twfunnymovie_com", "name": "新世代台湾人の反応", "url": "https://twfunnymovie.com/?xml"},
    {"id": "mykeibamemory_blog_fc2_com", "name": "海外の小反応", "url": "http://mykeibamemory.blog.fc2.com/?xml"},
    {"id": "chinesestyle_seesaa_net", "name": "中国人の戯言～大中華思想～", "url": "http://chinesestyle.seesaa.net/index.rdf"},
    {"id": "closetotokyo_blog_fc2_com", "name": "フォゲラバリ（海外の反応）", "url": "http://closetotokyo.blog.fc2.com/?xml"},
    {"id": "blog_livedoor_jp_sekaiminzoku", "name": "世界の憂鬱 海外・韓国の反応", "url": "http://blog.livedoor.jp/sekaiminzoku/index.rdf"},
    {"id": "iwado_work", "name": "イワド新報", "url": "https://iwado.work/feed"},
    {"id": "coffeehonyaku_blogspot_com_feeds_posts_default_alt_rss_orderby_published", "name": "コーヒーと翻訳", "url": "https://coffeehonyaku.blogspot.com/feeds/posts/default?alt=rss&orderby=published"},
    {"id": "www_kagerou_biz", "name": "海外の反応で英語の勉強", "url": "http://www.kagerou.biz/index.rdf"},
    {"id": "watamotetrans_livedoor_blog", "name": "蠱惑の壺 | 漫画・アニメ海外の反応まとめ", "url": "http://watamotetrans.livedoor.blog/index.rdf"},
    {"id": "kankokunohannou_org", "name": "かんこく！　韓国の反応翻訳ブログ", "url": "https://kankokunohannou.org/?xml"},
    {"id": "kaigaiwelcome_com", "name": "海外さんいらっしゃい　海外の反応", "url": "https://kaigaiwelcome.com/?xml"},
    {"id": "sarasoku_net", "name": "世界の反応　さら速", "url": "http://sarasoku.net/feed/"},
    {"id": "k_han_com", "name": "ボイスオブコリア韓国の反応翻訳まとめ", "url": "https://k-han.com/?xml"},
    {"id": "hokkorihann_com", "name": "ほっこりはん", "url": "https://hokkorihann.com/?xml"},
    {"id": "kaigaihannnoumatome_ldblog_jp", "name": "YouTube海外の反応まとめ", "url": "http://kaigaihannnoumatome.ldblog.jp/index.rdf"},
    {"id": "pankori_net", "name": "パンコリ", "url": "https://pankori.net/feed/"},
    {"id": "muryou_tanoshimu_com_category_kankoku", "name": "韓国の反応  |  海外トークログ", "url": "https://muryou-tanoshimu.com/category/kankoku/feed/"},
    {"id": "grewgrehrg_blog_fc2_com", "name": "ミク廃！！", "url": "https://grewgrehrg.blog.fc2.com/?xml"},
    {"id": "www_kaisupo_com_rss_xml_alt", "name": "海外の反応スポーツ", "url": "https://www.kaisupo.com/rss.xml?alt=rss"},
    {"id": "koreaction_net", "name": "KoreAction", "url": "https://koreaction.net/feed/"},
    {"id": "kaigaichan_net_feed", "name": "かいがいchan", "url": "https://kaigaichan.net/feed/rss"},
    {"id": "grandfleet_info", "name": "航空万能論GF", "url": "https://grandfleet.info/feed/"},
    {"id": "game_honyaku_com", "name": "ゲームほんやくコンニャク", "url": "http://game-honyaku.com/feed/"},
    {"id": "toku_log_com_feed_cat_5", "name": "海外の反応 | 海外トークログ", "url": "https://toku-log.com/feed/?cat=-5"},
    {"id": "kaigai_otaku_jp_category_world", "name": "海外の反応 | 海外のリアクション", "url": "http://kaigai-otaku.jp/category/world/feed"},
    {"id": "incident_wo_com", "name": "日本第一！ニュース録", "url": "https://incident-wo.com/feed/"},
    {"id": "a_la_carte_blog_jp", "name": "ちまたのアラカルト", "url": "http://a-la-carte.blog.jp/index.rdf"},
    {"id": "himayomi_com", "name": "暇読み", "url": "https://himayomi.com/feed"},
    {"id": "gurumato_net", "name": "グルメまとめの「ぐるまと！」", "url": "http://gurumato.net/feed"},
    {"id": "tiktok_p_blog_jp", "name": "まとめＴｏｋ", "url": "http://tiktok-p.blog.jp/index.rdf"},
    {"id": "xn_2ch_2d8eo32c60z_xyz", "name": "2ch大相撲", "url": "http://xn--2ch-2d8eo32c60z.xyz/atom.xml"},
    {"id": "beikokukabu_etf_matome_com", "name": "米国株ETFまとめ速報", "url": "http://beikokukabu-etf-matome.com/index.rdf"},
    {"id": "imasoku_com", "name": "いま速", "url": "https://imasoku.com/feed"},
    {"id": "onjsummarynet_net", "name": "おんｊサマリー＠なんｊホークスまとめ", "url": "http://onjsummarynet.net/index.rdf"},
    {"id": "showbizjapan_blog_fc2_com", "name": "SHOWBIZ JAPAN", "url": "http://showbizjapan.blog.fc2.com/?xml"},
    {"id": "hellopronews_blog_jp", "name": "ハロプロニュース", "url": "http://hellopronews.blog.jp/index.rdf"},
    {"id": "revuestarlightre_com", "name": "日刊バーチャル", "url": "http://revuestarlightre.com/index.rdf"},
    {"id": "marasoku_info", "name": "マラソン速報", "url": "http://marasoku.info/index.rdf"},
    {"id": "rejapan_blog_jp", "name": "Revival Japan 日本復活を叫ぶ", "url": "http://rejapan.blog.jp/index.rdf"},
    {"id": "keyakizaka46ch_jp", "name": "櫻坂46まとめちゃんねる", "url": "https://keyakizaka46ch.jp/feed"},
    {"id": "ladyplus_xyz", "name": "宵越しの銭はもたぬ速報", "url": "https://ladyplus.xyz/feed/"},
    {"id": "www_manga_to_anime_net", "name": "まんがとあにめ", "url": "http://www.manga-to-anime.net/index.rdf"},
    {"id": "j_seiji_blog_jp", "name": "なんJ政治ネタまとめ", "url": "http://j-seiji.blog.jp/index.rdf"},
    {"id": "smasoku_blog_jp", "name": "スマッシュ速報", "url": "http://smasoku.blog.jp/index.rdf"},
    {"id": "blog_livedoor_jp_tohopoke", "name": "徒歩のポケモンまとめブログ", "url": "http://blog.livedoor.jp/tohopoke/index.rdf"},
    {"id": "srwmatome_com", "name": "スパロボまとめ速報", "url": "https://srwmatome.com/feed"},
    {"id": "news_bomb_com", "name": "News Bomb｜ニュースまとめサイト", "url": "http://news-bomb.com/feed"},
    {"id": "oto_ch_net", "name": "音ちゃんねる", "url": "https://oto-ch.net/feed"},
    {"id": "umasoku_com", "name": "うま速@競馬まとめブログ", "url": "https://umasoku.com/feed"},
    {"id": "highfashionmens_com", "name": "ハイファッションちゃんねる", "url": "https://highfashionmens.com/feed"},
    {"id": "gfoodd_com", "name": "明日は何を食べようか", "url": "http://gfoodd.com/feed"},
    {"id": "www_mutyun_com", "name": "mutyunのゲーム+αブログ", "url": "https://www.mutyun.com/feed"},
    {"id": "sfgidf_blog_jp", "name": "ピンキリ速報 - レスバもまとめる5chブログ -", "url": "http://sfgidf.blog.jp/index.rdf"},
    {"id": "tapittalk_com", "name": "くろす速報", "url": "https://tapittalk.com/feed/"},
    {"id": "financial_c_net", "name": "守銭奴日報", "url": "https://financial-c.net/feed"},
    {"id": "www_mgif_jp", "name": "エムジフ～音ゲー情報局(MGIF)～", "url": "http://www.mgif.jp/index.rdf"},
    {"id": "zatuzatu_com", "name": "雑なまとめ", "url": "https://zatuzatu.com/feed"},
    {"id": "pokemon_matome_net", "name": "ぽけりん＠ポケモンソードシールド(剣盾)まとめ", "url": "http://pokemon-matome.net/index.rdf"},
    {"id": "blog_livedoor_jp_japan_and_korea", "name": "日本と韓国は敵か？味方か？", "url": "http://blog.livedoor.jp/japan_and_korea/index.rdf"},
    {"id": "blog_livedoor_jp_bbmt46", "name": "BABYMETALまとめもりー", "url": "http://blog.livedoor.jp/bbmt46/index.rdf"},
    {"id": "himatubusokuho_blog_jp", "name": "暇つぶ速報", "url": "http://himatubusokuho.blog.jp/index.rdf"},
    {"id": "lucky318b_m50_coreserver_jp", "name": "Glauber通信", "url": "http://lucky318b.m50.coreserver.jp/feed"},
    {"id": "katasumisokuhou_blog_jp", "name": "かたすみ速報", "url": "http://katasumisokuhou.blog.jp/index.rdf"},
    {"id": "www_maruhorror_com", "name": "まるたろうの怖い心霊ブログ", "url": "http://www.maruhorror.com/index.rdf"},
    {"id": "a711_work", "name": "CRただいま速報", "url": "http://a711.work/index.rdf"},
    {"id": "world_study_jp", "name": "世界歴史ちゃんねる", "url": "https://world-study.jp/feed"},
    {"id": "arknights_more_gamer_com", "name": "アークナイツまとめタイムズ", "url": "http://arknights.more-gamer.com/feed"},
    {"id": "moti_soku_com", "name": "気になるVtuber速報", "url": "https://moti-soku.com/feed/"},
    {"id": "www_news_toranomaki_net_feed", "name": "とらのまき", "url": "https://www.news-toranomaki.net/?feed=rss2"},
    {"id": "blog_livedoor_jp_abechan_matome", "name": "まとめ安倍速報", "url": "http://blog.livedoor.jp/abechan_matome/index.rdf"},
    {"id": "tachiyomitoday_com", "name": "今日の立ち読みまとめ", "url": "http://tachiyomitoday.com/index.rdf"},
    {"id": "umaumanews_com", "name": "競馬まとめのまとめ", "url": "http://umaumanews.com/feed"},
    {"id": "pirori2ch_com", "name": "ぴろり速報", "url": "http://pirori2ch.com/feed"},
    {"id": "syuukyuu_com", "name": "蹴球的情報ch", "url": "https://syuukyuu.com/feed"},
    {"id": "www_fatego_matome_com", "name": "FGOまとめ速報", "url": "https://www.fatego-matome.com/feed/"},
    {"id": "blog_livedoor_jp_nanjsyurai", "name": "なんJ襲来", "url": "http://blog.livedoor.jp/nanjsyurai/index.rdf"},
    {"id": "cggekijo_blog_fc2_com", "name": "でれげき -シンデレラガールズ劇場まとめ-", "url": "http://cggekijo.blog.fc2.com/?xml"},
    {"id": "fate_grandorder_jp_feed", "name": "Fate/Grand Order攻略情報まとめ", "url": "http://fate-grandorder.jp/?feed=rss2"},
    {"id": "jpsoku_blog_jp", "name": "じゃぱそく！", "url": "http://jpsoku.blog.jp/index.rdf"},
    {"id": "datsuaron_blog_jp", "name": "脱亜論", "url": "http://datsuaron.blog.jp/index.rdf"},
    {"id": "pitch_bat_com", "name": "投打スタジアムCH", "url": "https://pitch-bat.com/feed"},
    {"id": "xn_hhr014byylm9m90fi1p_com", "name": "荒野行動攻略まとめ隊", "url": "https://xn--hhr014byylm9m90fi1p.com/feed"},
    {"id": "xn_mckr6j9b9367e_com", "name": "ロマサガRS攻略まとめ隊", "url": "https://xn--mckr6j9b9367e.com/feed"},
    {"id": "xn_eckhu0c0d1b5kcu5305ksfpb_com", "name": "ドラクエライバルズ攻略まとめ隊", "url": "https://xn--eckhu0c0d1b5kcu5305ksfpb.com/feed"},
    {"id": "xn_gdkl0dubtwb7e_net", "name": "モンハンワールド攻略まとめ隊", "url": "https://xn--gdkl0dubtwb7e.net/feed"},
    {"id": "xn_o9j0bk3mocyap0jsh2eyam2gf4k_net", "name": "ドラゴンボールレジェンズ攻略まとめ隊", "url": "https://xn--o9j0bk3mocyap0jsh2eyam2gf4k.net/feed"},
    {"id": "xn_o9j0bk9175aoqh34d491f_com", "name": "ドールズフロントライン 攻略まとめ隊", "url": "https://xn--o9j0bk9175aoqh34d491f.com/feed"},
    {"id": "xn_zcka9bza7pybd5118hco4a_com", "name": "ハースストーン攻略まとめ速報", "url": "https://xn--zcka9bza7pybd5118hco4a.com/feed"},
    {"id": "xn_o9j0bk9l8cn4i9byj2jo863c0ssb_com", "name": "シャドウバース攻略まとめ隊", "url": "https://xn--o9j0bk9l8cn4i9byj2jo863c0ssb.com/feed"},
    {"id": "xn_o9j0bk1rwe8bvh_com", "name": "プリコネ攻略まとめ隊", "url": "https://xn--o9j0bk1rwe8bvh.com/feed"},
    {"id": "xn_o9j0bk5t7exbwe_com", "name": "スマブラ攻略まとめ隊", "url": "https://xn--o9j0bk5t7exbwe.com/feed"},
    {"id": "xn_fgo_gh8fn72e_com", "name": "FGO攻略まとめ隊", "url": "https://xn--fgo-gh8fn72e.com/feed"},
    {"id": "xn_ccke6azf2a21a_gamerstand_net", "name": "アークナイツ攻略まとめGS", "url": "https://xn--ccke6azf2a21a.gamerstand.net/feed"},
    {"id": "gamerstand_net_srw_dd", "name": "スパロボDD攻略まとめ GAMER STAND", "url": "https://gamerstand.net/srw-dd/feed"},
    {"id": "xn_ndk9au4b_gamerstand_net", "name": "ランモバ攻略まとめGS", "url": "https://xn--ndk9au4b.gamerstand.net/feed"},
    {"id": "ffbe_wotv_gamerstand_net", "name": "FFBE幻影戦争 攻略まとめGS", "url": "https://ffbe-wotv.gamerstand.net/feed"},
    {"id": "xn_ick1c6c0a_gamerstand_net", "name": "デュエプレ攻略まとめ GS", "url": "https://xn--ick1c6c0a.gamerstand.net/feed"},
    {"id": "netizen_voice_blog_jp", "name": "ネラーボイス", "url": "http://netizen-voice.blog.jp/index.rdf"},
    {"id": "keyakizaka46matomemory_net", "name": "欅坂46まとめもり～", "url": "http://keyakizaka46matomemory.net/index.rdf"},
    {"id": "46matome_net", "name": "日向坂46まとめもり～", "url": "http://46matome.net/index.rdf"},
    {"id": "draquewalk_blog_fc2_com", "name": "ドラクエウォーク速報", "url": "https://draquewalk.blog.fc2.com/?xml"},
    {"id": "xn_fgo_yb4b8dta56dif_xyz", "name": "FGOまとめマン速報", "url": "https://xn--fgo-yb4b8dta56dif.xyz/feed/"},
    {"id": "fgonovum_com", "name": "FGOノウムカルデア攻略速報", "url": "https://fgonovum.com/feed/"},
    {"id": "moerunihon_blog_jp", "name": "もえるにほん彡(^)(^)", "url": "http://moerunihon.blog.jp/index.rdf"},
    {"id": "pawapuro_xyz_feed", "name": "パワ速@プロスピA攻略まとめ", "url": "http://pawapuro.xyz/?feed=rss2"},
    {"id": "hachinai_net_feed", "name": "ハチナイ速報＠八月のシンデレラナイン攻略まとめ", "url": "http://hachinai.net/?feed=rss2"},
    {"id": "blog_livedoor_jp_daunti", "name": "おフトンからまとめ", "url": "http://blog.livedoor.jp/daunti/index.rdf"},
    {"id": "blog_livedoor_jp_himacyan", "name": "2chまとめ放題", "url": "http://blog.livedoor.jp/himacyan/index.rdf"},
    {"id": "jumpmatome2ch_net", "name": "超・ジャンプまとめ速報", "url": "https://jumpmatome2ch.net/feed"},
    {"id": "hnbnfun_blog_jp", "name": "ほのぼのしない動物速報 (Ф∀Ф)", "url": "http://hnbnfun.blog.jp/index.rdf"},
    {"id": "pokemongo_kouryakumatome_net", "name": "ポケモンGO攻略まとめ速報！！", "url": "http://pokemongo-kouryakumatome.net/index.rdf"},
    {"id": "kamenrider2_net", "name": "仮面ライダーまとめ２号", "url": "http://kamenrider2.net/feed"},
    {"id": "nioh_more_gamer_com", "name": "仁王まとめ速報｜仁王2", "url": "http://nioh.more-gamer.com/feed"},
    {"id": "shikaku105_blog_jp", "name": "2chNEWSまとめ", "url": "http://shikaku105.blog.jp/index.rdf"},
    {"id": "basketballbbs_com", "name": "バスケまとめ・COM", "url": "http://basketballbbs.com/feed/"},
    {"id": "butumori_com", "name": "どうぶつの森まとめ速報", "url": "http://butumori.com/index.rdf"},
    {"id": "baseball_nanj_com", "name": "きうり♪やきう♪きうり♪＠なんJ", "url": "http://baseball-nanj.com/?xml"},
    {"id": "soccer_time_net", "name": "サッカータイム", "url": "https://soccer-time.net/index.rdf"},
    {"id": "slo_matome_com_category_news", "name": "スロカク | パチスロデータ格付けブログ", "url": "https://slo-matome.com/category/news/feed/"},
    {"id": "tabinolog_com", "name": "旅のろぐ", "url": "https://tabinolog.com/feed"},
    {"id": "slotlog_net", "name": "パチスロログ", "url": "https://slotlog.net/feed"},
    {"id": "parlourfullslotl_com", "name": "パーラーフルスロットル", "url": "https://parlourfullslotl.com/feed"},
    {"id": "continent_news_blog_jp", "name": "大陸日報", "url": "http://continent-news.blog.jp/atom.xml"},
    {"id": "ps5sokunews_com_feed", "name": "PS5速報", "url": "https://ps5sokunews.com//?feed=rss2"},
    {"id": "baiku_life_com", "name": "バイクライフちゃんねる", "url": "https://baiku-life.com/feed"},
    {"id": "holosoku_com", "name": "ホロ速", "url": "https://holosoku.com/feed/"},
    {"id": "kaji2jimu_work", "name": "かじとじむ", "url": "https://kaji2jimu.work/index.rdf"},
    {"id": "brow2ing_com", "name": "ブラブラブラウジング", "url": "http://brow2ing.com/index.rdf"},
    {"id": "betweenjpandkr_blog", "name": "ニチカン!", "url": "https://betweenjpandkr.blog/feed"},
    {"id": "www_2monkeys_jp", "name": "2chまとめ・読み物・長編・名作/2MONKEYS.JP", "url": "http://www.2monkeys.jp/index.rdf"},
    {"id": "toychan_blog_jp", "name": "トーイチャンネット", "url": "http://toychan.blog.jp/index.rdf"},
    {"id": "matomeru1_livedoor_blog", "name": "まとめる", "url": "http://matomeru1.livedoor.blog/index.rdf"},
    {"id": "fgo_babylonia_cafe_jp", "name": "ばびろにあっ！", "url": "https://fgo-babylonia-cafe.jp/feed/"},
    {"id": "precurematome_com", "name": "プリキュアのまとめ", "url": "http://precurematome.com/feed/"},
    {"id": "blog_livedoor_jp_kumokumowatawata", "name": "コイン速報 | 仮想通貨ニュース・暗号資産相場情報・5chまとめ", "url": "http://blog.livedoor.jp/kumokumowatawata/index.rdf"},
    {"id": "blog_livedoor_jp_waruneko00326_002", "name": "歴史的速報", "url": "http://blog.livedoor.jp/waruneko00326-002/index.rdf"},
    {"id": "akb48team8_net", "name": "チーム8まとめりか(AKB48Team8まとめ)", "url": "http://akb48team8.net/feed/"},
    {"id": "medakamatome_tokyo", "name": "まとめだかニュース速報＠", "url": "http://medakamatome.tokyo/index.rdf"},
    {"id": "jiwachan_net", "name": "じわるチャンネル-雑談まとめブログ-", "url": "http://jiwachan.net/index.rdf"},
    {"id": "syurabake_com", "name": "修羅場家の日常", "url": "http://syurabake.com/index.rdf"},
    {"id": "fgochaldeas_com", "name": "FGOまとめ　カルデア速報", "url": "http://fgochaldeas.com/index.rdf"},
    {"id": "blog_livedoor_jp_kijyonoyaiba", "name": "鬼女の刃", "url": "http://blog.livedoor.jp/kijyonoyaiba/index.rdf"},
    {"id": "gooddays_wedding_com", "name": "女と男の幸せがいっぱい", "url": "http://gooddays-wedding.com/feed/"},
    {"id": "kekkon_souken_com", "name": "結婚総研", "url": "http://kekkon-souken.com/index.rdf"},
    {"id": "blog_livedoor_jp_gotisoku", "name": "ごちそう速報", "url": "http://blog.livedoor.jp/gotisoku/index.rdf"},
    {"id": "dsara_blog_fc2_com", "name": "ネット民の反応：国内・海外のゲーム・アニメの反応まとめ！", "url": "https://dsara.blog.fc2.com/?xml"},
    {"id": "vipperlog_com", "name": "VIPPERlog", "url": "http://vipperlog.com/index.rdf"},
    {"id": "abroadch_com", "name": "アブロードチャンネル｜サッカー専門の海外の反応サイト", "url": "https://abroadch.com/feed/"},
    {"id": "estalucia_com", "name": "グラブルまとめ！いすたるしあ通信", "url": "https://estalucia.com/feed"},
    {"id": "ske48matomemo_doorblog_jp", "name": "SKE48まとめもらんだむ", "url": "http://ske48matomemo.doorblog.jp/index.rdf"},
    {"id": "vtubernews_jp", "name": "VTuberNews", "url": "http://vtubernews.jp/index.rdf"},
    {"id": "blog_livedoor_jp_morning77", "name": "ハロプロ×LIFE", "url": "http://blog.livedoor.jp/morning77/index.rdf"},
    {"id": "pokemonunite_blog_fc2_com", "name": "ポケモンユナイト作戦会議", "url": "https://pokemonunite.blog.fc2.com/?xml"},
    {"id": "vtubersokuhou_com", "name": "ぶいちゅーばー速報", "url": "http://vtubersokuhou.com/feed"},
    {"id": "vrtuber_news_com", "name": "Vtuber速報@バーチャルYouTuberまとめ", "url": "http://vrtuber-news.com/index.rdf"},
    {"id": "blog_livedoor_jp_madoyuka", "name": "ゲーハーの窓", "url": "http://blog.livedoor.jp/madoyuka//index.rdf"},
    {"id": "zapzapjp_com", "name": "ZAPZAP!", "url": "https://zapzapjp.com/index.rdf"},
    {"id": "matome_new_com_feed", "name": "新5chまとめ速報-ネオ速-", "url": "https://matome-new.com//?feed=rss2"},
    {"id": "20xxnyu_su_blog_jp", "name": "20ＸＸニュース", "url": "http://20xxnyu-su.blog.jp/index.rdf"},
    {"id": "geolog_book_com", "name": "ジオろぐ", "url": "http://geolog-book.com/index.rdf"},
    {"id": "nida_aru_com", "name": "ニダアル速報＋", "url": "http://nida-aru.com/index.rdf"},
    {"id": "www_giogio48_com", "name": "GIOGIOの奇妙な速報‐AKB48・チーム8まとめたの", "url": "http://www.giogio48.com/index.rdf"},
    {"id": "nmbfan_seesaa_net_index20", "name": "NMB時々AKBとか", "url": "http://nmbfan.seesaa.net/index20.rdf"},
    {"id": "blog_livedoor_jp_nanjmagnus", "name": "なんＪは加速している", "url": "http://blog.livedoor.jp/nanjmagnus/index.rdf"},
    {"id": "pachinkolist_com", "name": "ぱちんこドキュメント!!", "url": "http://pachinkolist.com/index.rdf"},
    {"id": "yuitannel_blog_jp", "name": "ゆいたんねる", "url": "https://yuitannel.blog.jp/index.rdf"},
    {"id": "jinniro_blog_fc2_com", "name": "プロ野球いろいろ速報", "url": "http://jinniro.blog.fc2.com/?xml"},
    {"id": "shitsumonaru_com", "name": "為になる？質問ある？まとめ", "url": "http://shitsumonaru.com/feed"},
    {"id": "vtuber_matomeruyon_blog_jp", "name": "Vtuberまとめるよ～ん", "url": "http://vtuber-matomeruyon.blog.jp/index.rdf"},
    {"id": "o2military_blog_jp", "name": "軍事・ミリタリーログ", "url": "http://o2military.blog.jp/index.rdf"},
    {"id": "love_knowledge_com", "name": "知識の城　群雄割拠", "url": "https://love-knowledge.com/feed"},
    {"id": "keibapedia_com_feed", "name": "ケイバペディア", "url": "https://keibapedia.com/?feed=rss2"},
    {"id": "trombonechannel_net", "name": "ボントロちゃんねる", "url": "https://trombonechannel.net/feed"},
    {"id": "shukichisokuhou_blog", "name": "しゅーキチ速報", "url": "http://shukichisokuhou.blog/index.rdf"},
    {"id": "shurarara_monogatari_com", "name": "しゅららら物語", "url": "https://shurarara-monogatari.com/feed/"},
    {"id": "geininsokuhou_com", "name": "お笑いまとめ　芸人速報", "url": "https://geininsokuhou.com/feed"},
    {"id": "ikumamasokuhou_com", "name": "育ママ速報", "url": "http://ikumamasokuhou.com/index.rdf"},
    {"id": "uma_log_net", "name": "うまろぐ", "url": "https://uma-log.net/feed/"},
    {"id": "mcri_blog_feed", "name": "マクド総研", "url": "http://mcri.blog/?feed=rss2"},
    {"id": "mari_soku_com", "name": "まりえる速報", "url": "https://mari-soku.com/feed/"},
    {"id": "netshogimatome_blog_fc2_com", "name": "ネト将まとめ", "url": "https://netshogimatome.blog.fc2.com/?xml"},
    {"id": "geinou_7days_net", "name": "芸能7days", "url": "http://geinou-7days.net/feed"},
    {"id": "metabopro_net", "name": "ぱちとろ速報", "url": "https://metabopro.net/feed"},
    {"id": "www_ballparksokuhou_com", "name": "ボールパーク速報 海外の反応", "url": "https://www.ballparksokuhou.com/?xml"},
    {"id": "marutoo_com", "name": "まるっと翻訳", "url": "https://marutoo.com/feed"},
    {"id": "blog_sky_spider_com", "name": "自虐史感から脱却して世界を見る", "url": "https://blog.sky-spider.com/index.xml"},
    {"id": "gadjeizu_net_feed", "name": "ガジェットの泉ちゃんねる", "url": "https://gadjeizu.net/?feed=rss2"},
    {"id": "netsokuhou_seesaa_net_index20", "name": "ネット速報まとめ超", "url": "https://netsokuhou.seesaa.net/index20.rdf"},
    {"id": "hbr_square_com", "name": "ヘブバン広場", "url": "https://hbr-square.com/feed/"},
    {"id": "azurlane_sokuhou_com_feed", "name": "アズレン速報", "url": "https://azurlane-sokuhou.com/?feed=rss2"},
    {"id": "sduhrk_livedoor_blog", "name": "アニメの総合集", "url": "https://sduhrk.livedoor.blog/index.rdf"},
    {"id": "moon0502_blog_jp", "name": "VTuberまとめ情報", "url": "http://moon0502.blog.jp/index.rdf"},
    {"id": "neochisokuhou_net", "name": "寝落ち速報", "url": "https://neochisokuhou.net/feed/"},
    {"id": "jijinews_online", "name": "時事ネタニュース速報", "url": "http://jijinews.online/index.rdf"},
    {"id": "oishiimatome_com", "name": "おいしいまとめ", "url": "https://oishiimatome.com/?xml"},
    {"id": "invest_news_source_com_feed", "name": "投資ネタ集めておいたのだ！", "url": "https://invest-news-source.com/?feed=rss2"},
    {"id": "ksakamo0903_com", "name": "わちゃくちゃ速報", "url": "https://ksakamo0903.com/feed/"},
    {"id": "gootore_xyz_feed", "name": "僕青ちゃんねる", "url": "https://gootore.xyz/?feed=rss2"},
    {"id": "hpupdate_info_feed", "name": "ハロアップデート", "url": "https://hpupdate.info/?feed=rss2"},
    {"id": "www_syurasan_com", "name": "しゅらさん｜キチママ・修羅場の生活まとめ", "url": "https://www.syurasan.com/?xml"},
    {"id": "metyayaba_com_feed", "name": "めちゃヤバ速報", "url": "https://metyayaba.com/?feed=rss2"},
    {"id": "df_browser_games_com", "name": "ブラウザゲーム速報", "url": "https://df-browser-games.com/?xml"},
    {"id": "nogizakajyoho46_com", "name": "ネタンゴ！", "url": "https://nogizakajyoho46.com/index.rdf"},
    {"id": "ad_ars_line_blog_feed", "name": "Collect animations", "url": "https://ad-ars-line.blog/?feed=rss2"},
    {"id": "matomemento_com_feed_rdf", "name": "爆速まとめめんと", "url": "https://matomemento.com/feed/rdf/"},
    {"id": "reddit_matome_com", "name": "Ask Reddit まとめ", "url": "https://reddit-matome.com/feed"},
    {"id": "sekai_zukan_blog", "name": "世界反応図鑑", "url": "https://sekai-zukan.blog/feed/"},
    {"id": "giants_pride_news_com_category_giants", "name": "GIANTS PRIDE ニュース", "url": "https://giants-pride-news.com/category/giants/feed/"},
    {"id": "nogizakalife_tokyo_feed", "name": "乃木坂LIFE -坂道・48高速まとめ-", "url": "https://nogizakalife.tokyo/?feed=rss2"},
    {"id": "red4_kaigaimatome_com", "name": "Red4 海外の反応まとめ", "url": "https://red4-kaigaimatome.com/feed/"},
    {"id": "keizai4567_blog_jp", "name": "投資.com", "url": "https://keizai4567.blog.jp/index.rdf"},
    {"id": "halospo_com", "name": "ハロスポ＠ハロプロまとめ", "url": "https://halospo.com/feed/"},
    {"id": "sekahan0623_com", "name": "せかはん（世界の反応）", "url": "https://sekahan0623.com/feed"},
]
